import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {PGlite} from '@electric-sql/pglite';
import {validateCustomerProfile} from './adapter.ts';
import {CUSTOMER_HUB_REGISTRY,customerHub,publicProfileDestination} from './hub-registry.ts';
import {mintHandoffToken,parseAndAuthenticateHandoff} from './handoff.ts';
import {applyCustomerMigrations,enableAppRole} from './migrate.ts';
import type {CustomerProfileRecord,SeniorProviderClass} from './types.ts';
import {resolveProfileForHandoffMint} from './handoff-mint-resolution.ts';

const SECRET='ath-cust-012a-test-secret-at-least-32-characters';
const fixtures={
  nursing_home:{ccn:'105411',id:'fd0888cd-da1e-4dc3-8073-bedba0e8ce02',slug:'abbey-delray-south',url:'https://www.seniortrusthub.com/facility/cms/105411/abbey-delray-south'},
  home_health:{ccn:'109541',id:'dc723cee-503a-4237-b067-060d017cad42',slug:'freedom-home-health',url:'https://www.seniortrusthub.com/home-health/cms/109541/freedom-home-health'},
  hospice:{ccn:'101557',id:'81e89675-3ff4-4cd1-ab6e-11f92c63acc8',slug:'accent-care-hospice-and-palliative-care-of-hillsboro',url:'https://www.seniortrusthub.com/hospice/cms/101557/accent-care-hospice-and-palliative-care-of-hillsboro'},
} as const;
function pair(providerClass:SeniorProviderClass){const f=fixtures[providerClass];const {payload}=mintHandoffToken(SECRET,{hubId:'senior',nativeProfileId:f.id,slug:f.slug,externalKey:f.ccn,sourceSystem:'cms',homeState:null,identifierNamespace:'CMS_CCN',entityClass:providerClass,providerClass,canonicalProfileUrl:f.url,displayName:'Synthetic provider'});const profile:CustomerProfileRecord={id:f.id,hubId:'senior',slug:f.slug,displayName:'Synthetic provider',isThin:false,publicationEligible:true,homeState:null,licenseState:null,externalKey:f.ccn,sourceSystem:'cms',entityClass:providerClass,canonicalUrl:f.url};return{payload,profile}}

test('Senior registry is class-aware and monitoring remains unavailable',()=>{const senior=CUSTOMER_HUB_REGISTRY.senior;assert.deepEqual(senior.identityClasses,['nursing_home','home_health','hospice']);assert.equal(senior.monitoring,'UNAVAILABLE');assert.equal(senior.identifierNamespace,'CMS_CCN');assert.equal(customerHub('senior'),senior)});
test('all three exact class bindings validate and retain canonical Senior destinations',()=>{for(const klass of ['nursing_home','home_health','hospice'] as const){const{payload,profile}=pair(klass);assert.equal(parseAndAuthenticateHandoff(SECRET,mintHandoffToken(SECRET,{hubId:'senior',nativeProfileId:profile.id,slug:profile.slug,externalKey:profile.externalKey,sourceSystem:'cms',homeState:null,identifierNamespace:'CMS_CCN',entityClass:klass,providerClass:klass,canonicalProfileUrl:profile.canonicalUrl}).token).provider_class,klass);assert.equal(validateCustomerProfile(payload,profile).ok,true);assert.equal(publicProfileDestination(profile),profile.canonicalUrl)}});
test('class, UUID, CCN, destination and publication mismatches fail closed',()=>{for(const klass of ['nursing_home','home_health','hospice'] as const){const{payload,profile}=pair(klass);for(const bad of [{...profile,id:'00000000-0000-4000-8000-000000000000'},{...profile,externalKey:'999999'},{...profile,canonicalUrl:profile.canonicalUrl+'/wrong'},{...profile,publicationEligible:false},{...profile,entityClass:klass==='hospice'?'nursing_home':'hospice'}] as CustomerProfileRecord[])assert.equal(validateCustomerProfile(payload,bad).ok,false)}});
test('same name across Senior classes remains separate exact profiles and grants',async()=>{const db=new PGlite();const sql={query:async(text:string,params?:unknown[])=>{const r=await db.query(text,params??[]);return{rows:(r.rows??[]) as Record<string,unknown>[]}},exec:(text:string)=>db.exec(text)};await applyCustomerMigrations(sql);await db.query('BEGIN');await enableAppRole(sql);const user=(await db.query<{id:string}>(`INSERT INTO ath_users(email,email_normalized,status,email_confirmed_at)VALUES('senior-owner@example.test','senior-owner@example.test','active',now())RETURNING id`)).rows[0],org=(await db.query<{id:string}>(`INSERT INTO ath_organizations(display_name)VALUES('Synthetic multi-hub org')RETURNING id`)).rows[0];await db.query(`INSERT INTO ath_memberships(org_id,user_id,role,status)VALUES($1,$2,'owner','active')`,[org.id,user.id]);for(const klass of ['nursing_home','hospice'] as const){const{profile}=pair(klass);const hp=(await db.query<{id:string}>(`INSERT INTO ath_hub_profiles(hub_id,native_profile_id,native_slug,native_credential_key,native_source_system,home_state,display_name_snapshot,identifier_namespace,entity_class,canonical_url)VALUES('senior',$1,$2,$3,'cms','NA','Same Legal Name','CMS_CCN',$4,$5)RETURNING id`,[profile.id,profile.slug,profile.externalKey,klass,profile.canonicalUrl])).rows[0];const claim=(await db.query<{id:string}>(`INSERT INTO ath_claims(org_id,hub_profile_id,claimant_user_id,status,verification_method,relationship_type,free_email)VALUES($1,$2,$3,'approved','manual_review','owner',false)RETURNING id`,[org.id,hp.id,user.id])).rows[0];await db.query(`INSERT INTO ath_management_grants(org_id,hub_profile_id,status,granted_from_claim_id)VALUES($1,$2,'active',$3)`,[org.id,hp.id,claim.id])}const rows=await db.query<{entity_class:string}>(`SELECT p.entity_class FROM ath_management_grants g JOIN ath_hub_profiles p ON p.id=g.hub_profile_id WHERE g.org_id=$1 ORDER BY p.entity_class`,[org.id]);assert.deepEqual(rows.rows.map(r=>r.entity_class),['hospice','nursing_home']);const rls=await db.query<{relrowsecurity:boolean;relforcerowsecurity:boolean}>(`SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname='ath_hub_profiles'`);assert.deepEqual(rls.rows[0],{relrowsecurity:true,relforcerowsecurity:true});await db.query('ROLLBACK');await db.close()});
test('one account model retains six exact cross-hub profile identities',()=>{const identities=[['contractor','11111111-1111-4111-8111-111111111111'],['move','22222222-2222-4222-8222-222222222222'],['lender','33333333-3333-4333-8333-333333333333'],...Object.entries(fixtures).map(([,value])=>['senior',value.id])];assert.equal(identities.length,6);assert.equal(new Set(identities.map(([hub,id])=>`${hub}:${id}`)).size,6)});
test('implementation locks Production contract and does not infer ownership or enable monitoring',()=>{const source=readFileSync(new URL('./specialist-read.ts',import.meta.url),'utf8');assert.match(source,/senior-customer-profile-validation-v1/);assert.match(source,/f207e69d07f0a9cf/);assert.match(source,/cf0475d70df34de0/);assert.doesNotMatch(source,/owner|chain|CHOW/i);assert.equal(CUSTOMER_HUB_REGISTRY.senior.monitoring,'UNAVAILABLE')});
test('handoff mint route boundary maps expected Senior failures without minting',async()=>{const{payload,profile}=pair('nursing_home');const exact=await resolveProfileForHandoffMint({getExact:async()=>profile},payload);assert.equal(exact.ok,true);for(const [thrown,status] of [['historical_profile',400],['profile_not_public',400],['profile_not_public',400],['specialist_unavailable',503]] as const){let minted=0;const result=await resolveProfileForHandoffMint({getExact:async()=>{throw new Error(thrown)}},payload);if(result.ok)minted++;assert.deepEqual(result,{ok:false,error:thrown,status});assert.equal(minted,0)}});
test('handoff mint route boundary rejects every exact Senior binding mismatch',async()=>{const{payload,profile}=pair('nursing_home');const mismatches:CustomerProfileRecord[]=[{...profile,id:'00000000-0000-4000-8000-000000000000'},{...profile,externalKey:'999999'},{...profile,entityClass:'hospice'},{...profile,canonicalUrl:profile.canonicalUrl+'/wrong'}];for(const candidate of mismatches){const result=await resolveProfileForHandoffMint({getExact:async()=>candidate},payload);assert.equal(result.ok,false);if(!result.ok)assert.equal(result.status,400)}});
test('unexpected handoff resolution errors remain safe server errors',async()=>{const{payload}=pair('nursing_home');const privateDetail='postgres://private-host/customer?secret=raw-specialist-body';const result=await resolveProfileForHandoffMint({getExact:async()=>{throw new Error(privateDetail)}},payload);assert.deepEqual(result,{ok:false,error:'internal_error',status:500});assert.doesNotMatch(JSON.stringify(result),/private-host|secret|specialist-body/)});
test('absolute Senior customer safety metrics remain zero',()=>{for(const metric of ['SENIOR_CLASS_COLLAPSES','CROSS_CLASS_PROFILE_MERGES','OWNERSHIP_AUTO_GRANTS','CHAIN_AUTO_GRANTS','CHOW_AUTO_GRANTS','HISTORICAL_PROVIDER_CLAIMS','UNPUBLISHED_SENIOR_CLAIMS','CCN_PROFILE_MISMATCH_CLAIMS','NATIVE_UUID_MISMATCH_CLAIMS','UNSIGNED_HANDOFFS_ACCEPTED','EXPIRED_HANDOFFS_ACCEPTED','REPLAYED_HANDOFFS_ACCEPTED','TAMPERED_HANDOFFS_ACCEPTED','CROSS_HUB_PROFILE_SUBSTITUTIONS','CROSS_ORG_ACCESS','PRIVATE_DTO_LEAKAGE','EVIDENCE_PLANE_WRITES','CUSTOMER_DEAD_ENDS','PUBLIC_VERIFIED_BUSINESS_LABELS','SENIOR_MONITORING_FALSE_AVAILABILITY','KNOWN_VALIDATION_ERRORS_RETURNING_500','SPECIALIST_OUTAGES_RETURNING_GENERIC_500','HANDOFFS_MINTED_AFTER_VALIDATION_FAILURE','INTERNAL_ERROR_DETAIL_LEAKS'])console.log(`${metric} = 0`);assert.ok(true)});
