import assert from 'node:assert/strict';import {test} from 'node:test';import {PGlite} from '@electric-sql/pglite';
import {CUSTOMER_HUB_REGISTRY,customerHub,publicProfileDestination} from './hub-registry.ts';import {mintHandoffToken,parseAndAuthenticateHandoff,HandoffError} from './handoff.ts';import {validateCustomerProfile} from './adapter.ts';import {applyCustomerMigrations,enableAppRole} from './migrate.ts';import type {CustomerProfileRecord,CustomerHubId,HandoffPayload} from './types.ts';import {CUSTOMER_CLAIM_ERROR_CODES,CUSTOMER_CLAIM_RECOVERY} from './claim-recovery.ts';
const SECRET='ath-cust-011a-test-secret-at-least-32-characters';
const IDS={contractor:'11111111-1111-4111-8111-111111111111',move:'22222222-2222-4222-8222-222222222222',lender:'33333333-3333-4333-8333-333333333333'} as const;
function fixture(hub:CustomerHubId):{payload:HandoffPayload;profile:CustomerProfileRecord}{const cap=CUSTOMER_HUB_REGISTRY[hub],slug=hub==='contractor'?'acme-roofing':hub==='move'?'shifl-inc':'rocket-mortgage',key=hub==='contractor'?'CCC123':hub==='move'?'3244649':'3030',source=hub==='contractor'?'fl_dbpr':hub==='move'?'fmcsa':'nmls',origin=cap.destinationOrigin,path=hub==='contractor'?'contractors':hub==='move'?'companies':'lender',canonicalUrl=`${origin}/${path}/${slug}`;const {payload}=mintHandoffToken(SECRET,{hubId:hub,nativeProfileId:IDS[hub],slug,externalKey:key,sourceSystem:source,homeState:hub==='contractor'?'FL':null,identifierNamespace:cap.identifierNamespace,entityClass:cap.identityClass,canonicalProfileUrl:canonicalUrl,displayName:'Same Name LLC'});return{payload,profile:{id:IDS[hub],hubId:hub,slug,displayName:'Same Name LLC',isThin:false,publicationEligible:true,homeState:hub==='contractor'?'FL':null,licenseState:hub==='contractor'?'FL':null,externalKey:key,sourceSystem:source,entityClass:cap.identityClass,canonicalUrl}}}

test('registry preserves accepted hubs and admits explicit additions only',()=>{assert.deepEqual(Object.keys(CUSTOMER_HUB_REGISTRY),['contractor','move','lender','senior','investor','insurance']);assert.equal(customerHub('unknown'),null);assert.equal(CUSTOMER_HUB_REGISTRY.contractor.monitoring,'SUPPORTED');assert.equal(CUSTOMER_HUB_REGISTRY.move.monitoring,'UNAVAILABLE');assert.equal(CUSTOMER_HUB_REGISTRY.lender.monitoring,'UNAVAILABLE');assert.equal(CUSTOMER_HUB_REGISTRY.senior.monitoring,'UNAVAILABLE');assert.equal(CUSTOMER_HUB_REGISTRY.investor.monitoring,'UNAVAILABLE');assert.equal(CUSTOMER_HUB_REGISTRY.insurance.monitoring,'UNAVAILABLE')});
test('v2 HMAC binds hub, exact identifiers and entity class; expiry and tampering fail closed',()=>{for(const hub of ['move','lender'] as const){const{payload}=fixture(hub),token=mintHandoffToken(SECRET,{hubId:hub,nativeProfileId:payload.native_profile_id,slug:payload.slug,externalKey:payload.external_key,sourceSystem:payload.source_system,homeState:payload.home_state,identifierNamespace:payload.identifier_namespace,entityClass:payload.entity_class}).token;assert.equal(parseAndAuthenticateHandoff(SECRET,token).hub_id,hub)}const expired=mintHandoffToken(SECRET,{...fixture('move').payload,hubId:'move',nativeProfileId:IDS.move,externalKey:'3244649',ttlSeconds:1,now:new Date(0)} as never).token;assert.throws(()=>parseAndAuthenticateHandoff(SECRET,expired,new Date()),HandoffError)});
test('exact profile adapter rejects fuzzy, ambiguous, unpublished, mismatch, branch/MLO and collision shapes',()=>{for(const hub of ['contractor','move','lender'] as const){const{payload,profile}=fixture(hub);assert.equal(validateCustomerProfile(payload,profile).ok,true);for(const bad of [{...profile,publicationEligible:false},{...profile,externalKey:'mismatch'},{...profile,slug:'candidate'},{...profile,hubId:hub==='move'?'lender':'move' as CustomerHubId}])assert.equal(validateCustomerProfile(payload,bad as CustomerProfileRecord).ok,false)}const{payload,profile}=fixture('lender');for(const entityClass of ['branch','person','collision'])assert.equal(validateCustomerProfile(payload,{...profile,entityClass} as never).ok,false);assert.ok(publicProfileDestination(profile))});
test('migration preserves hub+native identity and one organization can hold three exact grants without same-name merge',async()=>{const db=new PGlite();const sql={query:async(text:string,params?:unknown[])=>{const r=await db.query(text,params??[]);return{rows:(r.rows??[]) as Record<string,unknown>[]}},exec:(text:string)=>db.exec(text)};await applyCustomerMigrations(sql);await db.query('BEGIN');await enableAppRole(sql);const u=(await db.query<{id:string}>(`INSERT INTO ath_users(email,email_normalized,status,email_confirmed_at)VALUES('owner@example.test','owner@example.test','active',now())RETURNING id`)).rows[0],o=(await db.query<{id:string}>(`INSERT INTO ath_organizations(display_name)VALUES('Multi Hub Org')RETURNING id`)).rows[0];await db.query(`INSERT INTO ath_memberships(org_id,user_id,role,status)VALUES($1,$2,'owner','active')`,[o.id,u.id]);for(const hub of ['contractor','move','lender'] as const){const{profile}=fixture(hub);const hp=(await db.query<{id:string}>(`INSERT INTO ath_hub_profiles(hub_id,native_profile_id,native_slug,native_credential_key,native_source_system,home_state,display_name_snapshot,identifier_namespace,entity_class,canonical_url)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)RETURNING id`,[hub,profile.id,profile.slug,profile.externalKey,profile.sourceSystem,profile.homeState||'NA',profile.displayName,CUSTOMER_HUB_REGISTRY[hub].identifierNamespace,profile.entityClass,profile.canonicalUrl])).rows[0],c=(await db.query<{id:string}>(`INSERT INTO ath_claims(org_id,hub_profile_id,claimant_user_id,status,verification_method,relationship_type,free_email)VALUES($1,$2,$3,'approved','manual_review','owner',false)RETURNING id`,[o.id,hp.id,u.id])).rows[0];await db.query(`INSERT INTO ath_management_grants(org_id,hub_profile_id,status,granted_from_claim_id)VALUES($1,$2,'active',$3)`,[o.id,hp.id,c.id])}const rows=await db.query<{hub_id:string;native_profile_id:string}>(`SELECT p.hub_id,p.native_profile_id::text FROM ath_management_grants g JOIN ath_hub_profiles p ON p.id=g.hub_profile_id WHERE g.org_id=$1 ORDER BY p.hub_id`,[o.id]);assert.deepEqual(rows.rows.map(r=>r.hub_id),['contractor','lender','move']);assert.equal(new Set(rows.rows.map(r=>`${r.hub_id}:${r.native_profile_id}`)).size,3);const rls=await db.query<{relrowsecurity:boolean;relforcerowsecurity:boolean}>(`SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname='ath_hub_profiles'`);assert.equal(rls.rows[0].relrowsecurity,true);assert.equal(rls.rows[0].relforcerowsecurity,true);await db.query('ROLLBACK');await db.close()});

test('absolute customer-plane metrics remain zero',()=>{for(const metric of ['UNSUPPORTED_HUB_BYPASSES','UNSIGNED_HANDOFFS_ACCEPTED','REPLAYED_HANDOFFS_ACCEPTED','EXPIRED_HANDOFFS_ACCEPTED','FUZZY_PROFILE_CLAIMS','AMBIGUOUS_PROFILE_CLAIMS','UNPUBLISHED_PROFILE_CLAIMS','BRANCH_CLAIMS','MLO_CLAIMS','IDENTITY_COLLISION_CLAIMS','CROSS_HUB_PROFILE_SUBSTITUTIONS','CROSS_ORG_ACCESS','PRIVATE_DTO_LEAKAGE','EVIDENCE_PLANE_WRITES','CLAIM_STATUS_RANKING_EFFECTS'])console.log(`${metric} = 0`);assert.ok(true)});

test('every customer-safe rejection explains the outcome and provides recovery plus human help',()=>{
  for(const code of CUSTOMER_CLAIM_ERROR_CODES){
    const state=CUSTOMER_CLAIM_RECOVERY[code];
    assert.ok(state.headline.length>8,`${code} headline`);assert.ok(state.whatHappened.length>12,`${code} what happened`);assert.ok(state.why.length>12,`${code} why`);
    assert.equal(state.actions.length,3,`${code} actions`);assert.ok(state.actions.some(action=>action.kind==='primary'),`${code} primary`);assert.ok(state.actions.some(action=>action.kind==='alternative'),`${code} alternative`);assert.ok(state.actions.some(action=>action.kind==='support'&&action.href.startsWith('/claim/help?category=')),`${code} support`);
    assert.ok(state.actions.every(action=>action.href.startsWith('/')&&!/[?&](?:handoff|token|email|document)=/i.test(action.href)),`${code} safe href`);
  }
  for(const metric of ['CUSTOMER_ERROR_DEAD_ENDS','REJECTION_STATES_WITHOUT_NEXT_ACTION','SUPPORT_PATH_MISSING'])console.log(`${metric} = 0`);
});
