import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import { ageBucket, ANALYTICS_SOURCE_MAP, buildHealth, completeHubRows, LAUNCH_FUNNEL, OWNER_ACTIVATION_ACTIONS, safeRate } from './launch-ops.ts';
import { applyCustomerMigrations, enableAppRole } from './migrate.ts';
import { AuthError, CustomerPlatform } from './store.ts';
import type { SqlClient } from './sql.ts';

test('canonical funnel separates behavioral context from durable truth',()=>{assert.equal(LAUNCH_FUNNEL[0].authoritative,false);assert.equal(LAUNCH_FUNNEL.find(x=>x.stage==='CLAIM_STARTED')?.authoritative,true);assert.equal(LAUNCH_FUNNEL.find(x=>x.stage==='OWNER_ACTIVATED')?.source,'audit_log');assert.doesNotMatch(JSON.stringify(LAUNCH_FUNNEL),/score|ranking/i)});
test('conversion denominators never produce NaN, infinity, or hidden rates',()=>{assert.deepEqual(safeRate(0,0),{numerator:0,denominator:0,percent:null});assert.deepEqual(safeRate(3,8),{numerator:3,denominator:8,percent:37.5})});
test('age buckets are neutral and deterministic',()=>{assert.deepEqual([0,24,96,192,360].map(ageBucket),['<24h','1–3d','4–7d','8–14d','15d+'])});
test('all six Hubs remain separate even in empty and small samples',()=>{const rows=completeHubRows([{hub:'contractor',started:1,approved:0,awaiting:1}]);assert.equal(rows.length,6);assert.equal(rows.find(x=>x.hub==='contractor')?.started,1);assert.equal(rows.find(x=>x.hub==='investor')?.started,0)});
test('health labels have explicit factual reasons and no arbitrary score',()=>{const health=buildHealth({awaitingReview:1,mailFailures24h:0,monitoringEligible:0});assert.equal(health.find(x=>x.label==='Review queue')?.status,'Needs attention');assert.equal(health.find(x=>x.label==='Monitoring')?.status,'Unavailable');assert.doesNotMatch(JSON.stringify(health),/score/i)});
test('activation excludes passive receipt and uses meaningful owner actions',()=>{assert.ok(OWNER_ACTIVATION_ACTIONS.includes('business_profile_updated'));assert.equal(OWNER_ACTIVATION_ACTIONS.some(x=>/email|viewed/.test(x)),false)});
test('analytics map labels behavioral events non-authoritative and exposes only bounded dimensions',()=>{assert.equal(ANALYTICS_SOURCE_MAP.filter(x=>x.source.includes('client')).every(x=>!x.authoritative),true);assert.doesNotMatch(JSON.stringify(ANALYTICS_SOURCE_MAP),/email address|credential|token|claim_id|profile_id|organization_id/i)});
test('operations route is dynamic, noindex, staff-only, bounded, and links existing queues',()=>{const page=readFileSync('app/internal/launch-ops/page.tsx','utf8'),store=readFileSync('lib/customer/store.ts','utf8');assert.match(page,/force-dynamic/);assert.match(page,/revalidate = 0/);assert.match(page,/noIndex:true/);assert.match(store.slice(store.indexOf('async launchOpsSnapshot')),/requireStaff\(sessionToken\)/);assert.match(store,/LIMIT 100/);assert.match(page,/internal\/review/);assert.match(page,/internal\/record-issues/);assert.match(page,/internal\/business-replies/);assert.doesNotMatch(page,/LifecycleQaOperator/)});
test('snapshot is one staff-authorized bounded aggregate read and normal customers are denied',async()=>{const db=new PGlite(),sql:SqlClient={async query(text,params){const result=await db.query(text,params??[]);return{rows:(result.rows??[]) as Record<string,unknown>[]}},async exec(text){await db.exec(text)}};await applyCustomerMigrations(sql);await db.query('BEGIN');await enableAppRole(sql);const platform=new CustomerPlatform({sql,cth:{async getById(){return null}},mailer:async m=>({sent:false,preview:m.text}),handoffSecret:'test-secret-that-is-long-enough-123',staffEmails:['staff@example.test'],siteUrl:'https://www.asktrusthub.com'});async function signup(email:string){const sent=await platform.requestMagicLink({email}),token=decodeURIComponent(sent.preview!.match(/token=([^&\s]+)/)![1]);return platform.consumeMagicLink(token)}const customer=await signup('customer@example.test'),staff=await signup('staff@example.test');await assert.rejects(()=>platform.launchOpsSnapshot(customer.sessionToken),(error:unknown)=>error instanceof AuthError&&error.code==='not_staff');const snapshot=await platform.launchOpsSnapshot(staff.sessionToken);assert.equal(snapshot.claims.length,0);assert.equal(snapshot.byHub.length,6);assert.equal(snapshot.summary.claims24h,0);assert.equal(JSON.stringify(snapshot).includes('customer@example.test'),false);await db.close()});
test('checked-in contract defines exact rate denominators and unknown attribution',()=>{const doc=readFileSync('docs/ath-launch-001d-funnel.md','utf8');assert.match(doc,/CTA clicks \/ eligible profile views/);assert.match(doc,/approved claims \/ started claims/);assert.match(doc,/missing attribution remains unknown/)});
