import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { applyCustomerMigrations,enableAppRole } from './migrate.ts';
import { CustomerPlatform,ManagementError } from './store.ts';
import { MonitoringError } from './monitoring.ts';
import type { SqlClient } from './sql.ts';

const PROFILE='11111111-1111-4111-8111-111111111111',SIBLING='22222222-2222-4222-8222-222222222222';
function asSql(db:PGlite):SqlClient{return{async query(text,params){const r=await db.query(text,params??[]);return{rows:(r.rows??[])as Record<string,unknown>[]}},async exec(sql){await db.exec(sql)}}}
async function signup(p:CustomerPlatform,email:string){const sent=await p.requestMagicLink({email}),token=decodeURIComponent(sent.preview!.match(/token=([^&\s]+)/)![1]);return p.consumeMagicLink(token)}
async function boot(sent=true){const db=new PGlite(),sql=asSql(db),mail:unknown[]=[];await applyCustomerMigrations(sql);await db.query('BEGIN');await enableAppRole(sql);let now=new Date('2026-08-31T12:00:00Z');const platform=new CustomerPlatform({sql,cth:{async getById(){return null}},mailer:async m=>{mail.push(m);return{sent,preview:m.text}},handoffSecret:'test-secret-that-is-long-enough-123',staffEmails:[],siteUrl:'https://www.asktrusthub.com',now:()=>now});return{db,sql,platform,mail,setNow:(v:string)=>{now=new Date(v)}}}
async function grant(sql:SqlClient,p:CustomerPlatform,role:'owner'|'manager'|'staff'|'billing'='owner'){const auth=await signup(p,`${role}@example.com`),org=(await sql.query<{id:string}>(`INSERT INTO ath_organizations(display_name,status)VALUES('Monitor org','active')RETURNING id`)).rows[0];await sql.query(`INSERT INTO ath_memberships(org_id,user_id,role,status)VALUES($1,$2,$3,'active')`,[org.id,auth.userId,role]);const hub=(await sql.query<{id:string}>(`INSERT INTO ath_hub_profiles(hub_id,native_profile_id,native_slug,native_credential_key,native_source_system,home_state,display_name_snapshot)VALUES('contractor',$1,'monitor-profile','CBC123','fl_dbpr','FL','Monitor Profile')RETURNING id`,[PROFILE])).rows[0],claim=(await sql.query<{id:string}>(`INSERT INTO ath_claims(org_id,hub_profile_id,claimant_user_id,status,verification_method,relationship_type,free_email)VALUES($1,$2,$3,'approved','manual_review','owner',false)RETURNING id`,[org.id,hub.id,auth.userId])).rows[0],g=(await sql.query<{id:string}>(`INSERT INTO ath_management_grants(org_id,hub_profile_id,status,granted_from_claim_id)VALUES($1,$2,'active',$3)RETURNING id`,[org.id,hub.id,claim.id])).rows[0];return{...auth,orgId:org.id,hubId:hub.id,grantId:g.id}}
function event(sequence='1',detected='2026-08-31T13:00:00Z'){return{sequence_id:sequence,id:'33333333-3333-4333-8333-333333333333',native_profile_id:PROFILE,source_system:'fl_dbpr',source_dataset:'construction_licensees',source_record_id:'CBC123',change_type:'LICENSE_STATUS_CHANGED',prior_state:{normalized:'ACTIVE'},current_state:{normalized:'INACTIVE'},source_effective_at:null,detected_at:detected,fingerprint_sha256:sequence.padStart(64,'a').slice(-64),provenance:{batch_id:'safe'}}}

test('explicit opt-in establishes baseline; later source event creates one private notification and delivery',async()=>{const{db,sql,platform,mail}=await boot(),owner=await grant(sql,platform);const enabled=await platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{enabled:true,emailEnabled:true,inAppEnabled:true,version:0}});assert.equal(enabled.version,1);assert.equal((await platform.ingestMonitoringEvents([event('1','2026-08-31T11:00:00Z')])).notifications,0,'historical event suppressed by baseline');const newer=await platform.ingestMonitoringEvents([event('2')]);assert.deepEqual({accepted:newer.accepted,notifications:newer.notifications},{accepted:1,notifications:1});assert.equal((await platform.ingestMonitoringEvents([event('2')])).accepted,0,'source and delivery dedupe');const view=await platform.monitoring(owner.sessionToken,PROFILE);assert.equal(view.notifications.length,1);await platform.markMonitoringNotificationRead({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,notificationId:String(view.notifications[0].id)});assert.equal((await platform.monitoring(owner.sessionToken,PROFILE)).notifications[0].read_at!==null,true);assert.deepEqual(await platform.deliverMonitoringEmails(),{sent:1,failed:0});const alerts=(mail as Array<{subject?:string}>).filter(m=>m.subject?.startsWith('Official record change'));assert.equal(alerts.length,1);assert.doesNotMatch(JSON.stringify(alerts),/prior_state|previous:/i,'email uses concise summary rather than raw payload dump');assert.equal((await sql.query(`SELECT count(*)::text n FROM ath_audit_events WHERE action IN('monitoring_enabled','regulatory_change_detected','regulatory_notification_created','regulatory_notification_read','regulatory_email_sent')`)).rows[0].n,'6');await db.close()});

test('exact-profile authorization, billing, revocation and guessed notification fail closed',async()=>{const{db,sql,platform}=await boot(),owner=await grant(sql,platform);await assert.rejects(()=>platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:SIBLING,body:{enabled:true,emailEnabled:false,inAppEnabled:true,version:0}}),ManagementError);await sql.query(`UPDATE ath_memberships SET role='billing' WHERE org_id=$1`,[owner.orgId]);await assert.rejects(()=>platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{enabled:true,emailEnabled:false,inAppEnabled:true,version:0}}),ManagementError);await sql.query(`UPDATE ath_memberships SET role='owner' WHERE org_id=$1`,[owner.orgId]);await platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{enabled:true,emailEnabled:true,inAppEnabled:true,version:0}});await platform.ingestMonitoringEvents([event()]);await assert.rejects(()=>platform.markMonitoringNotificationRead({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,notificationId:'44444444-4444-4444-8444-444444444444'}),MonitoringError);await sql.query(`UPDATE ath_management_grants SET status='revoked' WHERE id=$1`,[owner.grantId]);await assert.rejects(()=>platform.monitoring(owner.sessionToken,PROFILE),ManagementError);assert.deepEqual(await platform.deliverMonitoringEmails(),{sent:0,failed:0},'revocation stops future delivery');await db.close()});

test('channel validation, optimistic concurrency, forced RLS and regulatory firewall',async()=>{const{db,sql,platform}=await boot(),owner=await grant(sql,platform);await assert.rejects(()=>platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{enabled:true,emailEnabled:false,inAppEnabled:false,version:0}}),MonitoringError);await platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{enabled:true,emailEnabled:false,inAppEnabled:true,version:0}});await assert.rejects(()=>platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{enabled:false,emailEnabled:false,inAppEnabled:true,version:0}}),(e:unknown)=>e instanceof MonitoringError&&e.code==='stale_version');const rows=await sql.query<{relname:string;relrowsecurity:boolean;relforcerowsecurity:boolean}>(`SELECT relname,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname IN('ath_monitoring_subscriptions','ath_regulatory_change_events','ath_notifications','ath_notification_deliveries','ath_monitoring_sync_cursors')`);assert.equal(rows.rows.length,5);for(const r of rows.rows){assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true)}const migration=readFileSync('schema/migrations/005_ath_regulatory_monitoring.sql','utf8');assert.doesNotMatch(migration,/\b(?:INSERT INTO|UPDATE|DELETE FROM)\s+(?:contractors|licenses|discipline_actions|regulatory_source_observations|ath_entitlements)\b/i);await db.close()});

test('email failure leaves durable event and bounded retry state',async()=>{const{db,sql,platform}=await boot(false),owner=await grant(sql,platform);await platform.saveMonitoring({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{enabled:true,emailEnabled:true,inAppEnabled:true,version:0}});await platform.ingestMonitoringEvents([event()]);assert.deepEqual(await platform.deliverMonitoringEmails(),{sent:0,failed:1});assert.equal((await sql.query(`SELECT status,attempts FROM ath_notification_deliveries`)).rows[0].status,'FAILED');assert.equal((await sql.query(`SELECT count(*)::text n FROM ath_notifications WHERE event_key='regulatory_change'`)).rows[0].n,'1');await db.close()});
