import test from 'node:test';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { applyCustomerMigrations,enableAppRole } from './migrate.ts';
import { CustomerPlatform,ManagementError } from './store.ts';
import { OrganizationError } from './organization.ts';
import type { SqlClient } from './sql.ts';

const PROFILE_A='11111111-1111-4111-8111-111111111111',PROFILE_B='22222222-2222-4222-8222-222222222222';
function asSql(db:PGlite):SqlClient{return{async query(text,params){const result=await db.query(text,params??[]);return{rows:(result.rows??[])as Record<string,unknown>[]}},async exec(sql){await db.exec(sql)}}}
async function boot(mailSent=true){const db=new PGlite(),sql=asSql(db),mail:Array<{to:string;text:string;subject:string}>=[];await applyCustomerMigrations(sql);await db.query('BEGIN');await enableAppRole(sql);let now=new Date('2026-08-31T12:00:00Z');const platform=new CustomerPlatform({sql,cth:{async getById(){return null}},mailer:async message=>{mail.push(message as never);return{sent:mailSent,preview:message.text}},handoffSecret:'test-secret-that-is-long-enough-123',staffEmails:[],siteUrl:'https://www.asktrusthub.com',now:()=>now});return{db,sql,platform,mail,setNow:(value:string)=>{now=new Date(value)}}}
async function signup(platform:CustomerPlatform,email:string){const sent=await platform.requestMagicLink({email,nextPath:'/manage'}),token=decodeURIComponent(sent.preview!.match(/token=([^&\s]+)/)![1]);return platform.consumeMagicLink(token)}
async function orgWithProfiles(sql:SqlClient,platform:CustomerPlatform,count=1){const owner=await signup(platform,'owner@example.com'),org=(await sql.query<{id:string}>(`INSERT INTO ath_organizations(display_name,status)VALUES('One business','active')RETURNING id`)).rows[0],membership=(await sql.query<{id:string}>(`INSERT INTO ath_memberships(org_id,user_id,role,status)VALUES($1,$2,'owner','active')RETURNING id`,[org.id,owner.userId])).rows[0];for(const [index,profile] of [PROFILE_A,PROFILE_B].slice(0,count).entries()){const hub=(await sql.query<{id:string}>(`INSERT INTO ath_hub_profiles(hub_id,native_profile_id,native_slug,native_credential_key,native_source_system,home_state,display_name_snapshot)VALUES('contractor',$1,$2,$3,'fl_dbpr','FL',$4)RETURNING id`,[profile,`profile-${index}`,`CBC${index}`,`Profile ${index}`])).rows[0],claim=(await sql.query<{id:string}>(`INSERT INTO ath_claims(org_id,hub_profile_id,claimant_user_id,status,verification_method,relationship_type,free_email)VALUES($1,$2,$3,'approved','manual_review','owner',false)RETURNING id`,[org.id,hub.id,owner.userId])).rows[0];await sql.query(`INSERT INTO ath_management_grants(org_id,hub_profile_id,status,granted_from_claim_id)VALUES($1,$2,'active',$3)`,[org.id,hub.id,claim.id]);}return{owner,orgId:org.id,ownerMembershipId:membership.id}}
function inviteToken(mail:Array<{text:string}>){return decodeURIComponent(mail.at(-1)!.text.match(/token=([^&\s]+)/)![1])}

test('owner invitation supports new user, exact email, single use, audit and multi-profile inheritance',async()=>{const{db,sql,platform,mail}=await boot(),seed=await orgWithProfiles(sql,platform,2);const created=await platform.createOrganizationInvitation({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,body:{email:'New.Member@Example.com',role:'manager'}});assert.equal(created.status,'PENDING');assert.doesNotMatch(JSON.stringify(await sql.query(`SELECT * FROM ath_organization_invitations`)),/token=/);const token=inviteToken(mail),invitee=await signup(platform,'new.member@example.com'),accepted=await platform.acceptOrganizationInvitation({sessionToken:invitee.sessionToken,token});assert.equal(accepted.role,'manager');assert.equal((await platform.managedHome(invitee.sessionToken)).length,2,'one organization grants both exact profiles without duplicate user/org/grant');await assert.rejects(()=>platform.acceptOrganizationInvitation({sessionToken:invitee.sessionToken,token}),(error:unknown)=>error instanceof OrganizationError&&error.code==='consumed_invitation');assert.equal((await sql.query(`SELECT count(*)::text n FROM ath_audit_events WHERE action IN('organization_invite_created','organization_invite_accepted')`)).rows[0].n,'2');await db.close()});

test('tamper, mismatch, expiry, revoke, duplicate and role escalation fail closed',async()=>{const{db,sql,platform,mail,setNow}=await boot(),seed=await orgWithProfiles(sql,platform);await platform.createOrganizationInvitation({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,body:{email:'invitee@example.com',role:'staff'}});const token=inviteToken(mail),wrong=await signup(platform,'wrong@example.com');await assert.rejects(()=>platform.acceptOrganizationInvitation({sessionToken:wrong.sessionToken,token}),(error:unknown)=>error instanceof OrganizationError&&error.code==='email_mismatch');await assert.rejects(()=>platform.invitationPreview(`${token}x`),OrganizationError);await assert.rejects(()=>platform.createOrganizationInvitation({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,body:{email:'invitee@example.com',role:'owner'}}),OrganizationError);await assert.rejects(()=>platform.createOrganizationInvitation({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,body:{email:'invitee@example.com',role:'staff'}}),(error:unknown)=>error instanceof OrganizationError&&error.code==='duplicate_invitation');const row=(await sql.query<{id:string;version:number}>(`SELECT id,version FROM ath_organization_invitations WHERE org_id=$1`,[seed.orgId])).rows[0];await platform.revokeOrganizationInvitation({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,invitationId:row.id,version:row.version});const invitee=await signup(platform,'invitee@example.com');await assert.rejects(()=>platform.acceptOrganizationInvitation({sessionToken:invitee.sessionToken,token}),(error:unknown)=>error instanceof OrganizationError&&error.code==='revoked_invitation');await platform.createOrganizationInvitation({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,body:{email:'expired@example.com',role:'staff'}});const expiredToken=inviteToken(mail);setNow('2026-09-08T12:00:01Z');const expired=await signup(platform,'expired@example.com');await assert.rejects(()=>platform.acceptOrganizationInvitation({sessionToken:expired.sessionToken,token:expiredToken}),(error:unknown)=>error instanceof OrganizationError&&error.code==='expired_invitation');await db.close()});

test('only owners administer; last owner protected; removal immediately removes all profile authority',async()=>{const{db,sql,platform,mail}=await boot(),seed=await orgWithProfiles(sql,platform,2);await platform.createOrganizationInvitation({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,body:{email:'manager@example.com',role:'manager'}});const token=inviteToken(mail),manager=await signup(platform,'manager@example.com');const accepted=await platform.acceptOrganizationInvitation({sessionToken:manager.sessionToken,token});await assert.rejects(()=>platform.createOrganizationInvitation({sessionToken:manager.sessionToken,orgId:seed.orgId,body:{email:'staff@example.com',role:'staff'}}),(error:unknown)=>error instanceof OrganizationError&&error.code==='forbidden');await assert.rejects(()=>platform.changeOrganizationMemberRole({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,membershipId:seed.ownerMembershipId,role:'manager'}),(error:unknown)=>error instanceof OrganizationError&&error.code==='last_owner');await platform.changeOrganizationMemberRole({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,membershipId:accepted.membershipId,role:'staff'});assert.equal((await platform.organizationConsole(manager.sessionToken,seed.orgId)).currentRole,'staff');await platform.removeOrganizationMember({sessionToken:seed.owner.sessionToken,orgId:seed.orgId,membershipId:accepted.membershipId});await assert.rejects(()=>platform.organizationConsole(manager.sessionToken,seed.orgId),OrganizationError);await assert.rejects(()=>platform.businessProfile(manager.sessionToken,PROFILE_A),ManagementError);assert.equal((await sql.query(`SELECT count(*)::text n FROM ath_management_grants WHERE org_id=$1 AND status='active'`,[seed.orgId])).rows[0].n,'2','member removal never mutates organization grants');await db.close()});

test('cross-org guesses, inactive org, email failure durability and forced RLS',async()=>{const{db,sql,platform}=await boot(false),first=await orgWithProfiles(sql,platform),secondOwner=await signup(platform,'second@example.com'),second=(await sql.query<{id:string}>(`INSERT INTO ath_organizations(display_name,status)VALUES('Second','active')RETURNING id`)).rows[0];await sql.query(`INSERT INTO ath_memberships(org_id,user_id,role,status)VALUES($1,$2,'owner','active')`,[second.id,secondOwner.userId]);await assert.rejects(()=>platform.organizationConsole(first.owner.sessionToken,second.id),OrganizationError);const invite=await platform.createOrganizationInvitation({sessionToken:first.owner.sessionToken,orgId:first.orgId,body:{email:'durable@example.com',role:'staff'}});assert.equal(invite.emailSent,false);assert.equal((await sql.query(`SELECT status FROM ath_organization_invitations WHERE id=$1`,[invite.id])).rows[0].status,'PENDING');await sql.query(`UPDATE ath_organizations SET status='suspended' WHERE id=$1`,[first.orgId]);await assert.rejects(()=>platform.organizationConsole(first.owner.sessionToken,first.orgId),OrganizationError);const security=await sql.query<{relrowsecurity:boolean;relforcerowsecurity:boolean}>(`SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname='ath_organization_invitations'`);assert.deepEqual(security.rows,[{relrowsecurity:true,relforcerowsecurity:true}]);await db.close()});
