import assert from 'node:assert/strict';import { test } from 'node:test';import { PGlite } from '@electric-sql/pglite';import { readFileSync } from 'node:fs';import { applyCustomerMigrations,enableAppRole } from './migrate.ts';import { CustomerPlatform,ManagementError } from './store.ts';import { RecordIssueError,validateRecordIssue } from './record-issues.ts';import type { SqlClient } from './sql.ts';
const PROFILE='11111111-1111-4111-8111-111111111111',SIBLING='22222222-2222-4222-8222-222222222222';
function asSql(db:PGlite):SqlClient{return{async query(text,params){const r=await db.query(text,params??[]);return{rows:(r.rows??[]) as Record<string,unknown>[]}},async exec(sql){await db.exec(sql)}}}
async function signup(p:CustomerPlatform,email:string){const sent=await p.requestMagicLink({email});const token=decodeURIComponent(sent.preview!.match(/token=([^&\s]+)/)![1]);return p.consumeMagicLink(token)}
async function boot(){const db=new PGlite(),sql=asSql(db),mail:unknown[]=[];await applyCustomerMigrations(sql);await db.query('BEGIN');await enableAppRole(sql);const platform=new CustomerPlatform({sql,cth:{async getById(){return null}},mailer:async m=>{mail.push(m);return{sent:false,preview:m.text}},handoffSecret:'test-secret-that-is-long-enough-123',staffEmails:['reviewer@example.com'],siteUrl:'https://www.asktrusthub.com'});return{db,sql,platform,mail}}
async function grant(sql:SqlClient,p:CustomerPlatform,email='owner@example.com',role:'owner'|'manager'|'staff'|'billing'='owner',profile=PROFILE){const auth=await signup(p,email);const org=(await sql.query<{id:string}>(`INSERT INTO ath_organizations(display_name,status) VALUES('Issue org','active') RETURNING id`)).rows[0];await sql.query(`INSERT INTO ath_memberships(org_id,user_id,role,status) VALUES($1,$2,$3,'active')`,[org.id,auth.userId,role]);const hub=(await sql.query<{id:string}>(`INSERT INTO ath_hub_profiles(hub_id,native_profile_id,native_slug,native_credential_key,native_source_system,home_state,display_name_snapshot) VALUES('contractor',$1,'issue-profile','CBC123','fl_dbpr','FL','Issue Profile') RETURNING id`,[profile])).rows[0];const claim=(await sql.query<{id:string}>(`INSERT INTO ath_claims(org_id,hub_profile_id,claimant_user_id,status,verification_method,relationship_type,free_email) VALUES($1,$2,$3,'approved','manual_review','owner',false) RETURNING id`,[org.id,hub.id,auth.userId])).rows[0];const g=(await sql.query<{id:string}>(`INSERT INTO ath_management_grants(org_id,hub_profile_id,status,granted_from_claim_id) VALUES($1,$2,'active',$3) RETURNING id`,[org.id,hub.id,claim.id])).rows[0];return{...auth,orgId:org.id,hubId:hub.id,grantId:g.id}}
const valid={issueType:'OTHER_RECORD_ISSUE',targetRecordType:'PROFILE',explanation:'Controlled workflow test with no factual correction requested.'};

test('taxonomy and target validation are constrained',()=>{assert.equal(validateRecordIssue(valid).targetLayer,'AUTHORITATIVE_EVIDENCE');for(const input of [{...valid,issueType:'FREEFORM'},{...valid,targetRecordType:'SQL_TABLE'},{...valid,explanation:'short'},{...valid,explanation:'<script>alert(1)</script>'},{issueType:'WRONG_DISCIPLINE_LINK',targetRecordType:'DISCIPLINE_EVENT',explanation:valid.explanation}])assert.throws(()=>validateRecordIssue(input),RecordIssueError)});

test('authorized exact-profile manager creates Layer D issue, queue, audit and notification',async()=>{const{db,sql,platform,mail}=await boot();const owner=await grant(sql,platform);const created=await platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:valid});assert.equal(created.status,'OPEN');const view=await platform.recordIssues(owner.sessionToken,PROFILE);assert.equal(view.issues.length,1);assert.equal((view.issues[0] as Record<string,unknown>).internal_resolution_note,undefined);assert.equal((await sql.query(`SELECT count(*)::text n FROM ath_review_queue WHERE work_type='record_issue'`)).rows[0].n,'1');assert.equal((await sql.query(`SELECT count(*)::text n FROM ath_audit_events WHERE action='record_issue_created'`)).rows[0].n,'1');assert.match(JSON.stringify(mail.at(-1)),/received your record issue/i);await assert.rejects(()=>platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:valid}),(e:unknown)=>e instanceof RecordIssueError&&e.code==='duplicate');await db.close()});

test('cross-org, sibling, billing, revoked grant and inactive membership deny submission and reads',async()=>{const{db,sql,platform}=await boot();const owner=await grant(sql,platform);const stranger=await signup(platform,'stranger@example.com');await assert.rejects(()=>platform.createRecordIssue({sessionToken:stranger.sessionToken,nativeProfileId:PROFILE,body:valid}),ManagementError);await assert.rejects(()=>platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:SIBLING,body:valid}),ManagementError);await sql.query(`UPDATE ath_memberships SET role='billing' WHERE org_id=$1`,[owner.orgId]);await assert.rejects(()=>platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:valid}),ManagementError);await sql.query(`UPDATE ath_memberships SET role='owner' WHERE org_id=$1`,[owner.orgId]);await sql.query(`UPDATE ath_management_grants SET status='revoked' WHERE id=$1`,[owner.grantId]);await assert.rejects(()=>platform.recordIssues(owner.sessionToken,PROFILE),ManagementError);await sql.query(`UPDATE ath_management_grants SET status='active' WHERE id=$1`,[owner.grantId]);await sql.query(`UPDATE ath_memberships SET status='revoked' WHERE org_id=$1`,[owner.orgId]);await assert.rejects(()=>platform.recordIssues(owner.sessionToken,PROFILE),ManagementError);await db.close()});

test('staff transitions are versioned, internal notes stay private, and corrected is remediation-only',async()=>{const{db,sql,platform}=await boot();const owner=await grant(sql,platform);const staff=await signup(platform,'reviewer@example.com');const created=await platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:valid});let result=await platform.staffTransitionRecordIssue({sessionToken:staff.sessionToken,issueId:created.id,nextStatus:'UNDER_REVIEW',version:1});assert.equal(result.version,2);await assert.rejects(()=>platform.staffTransitionRecordIssue({sessionToken:staff.sessionToken,issueId:created.id,nextStatus:'RESOLVED_NO_CHANGE',version:1,customerNote:'No change supported.'}),(e:unknown)=>e instanceof RecordIssueError&&e.code==='stale_version');result=await platform.staffTransitionRecordIssue({sessionToken:staff.sessionToken,issueId:created.id,nextStatus:'NEEDS_INFORMATION',version:2,customerNote:'Please provide the official source identifier.',internalNote:'Private reviewer context only.'});assert.equal(result.version,3);let customer=await platform.recordIssues(owner.sessionToken,PROFILE);assert.doesNotMatch(JSON.stringify(customer),/Private reviewer/);const response=await platform.customerRecordIssueAction({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,issueId:created.id,action:'respond',version:3,message:'The relevant source reference is DBPR CBC123.'});assert.equal(response.status,'OPEN');await platform.staffTransitionRecordIssue({sessionToken:staff.sessionToken,issueId:created.id,nextStatus:'RESOLVED_CORRECTED',version:4,customerNote:'Reviewed and queued for authoritative-source reconciliation.',internalNote:'Use the normal ingest process; no manual evidence edit.'});customer=await platform.recordIssues(owner.sessionToken,PROFILE);assert.equal((customer.issues[0] as Record<string,unknown>).status,'RESOLVED_CORRECTED');assert.equal((await sql.query(`SELECT count(*)::text n FROM ath_record_issue_remediation_tasks WHERE issue_id=$1 AND status='OPEN'`,[created.id])).rows[0].n,'1');const migration=readFileSync('schema/migrations/003_ath_record_issues.sql','utf8');assert.doesNotMatch(migration,/\b(?:UPDATE|INSERT INTO|DELETE FROM)\s+(?:contractors|licenses|discipline_actions|regulatory_source_observations)\b/i);await db.close()});

test('customer can withdraw only OPEN issue; guessed issue UUID and stale version fail',async()=>{const{db,sql,platform}=await boot();const owner=await grant(sql,platform);const created=await platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:valid});await assert.rejects(()=>platform.customerRecordIssueAction({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,issueId:'33333333-3333-4333-8333-333333333333',action:'withdraw',version:1}),(e:unknown)=>e instanceof RecordIssueError&&e.code==='not_found');const withdrawn=await platform.customerRecordIssueAction({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,issueId:created.id,action:'withdraw',version:1});assert.equal(withdrawn.status,'WITHDRAWN');await assert.rejects(()=>platform.customerRecordIssueAction({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,issueId:created.id,action:'withdraw',version:1}),RecordIssueError);await db.close()});

test('submission rate limit and exact credential targeting fail closed',async()=>{const{db,sql,platform}=await boot();const owner=await grant(sql,platform);await assert.rejects(()=>platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{issueType:'WRONG_LICENSE',targetRecordType:'DBPR_CREDENTIAL',targetRecordId:'OTHER123',explanation:'This points to a different credential than the granted profile.'}}),(e:unknown)=>e instanceof RecordIssueError&&e.code==='validation_failed');for(let i=0;i<5;i++)await platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{...valid,explanation:`Controlled distinct issue number ${i} for submission limiting.`}});await assert.rejects(()=>platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:{...valid,explanation:'Controlled sixth distinct issue for submission limiting.'}}),(e:unknown)=>e instanceof RecordIssueError&&e.code==='rate_limited');await db.close()});

test('record issue tables use forced RLS and event history is append-only',async()=>{const{db,sql,platform}=await boot();const owner=await grant(sql,platform);const issue=await platform.createRecordIssue({sessionToken:owner.sessionToken,nativeProfileId:PROFILE,body:valid});const rows=await sql.query<{relname:string;relrowsecurity:boolean;relforcerowsecurity:boolean}>(`SELECT relname,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname IN ('ath_record_issues','ath_record_issue_events','ath_record_issue_remediation_tasks')`);assert.equal(rows.rows.length,3);for(const r of rows.rows){assert.equal(r.relrowsecurity,true);assert.equal(r.relforcerowsecurity,true)}await assert.rejects(()=>sql.query(`UPDATE ath_record_issue_events SET message='mutated' WHERE issue_id=$1`,[issue.id]));await assert.rejects(()=>sql.query(`DELETE FROM ath_record_issue_events WHERE issue_id=$1`,[issue.id]));await db.close()});
