"""ATH-CA-001 — emit isolated California network JSON (no public routes)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / "data" / "network" / "california"
CHECKED = "2026-09-03"
TICKET = "ATH-CA-001"

HUBS = ["ASK", "CONTRACTOR", "LENDER", "INSURANCE", "SENIOR", "MOVE", "INVESTOR"]


def hv(**kwargs) -> dict:
    out = {h: "NONE" for h in HUBS}
    out.update(kwargs)
    return out


def scores(**kwargs) -> dict:
    base = {
        "IDENTITY_VALUE": "NONE",
        "CONTACT_VALUE": "NONE",
        "REGULATORY_VALUE": "NONE",
        "MARKET_INTELLIGENCE_VALUE": "NONE",
        "ACQUISITION_EASE": "NONE",
    }
    base.update(kwargs)
    return base


SOURCES = [
    {
        "source_id": "ca-cslb-master-list",
        "hub_home": "CONTRACTOR",
        "source_family": "license_roster",
        "source_name": "CSLB Public Data Portal — License Master",
        "regulator": "Contractors State License Board (Department of Consumer Affairs)",
        "source_url": "https://www.cslb.ca.gov/onlineservices/dataportal/ContractorList",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "CSLB license number",
        "source_as_of": "2026-09-02",
        "last_checked": CHECKED,
        "grain": "contractor license",
        "record_count": "UNKNOWN",
        "active_count": "UNKNOWN",
        "count_notes": "Free file covers currently renewed OR expired-but-renewable licenses. Cancelled, revoked, and expired-non-renewable are omitted. Portal label: Updated as of 9/2/2026. This ticket's CSV postback transferred 27,890,218 bytes then dropped (IncompleteRead). Do not treat homepage snapshots as file row counts.",
        "identifier_fields": ["license number"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": False, "count": 0, "note": "BPC 27 — emails are not provided"},
            "WEBSITE": {"present": False, "count": 0, "note": "not in official field list"},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN", "note": "portal describes address; mailing vs physical not split in the public description"},
        },
        "other_fields": ["business name", "license status", "issue date", "expiration date", "classification(s)", "bond information", "workers compensation information"],
        "terms_notes": "No charge. Disclaimer: current as of the date under the download link. Verify current status via Instant License Check. CA.gov Conditions of Use + DCA privacy policy.",
        "redistribution_notes": "Do not commit the full master CSV. Do not treat missing cancelled/revoked rows as zero discipline.",
        "hub_value": hv(ASK="HIGH", CONTRACTOR="HIGH", LENDER="LOW", INSURANCE="LOW", SENIOR="LOW", MOVE="LOW", INVESTOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="HIGH", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "PORTAL_LIVE_TRANSFER_INCOMPLETE",
        "blocker": "ASP.NET postback to ctl00$MainContent$lbMasterCSV started a file (>=27.8MB) then the HTTP body truncated. Not a CAPTCHA. Retry with streaming next ticket.",
        "recommended_next_action": "Stream the official CSV/XLS postback to data/raw (gitignored). Profile phone occupancy. Commit header+3-row fixture only.",
    },
    {
        "source_id": "ca-cslb-personnel",
        "hub_home": "CONTRACTOR",
        "source_family": "license_personnel",
        "source_name": "CSLB Public Data Portal — Personnel",
        "regulator": "Contractors State License Board",
        "source_url": "https://www.cslb.ca.gov/onlineservices/dataportal/ContractorList",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "CSLB license number + currently associated personnel name/title",
        "source_as_of": "2026-09-02",
        "last_checked": CHECKED,
        "grain": "person currently associated with a license",
        "record_count": "UNKNOWN",
        "active_count": "UNKNOWN",
        "identifier_fields": ["license number", "personnel name", "title"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0, "note": "BPC 27"},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "other_fields": ["classification(s)", "bond information"],
        "terms_notes": "Disassociated personnel are not included in the free file.",
        "redistribution_notes": "Personnel names are official license associations, not a consumer contact list. Do not infer personal phone/email.",
        "hub_value": hv(ASK="MEDIUM", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="LOW", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "PORTAL_LIVE_NOT_DOWNLOADED",
        "blocker": "Master CSV transfer failed first; personnel download not attempted.",
        "recommended_next_action": "Download after master succeeds. Join on license number only.",
    },
    {
        "source_id": "ca-cslb-workers-comp",
        "hub_home": "CONTRACTOR",
        "source_family": "insurance_coverage",
        "source_name": "CSLB Public Data Portal — Workers Compensation",
        "regulator": "Contractors State License Board",
        "source_url": "https://www.cslb.ca.gov/onlineservices/dataportal/ContractorList",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "CSLB license number",
        "source_as_of": "2026-09-02",
        "last_checked": CHECKED,
        "grain": "workers compensation policy row for a license",
        "record_count": "UNKNOWN",
        "identifier_fields": ["license number", "policy number"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "other_fields": ["coverage type", "workers comp company", "policy dates"],
        "hub_value": hv(ASK="MEDIUM", CONTRACTOR="HIGH", INSURANCE="LOW"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="NONE", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "PORTAL_LIVE_NOT_DOWNLOADED",
        "recommended_next_action": "Download with master. Missing WC != uninsured without Instant Check.",
    },
    {
        "source_id": "ca-cslb-classifications",
        "hub_home": "CONTRACTOR",
        "source_family": "classification_taxonomy",
        "source_name": "CSLB Licensing Classifications",
        "regulator": "Contractors State License Board",
        "source_url": "https://www.cslb.ca.gov/About_Us/Library/Licensing_Classifications/",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "license classification code",
        "record_count": 46,
        "count_notes": "Official page lists A, B, B-2, and 43 C-codes (C-2 through C-61 as published), plus ASB and HAZ certifications. C-61 Limited Specialty has additional D-subclasses not enumerated here.",
        "identifier_fields": ["classification code"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="HIGH", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="NONE", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "INVENTORIED",
        "recommended_next_action": "Use as taxonomy. Do not scrape every D-subclass page this ticket.",
    },
    {
        "source_id": "ca-cslb-instant-license-check",
        "hub_home": "CONTRACTOR",
        "source_family": "license_lookup",
        "source_name": "CSLB Instant License Check",
        "regulator": "Contractors State License Board",
        "source_url": "https://www.cslb.ca.gov/OnlineServices/CheckLicenseII/CheckLicense.aspx",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "single license lookup",
        "record_count": "UNKNOWN",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": False, "count": 0, "note": "BPC 27"},
            "WEBSITE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "terms_notes": "Portal page matched a captcha token in HTML. Do not scrape. Current-status source of record for a single license.",
        "hub_value": hv(ASK="HIGH", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="LOW"),
        "acquisition_status": "DOCUMENTED_NO_SCRAPE",
        "blocker": "Interactive lookup. Possible CAPTCHA. Not a bulk API.",
        "recommended_next_action": "Keep as consumer verify link. Do not automate.",
    },
    {
        "source_id": "ca-cslb-full-file-paid",
        "hub_home": "CONTRACTOR",
        "source_family": "license_roster",
        "source_name": "CSLB License Master Full File / Update File",
        "regulator": "Contractors State License Board — Data Services Unit",
        "source_url": "https://www.cslb.ca.gov/about_us/library/forms_and_applications.aspx",
        "access_class": "SOURCE_AVAILABLE_BY_REQUEST",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "contractor license including cancelled/revoked/expired 10+ years",
        "record_count": "830000+",
        "count_notes": "Official forms page: FULL file provides 830,000+ records. Fee $235 non-refundable per file. Text file, not Excel. Personnel is a separate 1.3+ million Business Principle Full File. Emails are not included.",
        "identifier_fields": ["LICENSE NUMBER"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(ASK="MEDIUM", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="HIGH", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="LOW"),
        "acquisition_status": "REQUEST_DRAFTED_NOT_SUBMITTED",
        "recommended_next_action": "Do not wait. Free master is the first universe. Draft is in docs/california/requests/cslb-full-file.md.",
    },
    {
        "source_id": "ca-cslb-public-sales-custom",
        "hub_home": "CONTRACTOR",
        "source_family": "license_roster",
        "source_name": "CSLB Public Sales Custom Order",
        "regulator": "Contractors State License Board — Data Services Unit",
        "source_url": "https://www.cslb.ca.gov/Resources/FormsAndApplications/publicsalesorderformlabelslistscd.pdf",
        "access_class": "SOURCE_AVAILABLE_BY_REQUEST",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": "2026-06",
        "last_checked": CHECKED,
        "grain": "filtered currently renewed licenses",
        "record_count": "UNKNOWN",
        "count_notes": "Fee $245. Currently renewed only. No expired/cancelled/revoked. No personnel. No email. Form Rev. 06/2026.",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(CONTRACTOR="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="HIGH", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "SKIP_FREE_PORTAL_FIRST",
        "recommended_next_action": "Skip unless a filtered extract is needed after the free master lands.",
    },
    {
        "source_id": "ca-cslb-soap-api",
        "hub_home": "CONTRACTOR",
        "source_family": "license_api",
        "source_name": "CSLB Data Portal SOAP GetbyClassification",
        "regulator": "Contractors State License Board",
        "source_url": "https://www.cslb.ca.gov/onlineservices/DataPortalAPI/GetbyClassification.asmx?WSDL",
        "access_class": "FREE_ACCOUNT_REQUIRED",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "classification extract",
        "record_count": "UNKNOWN",
        "count_notes": "WSDL live. Empty-token GetDataByClassification(C-10) returned HTTP 200 with errorMessage Missing Classification or Token. Not an open anonymous API.",
        "hub_value": hv(CONTRACTOR="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "TOKEN_REQUIRED",
        "blocker": "Token required. Do not claim OPEN_API.",
        "recommended_next_action": "Prefer the free master CSV. Do not guess tokens.",
    },
    {
        "source_id": "ca-cslb-enforcement-report",
        "hub_home": "CONTRACTOR",
        "source_family": "enforcement_aggregate",
        "source_name": "CSLB FY 2024-25 Enforcement Report",
        "regulator": "Contractors State License Board",
        "source_url": "https://www.cslb.ca.gov/Resources/Reports/Enforcement/CSLB_FY_2024-25_Enforcement_Report.pdf",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "UNSAFE",
        "source_as_of": "2025-09-15",
        "last_checked": CHECKED,
        "grain": "fiscal-year aggregate",
        "record_count": "UNKNOWN",
        "count_notes": "Report totals are not a license roster. FY 2024/25: 19,257 complaints received; 591 licenses revoked; 455 licenses suspended (report figures). Complaint != violation. Accusation != finding.",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="MEDIUM", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="NONE", CONTACT_VALUE="NONE", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "AGGREGATE_ONLY",
        "recommended_next_action": "Publish as coverage evidence. Never auto-attach to a profile from this PDF.",
    },
    {
        "source_id": "ca-cslb-revoked-licenses",
        "hub_home": "CONTRACTOR",
        "source_family": "enforcement",
        "source_name": "CSLB revoked licenses listing",
        "regulator": "Contractors State License Board",
        "source_url": "https://www.cslb.ca.gov/RevokedLicenses",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "revoked license row",
        "record_count": "UNKNOWN",
        "count_notes": "Summer 2026 newsletter points consumers to cslb.ca.gov/RevokedLicenses. Disciplinary_Actions.aspx returned a Page Not Found title on 2026-09-03. Instant License Check remains the per-license disclosure path. Do not scrape.",
        "hub_value": hv(ASK="MEDIUM", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="NONE", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "DOCUMENTED_NO_SCRAPE",
        "recommended_next_action": "Confirm page shape next contractor ticket. Join only on license number.",
    },
    {
        "source_id": "ca-dir-pwcr",
        "hub_home": "CONTRACTOR",
        "source_family": "public_works_registration",
        "source_name": "DIR Public Works Contractor Registration (PWCR)",
        "regulator": "California Department of Industrial Relations",
        "source_url": "https://www.dir.ca.gov/public-works/contractor-registration.html",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "PWCR number",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "public works contractor registration",
        "record_count": "UNKNOWN",
        "count_notes": "No bulk CSV on data.ca.gov. Legacy Salesforce search cadir.my.salesforce-sites.com/ContractorSearch returned HTTP 503 this ticket. services.dir.ca.gov/pw returned HTTP 200 (LETF Dashboard / Public Works Portal HTML). Local debarment downloads may require captcha for public users. PWCR != CSLB license.",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(ASK="MEDIUM", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="LOW", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "SEARCH_PORTAL_NO_BULK",
        "blocker": "No documented public bulk roster. Do not scrape. Do not captcha-bypass local debarment Excel.",
        "recommended_next_action": "Keep as search capability. Do not wait on PRA.",
    },
    {
        "source_id": "ca-dir-dlse-debarment",
        "hub_home": "CONTRACTOR",
        "source_family": "debarment",
        "source_name": "DIR DLSE Public Works Debarments",
        "regulator": "Labor Commissioner's Office (DLSE), Department of Industrial Relations",
        "source_url": "https://www.dir.ca.gov/dlse/debar.html",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "CSLB license number when stated",
        "source_as_of": "2025-07",
        "last_checked": CHECKED,
        "grain": "debarment order / contractor-person grouping",
        "record_count": "UNKNOWN",
        "count_notes": "HTML table live (page dated July 2025 in footer). Parser saw 67 period strings and 62 table data rows. Two-digit years such as 4/1/44 are ambiguous, so currently-in-force count is UNKNOWN. Distinct from DIR local debarment list. Federal EPLS/SAM is a separate list.",
        "identifier_fields": ["CSLB license number when published", "decision number"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": "UNKNOWN", "note": "some historical rows include an address"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(ASK="MEDIUM", CONTRACTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="LOW", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "HTML_TABLE_LIVE",
        "recommended_next_action": "Parse into a small reviewed fixture. Attach to profiles only on exact CSLB number. Preserve unmatched rows.",
    },
    {
        "source_id": "ca-dir-electrician-certified",
        "hub_home": "CONTRACTOR",
        "source_family": "trade_certification",
        "source_name": "DIR Electrician Certification Unit — Certified Electrician List",
        "regulator": "Department of Industrial Relations — Electrician Certification Unit",
        "source_url": "https://data.ca.gov/dataset/dir-electrician-certification-unit-ecu",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "REVIEW_REQUIRED",
        "identity_field": "CERTIFICATE_NUMBER (person)",
        "source_as_of": "2026-09-03",
        "last_checked": CHECKED,
        "grain": "certified electrician (person)",
        "record_count": 36983,
        "active_count": "UNKNOWN",
        "count_notes": "CKAN datastore total 36,983 on 2026-09-03. Fields: ELECTRICIAN_NAME, ZIP_CODE, CERTIFICATE_NUMBER, EXPIRATION_DATE. This is not a contractor-business universe and not a C-10 roster.",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="LOW", CONTRACTOR="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="MEDIUM", CONTACT_VALUE="NONE", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DOWNLOADED_NOT_COMMITTED",
        "recommended_next_action": "Keep as person-level enrichment. Never auto-attach to a contractor profile from name+zip.",
    },
    {
        "source_id": "ca-dir-electrician-trainee",
        "hub_home": "CONTRACTOR",
        "source_family": "trade_certification",
        "source_name": "DIR Electrician Certification Unit — Trainee List",
        "regulator": "Department of Industrial Relations — Electrician Certification Unit",
        "source_url": "https://data.ca.gov/dataset/dir-electrician-certification-unit-ecu",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "UNSAFE",
        "source_as_of": "2026-09-03",
        "last_checked": CHECKED,
        "grain": "electrician trainee (person)",
        "record_count": 19661,
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(CONTRACTOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="LOW", CONTACT_VALUE="NONE", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DOWNLOADED_NOT_COMMITTED",
        "recommended_next_action": "Do not use as a contractor business list.",
    },
    {
        "source_id": "ca-dgs-purchase-order-data",
        "hub_home": "CROSS_HUB",
        "source_family": "procurement",
        "source_name": "DGS Purchase Order Data (data.ca.gov)",
        "regulator": "California Department of General Services",
        "source_url": "https://data.ca.gov/dataset/purchase-order-data",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_VENDOR_REGISTRY",
        "identity_bar": "REVIEW_REQUIRED",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "purchase order",
        "record_count": "UNKNOWN",
        "count_notes": "Package exists on data.ca.gov (package_search hit). Vendor != CSLB licensed contractor. Not acquired this ticket (procurement is secondary to the license universe).",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "WEBSITE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(ASK="LOW", CONTRACTOR="MEDIUM", INVESTOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="LOW", CONTACT_VALUE="LOW", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="MEDIUM"),
        "acquisition_status": "INVENTORIED_NOT_ACQUIRED",
        "recommended_next_action": "Optional enrichment after CSLB master. Never replace a license roster with vendor rows.",
    },
    {
        "source_id": "ca-caleprocure",
        "hub_home": "CROSS_HUB",
        "source_family": "procurement",
        "source_name": "Cal eProcure / FISCal public search",
        "regulator": "Department of General Services / FISCal",
        "source_url": "https://caleprocure.ca.gov/pages/index.aspx",
        "access_class": "SOURCE_ACCESS_BLOCKED",
        "contact_rank": "OFFICIAL_VENDOR_REGISTRY",
        "identity_bar": "REVIEW_REQUIRED",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "state vendor / solicitation",
        "record_count": "UNKNOWN",
        "count_notes": "HTTP 403 from this environment. DGS FISCal intro URL returned a 404 title. Vendor != contractor license.",
        "hub_value": hv(CONTRACTOR="MEDIUM", INVESTOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="LOW", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "HTTP_403",
        "blocker": "403 Forbidden. Do not scrape around it.",
        "recommended_next_action": "Retry later from a residential network. Do not wait.",
    },
    {
        "source_id": "ca-dca-box-licensee-lists",
        "hub_home": "CROSS_HUB",
        "source_family": "licensee_lists",
        "source_name": "DCA Open Data / Box licensee lists",
        "regulator": "Department of Consumer Affairs",
        "source_url": "https://www.dca.ca.gov/consumers/public_info/",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "DCA board licensee list",
        "record_count": "UNKNOWN",
        "count_notes": "DCA points CSLB users to https://cslb.ca.gov/onlineservices/dataportal/ rather than the Box dump. Box URL https://dca.box.com/s/oss6hf8jys2bmgxqd2gdz7w4oepm2il9 is advertised for other boards. Do not scrape Box.",
        "hub_value": hv(ASK="LOW", CONTRACTOR="LOW", MOVE="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="MEDIUM", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="MEDIUM"),
        "acquisition_status": "CSLB_EXCLUDED_FROM_BOX",
        "recommended_next_action": "Use CSLB Data Portal for contractors. Recheck Box only for BHGS if a household-mover list appears.",
    },
    {
        "source_id": "ca-chhs-elms-locations",
        "hub_home": "SENIOR",
        "source_family": "facility_license",
        "source_name": "CDPH Licensed and Certified Healthcare Facility Locations (ELMS)",
        "regulator": "California Department of Public Health — Center for Health Care Quality",
        "source_url": "https://data.chhs.ca.gov/dataset/healthcare-facility-locations",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "FACID; CCN; LICENSE_NUMBER; HCAI_ID",
        "source_as_of": "2026-08-17",
        "last_checked": CHECKED,
        "grain": "licensed/certified healthcare facility location",
        "record_count": 15097,
        "active_count": 13401,
        "count_notes": "Datastore total 15,097. FAC_STATUS_TYPE_CODE=OPEN for all 15,097 dumped rows. LICENSE_STATUS_DESCRIPTION: ACTIVE 13,401; blank 1,357; INACTIVE - CAPEN DECISION 339. DATA_DATE 2026-08-17. Facility types include Home Health Agency 4,137; Hospice 2,114; SNF 1,186. This is not RCFE.",
        "identifier_fields": ["FACID", "CCN", "LICENSE_NUMBER", "HCAI_ID", "NPI", "ASPEN_FACID"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": 13560},
            "BUSINESS_EMAIL": {"present": True, "count": 12435, "note": "CONTACT_EMAIL may be an administrator mailbox. Do not treat as a personal consumer email harvest."},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": 15097},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="HIGH", SENIOR="HIGH", INSURANCE="LOW"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="HIGH", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DOWNLOADED_NOT_COMMITTED",
        "recommended_next_action": "Primary Senior state universe for CDPH-licensed facilities. Commit small fixtures only.",
    },
    {
        "source_id": "ca-hcai-current-listing",
        "hub_home": "SENIOR",
        "source_family": "facility_listing",
        "source_name": "HCAI Current California Healthcare Facility Listing",
        "regulator": "Department of Health Care Access and Information (HCAI)",
        "source_url": "https://data.chhs.ca.gov/dataset/licensed-healthcare-facility-listing",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "OSHPD_ID; LICENSE_NUM",
        "source_as_of": "2026-09-01",
        "last_checked": CHECKED,
        "grain": "HCAI facility listing row",
        "record_count": 10871,
        "active_count": 10856,
        "count_notes": "Datastore total 10,871. FACILITY_STATUS_DESC Open 10,856; Suspense 14; Closed 1. No phone/email fields. Categories include Home Health Agency 4,310; Hospice 2,669; SNF 1,078; GACH 458.",
        "identifier_fields": ["OSHPD_ID", "PERM_ID", "LICENSE_NUM"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": 10871},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="HIGH", SENIOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="LOW", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DOWNLOADED_NOT_COMMITTED",
        "recommended_next_action": "Crosswalk to ELMS via licensed-facility-crosswalk. Do not invent phones from this file.",
    },
    {
        "source_id": "ca-chhs-facility-crosswalk",
        "hub_home": "SENIOR",
        "source_family": "identity_crosswalk",
        "source_name": "Licensed Facility Crosswalk (ELMS-ASPEN-OSHPD)",
        "regulator": "CDPH / HCAI",
        "source_url": "https://data.chhs.ca.gov/dataset/licensed-facility-crosswalk",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": "2024-10",
        "last_checked": CHECKED,
        "grain": "FACID / ASPEN / OSHPD crosswalk row",
        "record_count": "UNKNOWN",
        "count_notes": "XLSX resources exist (ELMS-ASPEN-OSHPD, ELMS-ASPEN, ELMS-OSHPD). Last-modified metadata on the XLSX is 2024. Approved deterministic crosswalk when IDs match.",
        "hub_value": hv(SENIOR="HIGH", ASK="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="NONE", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "INVENTORIED_XLSX",
        "recommended_next_action": "Acquire XLSX next Senior ticket. Do not commit the full workbook.",
    },
    {
        "source_id": "ca-ccld-rcfe",
        "hub_home": "SENIOR",
        "source_family": "facility_license",
        "source_name": "CDSS CCLD Residential Care Facilities for the Elderly",
        "regulator": "California Department of Social Services — Community Care Licensing Division",
        "source_url": "https://data.chhs.ca.gov/dataset/ccl-facilities",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "facility_number",
        "source_as_of": "2025-05-25",
        "last_checked": CHECKED,
        "grain": "RCFE / CCRC facility",
        "record_count": 12522,
        "active_count": 7939,
        "count_notes": "Datastore resource 744d1583-f9eb-45b6-b0f8-b9a9dab936a6. file_date 05/25/2025. LICENSED 7,939; CLOSED 3,821; PENDING 739; ON PROBATION 23. Types: RESIDENTIAL CARE ELDERLY 12,389; RCFE-CONTINUING CARE RETIREMENT COMMUNITY 132. This snapshot is older than ELMS. Live search remains https://www.ccld.dss.ca.gov/carefacilitysearch/. Missing later months != zero facilities.",
        "identifier_fields": ["facility_number"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": 12522, "note": "CKAN COUNT(column) is non-null, not non-blank. Sample phones are populated. Exact non-empty excluding 'Unavailable' is UNKNOWN without a dump profile."},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": 12522},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="HIGH", SENIOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="HIGH", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DATASTORE_COUNTED",
        "recommended_next_action": "Dump CSV next Senior ticket. RCFE != SNF. CCRC rows are a subtype, not a separate regulator.",
    },
    {
        "source_id": "ca-ccld-hco",
        "hub_home": "SENIOR",
        "source_family": "home_care",
        "source_name": "CDSS CCLD Home Care Organization",
        "regulator": "California Department of Social Services — CCLD",
        "source_url": "https://data.chhs.ca.gov/dataset/ccl-facilities",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "facility_number",
        "source_as_of": "2025-05-25",
        "last_checked": CHECKED,
        "grain": "home care organization",
        "record_count": 3654,
        "active_count": "UNKNOWN",
        "count_notes": "Datastore total 3,654 as of file_date 05/25/2025. Home care organization != home health agency (CDPH).",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="MEDIUM", SENIOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DATASTORE_COUNTED",
        "recommended_next_action": "Keep distinct from CDPH home health.",
    },
    {
        "source_id": "ca-ccld-arf",
        "hub_home": "SENIOR",
        "source_family": "adult_residential",
        "source_name": "CDSS CCLD Adult Residential Facilities",
        "regulator": "California Department of Social Services — CCLD",
        "source_url": "https://data.chhs.ca.gov/dataset/ccl-facilities",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": "2025-05-25",
        "last_checked": CHECKED,
        "grain": "adult residential / adult day program",
        "record_count": 10498,
        "count_notes": "Not all rows are senior-specific. Do not collapse into RCFE.",
        "hub_value": hv(SENIOR="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DATASTORE_COUNTED",
        "recommended_next_action": "Filter by facility_type before any Senior profile use.",
    },
    {
        "source_id": "ca-ccld-search",
        "hub_home": "SENIOR",
        "source_family": "facility_lookup",
        "source_name": "CCLD Care Facility Search (Transparency Website)",
        "regulator": "California Department of Social Services — CCLD",
        "source_url": "https://www.ccld.dss.ca.gov/carefacilitysearch/",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "facility search result",
        "record_count": "UNKNOWN",
        "count_notes": "Live search. Page advertises a Download Data feature. The CHHS ccl-facilities CSVs are the bulk path used here. Do not scrape the search UI.",
        "hub_value": hv(ASK="HIGH", SENIOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "DOCUMENTED_NO_SCRAPE",
        "recommended_next_action": "Consumer verify link. Use CHHS dumps for bulk.",
    },
    {
        "source_id": "ca-dmhc-enforcement-trend",
        "hub_home": "INSURANCE",
        "source_family": "enforcement",
        "source_name": "DMHC Enforcement Actions, Trend",
        "regulator": "Department of Managed Health Care",
        "source_url": "https://data.chhs.ca.gov/dataset/enforcement-actions-trend",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "REVIEW_REQUIRED",
        "source_as_of": "2026-06-01",
        "last_checked": CHECKED,
        "grain": "enforcement action row",
        "record_count": 5435,
        "count_notes": "Datastore total 5,435. Action mix includes Letter of Agreement 4,212; Settlement Agreement 606; Cease and Desist Order 240; Accusation 53. OrganizationName is not NAIC. Accusation != finding. This is Knox-Keene / DMHC, not CDI admitted P&C.",
        "identifier_fields": ["OrganizationName", "ActionDate", "EnforcementAction"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": False, "count": 0},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="MEDIUM", INSURANCE="HIGH", SENIOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="MEDIUM", CONTACT_VALUE="NONE", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DOWNLOADED_NOT_COMMITTED",
        "recommended_next_action": "Use as source-level evidence. Profile attach only with EXACT NAIC/plan ID crosswalk — none is in this file.",
    },
    {
        "source_id": "ca-dmhc-imr-trend",
        "hub_home": "INSURANCE",
        "source_family": "appeals",
        "source_name": "DMHC Independent Medical Review Determinations, Trend",
        "regulator": "Department of Managed Health Care",
        "source_url": "https://data.chhs.ca.gov/dataset/independent-medical-review-imr-determinations-trend",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "UNSAFE",
        "source_as_of": "2026-06-01",
        "last_checked": CHECKED,
        "grain": "IMR determination",
        "record_count": 42749,
        "count_notes": "Datastore total 42,749. No plan NAIC in the dumped columns. PatientGender/AgeRange are aggregate attributes of the review, not a consumer PII dump we republish. Do not attach to a named issuer without an official plan identifier.",
        "hub_value": hv(ASK="MEDIUM", INSURANCE="MEDIUM", SENIOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="NONE", CONTACT_VALUE="NONE", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "DOWNLOADED_NOT_COMMITTED",
        "recommended_next_action": "Aggregate coverage only. 84MB dump stays gitignored.",
    },
    {
        "source_id": "ca-cdi-health-insurer-list",
        "hub_home": "INSURANCE",
        "source_family": "company_list",
        "source_name": "CDI List of Insurers Providing Health Insurance Coverage",
        "regulator": "California Department of Insurance",
        "source_url": "https://www.insurance.ca.gov/01-consumers/110-health/20-look/hcpcarriers.cfm",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "HIGH_CONFIDENCE",
        "source_as_of": "2025-12-31",
        "last_checked": CHECKED,
        "grain": "CDI-licensed health insurance company on this list",
        "record_count": 28,
        "active_count": 28,
        "count_notes": "Official HTML table: currently licensed to provide health insurance coverage as of December 31, 2025. Licensed != currently selling. This is not the full admitted-company universe and not DMHC Knox-Keene plans.",
        "identifier_fields": ["company name", "CDI company profile id in URL"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": 28},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": True, "count": 27, "note": "Prudential row has a phone and a blank website cell on the published table."},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": False, "count": 0},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="MEDIUM", INSURANCE="HIGH", SENIOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="MEDIUM", CONTACT_VALUE="HIGH", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "HTML_TABLE_COUNTED",
        "recommended_next_action": "Fixture the 28 rows. Join to NAIC via CDI company profile, not via name web search.",
    },
    {
        "source_id": "ca-cdi-company-lookup",
        "hub_home": "INSURANCE",
        "source_family": "company_lookup",
        "source_name": "CDI Insurance Company Lookup / Profiles",
        "regulator": "California Department of Insurance",
        "source_url": "https://www.insurance.ca.gov/01-consumers/120-company/lookup/index.cfm",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "admitted company profile",
        "record_count": "UNKNOWN",
        "count_notes": "Interactive company search. No free bulk admitted roster found. Paid mailing lists exist.",
        "hub_value": hv(ASK="MEDIUM", INSURANCE="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "DOCUMENTED_NO_SCRAPE",
        "recommended_next_action": "Consumer verify. Do not scrape APEX apps.",
    },
    {
        "source_id": "ca-cdi-mailing-lists-paid",
        "hub_home": "INSURANCE",
        "source_family": "producer_list",
        "source_name": "CDI Producer Licensing Bureau mailing lists",
        "regulator": "California Department of Insurance",
        "source_url": "https://www.insurance.ca.gov/0200-industry/0130-mailing-lists/",
        "access_class": "SOURCE_AVAILABLE_BY_REQUEST",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "licensed producer / admitted company extract",
        "record_count": "UNKNOWN",
        "count_notes": "Paid lists. Agent/agency qualification lists priced from $75 minimum to greater than $4,000. Company appointment list $363 per NAIC. Check required. ~400,000 licensed agents/brokers is a Find-an-Agent marketing figure, not a verified extract count from this ticket.",
        "hub_value": hv(INSURANCE="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="HIGH", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "REQUEST_NOT_DRAFTED",
        "recommended_next_action": "Low effort this ticket. Company-level CDI HTML list is the easy win.",
    },
    {
        "source_id": "ca-fair-plan",
        "hub_home": "INSURANCE",
        "source_family": "residual_market",
        "source_name": "California FAIR Plan",
        "regulator": "California FAIR Plan Association (industry residual market; CDI oversight context)",
        "source_url": "https://www.fairplan.org/",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OTHER_OFFICIAL_SOURCE",
        "identity_bar": "UNSAFE",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "program landing page",
        "record_count": "UNKNOWN",
        "count_notes": "Root URL returned a JS lander redirect. Not a company roster. Not acquired.",
        "hub_value": hv(INSURANCE="LOW", ASK="LOW"),
        "value_scores": scores(IDENTITY_VALUE="NONE", CONTACT_VALUE="NONE", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="LOW"),
        "acquisition_status": "LANDER_ONLY",
        "recommended_next_action": "Skip this ticket.",
    },
    {
        "source_id": "ca-dfpi-crmla",
        "hub_home": "LENDER",
        "source_family": "mortgage_license",
        "source_name": "DFPI California Residential Mortgage Lending Act",
        "regulator": "Department of Financial Protection and Innovation",
        "source_url": "https://dfpi.ca.gov/regulated-industries/california-residential-mortgage-lending-act/",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "NMLS ID / DFPI license number",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "CRMLA company or branch",
        "record_count": "UNKNOWN",
        "count_notes": "No Florida-OFR-style free bulk mortgage roster on data.ca.gov. Official page sends the public to NMLS Consumer Access and DOCQNET. 2024 CRMLA Annual Report snapshot: 389 licensees and 5,104 branches as of December 31, 2024 — that is a report figure, not a live file row count.",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "WEBSITE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(ASK="MEDIUM", LENDER="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "SEARCH_ONLY_NO_BULK",
        "blocker": "No free bulk CRMLA roster found. NMLS root returned Cloudflare 403 to this user-agent.",
        "recommended_next_action": "Use NMLS Consumer Access as the public verify path. Do not scrape DOCQNET.",
    },
    {
        "source_id": "ca-dfpi-docqnet",
        "hub_home": "LENDER",
        "source_family": "license_lookup",
        "source_name": "DFPI DOCQNET License Search",
        "regulator": "Department of Financial Protection and Innovation",
        "source_url": "https://docqnet.dfpi.ca.gov/licensesearch",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "DFPI licensee search result",
        "record_count": "UNKNOWN",
        "count_notes": "HTTP 200. Page states Individual MLO licenses should be checked through NMLS Consumer Access.",
        "hub_value": hv(LENDER="HIGH", ASK="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="LOW"),
        "acquisition_status": "DOCUMENTED_NO_SCRAPE",
        "recommended_next_action": "Do not scrape.",
    },
    {
        "source_id": "ca-nmls-consumer-access",
        "hub_home": "LENDER",
        "source_family": "nmls",
        "source_name": "NMLS Consumer Access",
        "regulator": "Nationwide Multistate Licensing System (state-license records; not a California regulator)",
        "source_url": "https://www.nmlsconsumeraccess.org/",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "NMLS ID",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "NMLS company, branch, or individual",
        "record_count": "UNKNOWN",
        "count_notes": "HTTP 403 Cloudflare from this user-agent. DFPI and CalDRE both point consumers here. State vs NMLS: NMLS is the system of record display for many CA mortgage licenses, not a California bulk download.",
        "hub_value": hv(ASK="MEDIUM", LENDER="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "CLOUDFLARE_403",
        "blocker": "Do not bypass Cloudflare.",
        "recommended_next_action": "Browser verify link only.",
    },
    {
        "source_id": "ca-caldre-license-lookup",
        "hub_home": "LENDER",
        "source_family": "real_estate_license",
        "source_name": "CalDRE Public License Lookup",
        "regulator": "California Department of Real Estate",
        "source_url": "https://www2.dre.ca.gov/PublicASP/pplinfo.asp",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "DRE license number; MLO endorsement is not a CRMLA license",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "real estate licensee",
        "record_count": "UNKNOWN",
        "count_notes": "HTTP 200. DRE MLO endorsement != DFPI CRMLA/CFL company license. No bulk roster found this ticket.",
        "hub_value": hv(LENDER="MEDIUM", ASK="LOW"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="LOW", REGULATORY_VALUE="MEDIUM", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="LOW"),
        "acquisition_status": "DOCUMENTED_NO_SCRAPE",
        "recommended_next_action": "Keep distinct from DFPI. Do not merge MLO endorsement into a mortgage-company universe.",
    },
    {
        "source_id": "ca-calhfa-approved-lenders",
        "hub_home": "LENDER",
        "source_family": "government_program",
        "source_name": "CalHFA Approved Lenders directory",
        "regulator": "California Housing Finance Agency",
        "source_url": "https://www.calhfa.ca.gov/apps/approvedlenders/",
        "access_class": "OPEN_BULK_DOWNLOAD",
        "contact_rank": "OFFICIAL_GOVERNMENT_PROGRAM",
        "identity_bar": "REVIEW_REQUIRED",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "approved lender branch row",
        "record_count": "UNKNOWN",
        "count_notes": "Official HTML table of CalHFA-approved lender branches with street address and phone and program flags. Unique legal-entity count UNKNOWN (many repeated branch rows). CalHFA approval != DFPI license and != NMLS authorization.",
        "identifier_fields": ["lender display name", "branch address"],
        "contact_fields": {
            "BUSINESS_PHONE": {"present": True, "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": False, "count": 0},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": True, "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": False, "count": 0},
        },
        "hub_value": hv(ASK="MEDIUM", LENDER="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="MEDIUM", CONTACT_VALUE="HIGH", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="HIGH", ACQUISITION_EASE="HIGH"),
        "acquisition_status": "HTML_TABLE_LIVE",
        "recommended_next_action": "Parse branch table next Lender ticket. Do not rank 'top hero' officers as Trust Hub ranking.",
    },
    {
        "source_id": "ca-bhgs-household-movers",
        "hub_home": "MOVE",
        "source_family": "mover_permit",
        "source_name": "BHGS Household Movers licensing",
        "regulator": "Bureau of Household Goods and Services (Department of Consumer Affairs)",
        "source_url": "https://bhgs.dca.ca.gov/",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "CAL-T number",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "household mover permit",
        "record_count": "UNKNOWN",
        "count_notes": "Intrastate household-goods authority transferred from CPUC to BHGS (2018). License search is via DCA search.dca.ca.gov and BHGS Connect (connect.dca.ca.gov/bhgs). No household-mover bulk file on data.ca.gov (package_search count 0). CAL-T != USDOT. CPUC is not the current regulator.",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(ASK="MEDIUM", MOVE="HIGH", CONTRACTOR="LOW"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="MEDIUM", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "SEARCH_ONLY_NO_BULK",
        "blocker": "No open bulk roster found. Do not scrape Connect or DCA search.",
        "recommended_next_action": "Watch DCA Box dumps for a BHGS HHM list. Citations/disciplinary pages are HTML.",
    },
    {
        "source_id": "ca-bhgs-enforcement",
        "hub_home": "MOVE",
        "source_family": "enforcement",
        "source_name": "BHGS Citations and Disciplinary Actions",
        "regulator": "Bureau of Household Goods and Services",
        "source_url": "https://bhgs.dca.ca.gov/enforcement/lookup.shtml",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "citation / disciplinary action",
        "record_count": "UNKNOWN",
        "hub_value": hv(MOVE="HIGH", ASK="LOW"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="NONE", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="MEDIUM", ACQUISITION_EASE="LOW"),
        "acquisition_status": "DOCUMENTED_NO_SCRAPE",
        "recommended_next_action": "Per-license disclosure. Do not auto-attach from name search.",
    },
    {
        "source_id": "ca-dfpi-investment-adviser",
        "hub_home": "INVESTOR",
        "source_family": "investment_adviser",
        "source_name": "DFPI investment adviser / financial service provider search",
        "regulator": "Department of Financial Protection and Innovation",
        "source_url": "https://dfpi.ca.gov/licensee-and-financial-service-provider-search/",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_REGULATOR",
        "identity_bar": "EXACT",
        "identity_field": "CRD / DFPI license number",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "state-registered adviser or other DFPI licensee",
        "record_count": "UNKNOWN",
        "count_notes": "No bulk California RIA roster on data.ca.gov (investment adviser package_search returned unrelated FTB data). SEC IARD / FINRA BrokerCheck remain federal. CA principal office != complete state-RIA denominator.",
        "hub_value": hv(ASK="LOW", INVESTOR="HIGH"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="LOW", REGULATORY_VALUE="HIGH", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="LOW"),
        "acquisition_status": "SEARCH_ONLY_NO_BULK",
        "recommended_next_action": "Keep search-only. Do not scrape.",
    },
    {
        "source_id": "ca-sos-bizfile",
        "hub_home": "CROSS_HUB",
        "source_family": "business_entity",
        "source_name": "California Secretary of State BizFile",
        "regulator": "California Secretary of State",
        "source_url": "https://bizfileonline.sos.ca.gov/search/business",
        "access_class": "OPEN_SEARCH_ONLY",
        "contact_rank": "OFFICIAL_BUSINESS_REGISTRY",
        "identity_bar": "EXACT",
        "identity_field": "SOS entity number",
        "source_as_of": CHECKED,
        "last_checked": CHECKED,
        "grain": "business entity",
        "record_count": "UNKNOWN",
        "count_notes": "Incapsula JS challenge. Not a license roster. Entity registration != CSLB / DFPI / CDI / BHGS authority.",
        "contact_fields": {
            "BUSINESS_PHONE": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "BUSINESS_EMAIL": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "WEBSITE": {"present": False, "count": 0},
            "PHYSICAL_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
            "MAILING_BUSINESS_ADDRESS": {"present": "UNKNOWN", "count": "UNKNOWN"},
        },
        "hub_value": hv(ASK="LOW", CONTRACTOR="MEDIUM", LENDER="LOW", INSURANCE="LOW", SENIOR="LOW", MOVE="LOW", INVESTOR="MEDIUM"),
        "value_scores": scores(IDENTITY_VALUE="HIGH", CONTACT_VALUE="LOW", REGULATORY_VALUE="LOW", MARKET_INTELLIGENCE_VALUE="LOW", ACQUISITION_EASE="LOW"),
        "acquisition_status": "INCAPSULA_CHALLENGE",
        "blocker": "Do not bypass Incapsula.",
        "recommended_next_action": "Name+official address HIGH CONFIDENCE join only when a lawful extract exists. Never overwrite regulator contacts with SOS contacts.",
    },
]


def dump(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    BASE.mkdir(parents=True, exist_ok=True)
    dump(
        BASE / "source-manifest.json",
        {
            "ticket": TICKET,
            "state": "CA",
            "scope": "STATE_LEVEL_ONLY",
            "source_as_of": CHECKED,
            "last_checked": CHECKED,
            "publication": {
                "public_california_routes": False,
                "sitemap_changes": False,
                "trust_score": False,
                "paid_ranking": False,
            },
            "principles": [
                "LIBERAL_INCLUSION",
                "CONSERVATIVE_ATTRIBUTION",
                "TRANSPARENT_COVERAGE",
                "missing_source_is_not_zero",
                "vendor_is_not_contractor_license",
                "accusation_is_not_finding",
                "complaint_is_not_violation",
                "PWCR_is_not_CSLB",
                "BHGS_CAL-T_is_not_USDOT",
                "DRE_MLO_endorsement_is_not_CRMLA",
                "CDPH_facility_is_not_RCFE",
                "home_care_organization_is_not_home_health",
            ],
            "sources": SOURCES,
        },
    )

    dump(
        BASE / "acquisition-summary.json",
        {
            "ticket": TICKET,
            "checked": CHECKED,
            "acquired_this_ticket": [
                {
                    "source_id": "ca-chhs-elms-locations",
                    "method": "CKAN datastore/dump",
                    "rows": 15097,
                    "phone_nonempty": 13560,
                    "email_nonempty": 12435,
                    "committed": False,
                },
                {
                    "source_id": "ca-hcai-current-listing",
                    "method": "CKAN datastore/dump",
                    "rows": 10871,
                    "phone_nonempty": 0,
                    "email_nonempty": 0,
                    "committed": False,
                },
                {
                    "source_id": "ca-dir-electrician-certified",
                    "method": "CKAN datastore/dump",
                    "rows": 36983,
                    "committed": False,
                },
                {
                    "source_id": "ca-dir-electrician-trainee",
                    "method": "CKAN datastore/dump",
                    "rows": 19661,
                    "committed": False,
                },
                {
                    "source_id": "ca-dmhc-enforcement-trend",
                    "method": "CKAN datastore/dump",
                    "rows": 5435,
                    "committed": False,
                },
                {
                    "source_id": "ca-dmhc-imr-trend",
                    "method": "CKAN datastore/dump",
                    "rows": 42749,
                    "committed": False,
                    "note": "84MB local dump gitignored",
                },
                {
                    "source_id": "ca-ccld-rcfe",
                    "method": "CKAN datastore_search total",
                    "rows": 12522,
                    "licensed": 7939,
                    "committed": False,
                },
                {
                    "source_id": "ca-cdi-health-insurer-list",
                    "method": "official HTML table count",
                    "rows": 28,
                    "committed": True,
                },
                {
                    "source_id": "ca-dir-dlse-debarment",
                    "method": "official HTML table",
                    "table_data_rows_parsed": 62,
                    "committed": True,
                    "note": "sample fixture only",
                },
            ],
            "attempted_incomplete": [
                {
                    "source_id": "ca-cslb-master-list",
                    "method": "ASP.NET postback lbMasterCSV",
                    "result": "IncompleteRead 27890218 bytes",
                    "row_count": "UNKNOWN",
                }
            ],
            "not_acquired": [
                "CSLB personnel/WC files",
                "CSLB paid Full File",
                "DIR PWCR roster",
                "Cal eProcure (HTTP 403)",
                "NMLS (Cloudflare 403)",
                "SOS BizFile (Incapsula)",
                "BHGS mover roster",
                "DFPI CRMLA bulk",
                "CDI admitted-company paid lists",
            ],
        },
    )

    dump(
        BASE / "cross-hub-source-map.json",
        {
            "ticket": TICKET,
            "note": "Statewide sources live once. Do not duplicate per hub.",
            "sources": [s["source_id"] for s in SOURCES if s.get("hub_home") == "CROSS_HUB"],
        },
    )

    dump(
        BASE / "contractor-priority-source-map.json",
        {
            "ticket": TICKET,
            "universe": "CSLB contractor licenses",
            "priority_order": [
                "ca-cslb-master-list",
                "ca-cslb-personnel",
                "ca-cslb-workers-comp",
                "ca-cslb-classifications",
                "ca-dir-dlse-debarment",
                "ca-dir-pwcr",
                "ca-cslb-enforcement-report",
                "ca-cslb-full-file-paid",
                "ca-dgs-purchase-order-data",
                "ca-dir-electrician-certified",
            ],
            "do_not_confuse": [
                "PWCR != CSLB license",
                "DGS vendor != licensed contractor",
                "electrician certificate != C-10 business",
                "HIS registration != contractor license",
                "cancelled/revoked omission in free file != clean history",
            ],
        },
    )

    dump(
        BASE / "contact-source-summary.json",
        {
            "ticket": TICKET,
            "rank_order": [
                "OFFICIAL_REGULATOR",
                "OFFICIAL_VENDOR_REGISTRY",
                "OFFICIAL_GOVERNMENT_PROGRAM",
                "OFFICIAL_BUSINESS_REGISTRY",
                "OTHER_OFFICIAL_SOURCE",
            ],
            "rules": [
                "Do not overwrite stronger contact evidence with weaker source data.",
                "Do not infer personal contact information.",
                "CSLB emails are withheld under BPC 27.",
                "CalHFA program phones do not replace DFPI/NMLS regulator phones.",
                "SOS entity addresses do not replace CSLB license addresses.",
            ],
            "inventory": [
                {
                    "source_id": s["source_id"],
                    "contact_rank": s.get("contact_rank"),
                    "fields": s.get("contact_fields"),
                }
                for s in SOURCES
                if s.get("contact_fields")
            ],
        },
    )

    dump(
        BASE / "identity-source-map.json",
        {
            "ticket": TICKET,
            "bars": {
                "EXACT": "official identifier match (license, NMLS, NPN, NAIC, CRD, CMS CCN, state facility ID, USDOT, CAL-T, FACID, PWCR, source-native stable ID)",
                "HIGH_CONFIDENCE": "exact legal name + exact official business address, or an approved deterministic crosswalk",
                "REVIEW_REQUIRED": "name + city; DBA ambiguity; common-name conflict; person/company ambiguity",
                "UNSAFE": "name alone; phone alone; search-engine matching",
            },
            "rules": [
                "Never auto-attach adverse evidence from unsafe identity.",
                "Preserve unmatched official evidence.",
                "Profile-level negative/regulatory evidence requires the higher identity bar.",
                "Aggregate/source-level evidence can be published with incomplete identity.",
            ],
            "crosswalks": [
                {"from": "CSLB license number", "to": "DIR DLSE debarment CSLB number", "bar": "EXACT"},
                {"from": "FACID", "to": "HCAI/OSHPD_ID", "bar": "EXACT", "via": "ca-chhs-facility-crosswalk"},
                {"from": "FACID", "to": "CMS CCN", "bar": "EXACT", "via": "ELMS CCN field when populated"},
                {"from": "CCLD facility_number", "to": "ELMS FACID", "bar": "REVIEW_REQUIRED", "note": "different regulators; no approved crosswalk acquired this ticket"},
                {"from": "CalHFA lender display name", "to": "NMLS ID", "bar": "REVIEW_REQUIRED"},
                {"from": "electrician CERTIFICATE_NUMBER", "to": "CSLB C-10 license", "bar": "REVIEW_REQUIRED"},
                {"from": "DGS vendor name", "to": "CSLB license", "bar": "REVIEW_REQUIRED"},
            ],
        },
    )

    dump(
        BASE / "six-hub-value-matrix.json",
        {
            "ticket": TICKET,
            "note": "Prioritization, not consumer ranking. No Trust Score.",
            "sources": [
                {
                    "source_id": s["source_id"],
                    "hub_value": s.get("hub_value"),
                    "scores": s.get("value_scores"),
                    "access_class": s.get("access_class"),
                }
                for s in SOURCES
            ],
        },
    )

    # per-hub stubs
    hub_map = {
        "contractor": [s for s in SOURCES if s.get("hub_home") == "CONTRACTOR"],
        "lender": [s for s in SOURCES if s.get("hub_home") == "LENDER"],
        "insurance": [s for s in SOURCES if s.get("hub_home") == "INSURANCE"],
        "senior": [s for s in SOURCES if s.get("hub_home") == "SENIOR"],
        "move": [s for s in SOURCES if s.get("hub_home") == "MOVE"],
        "investor": [s for s in SOURCES if s.get("hub_home") == "INVESTOR"],
    }
    for hub, rows in hub_map.items():
        dump(
            BASE / hub / "source-manifest.json",
            {
                "ticket": TICKET,
                "hub": hub,
                "state": "CA",
                "source_as_of": CHECKED,
                "source_ids": [r["source_id"] for r in rows],
                "sources": rows,
            },
        )

    print("emitted", len(SOURCES), "sources")


if __name__ == "__main__":
    main()
