import Link from 'next/link';
import {redirect} from 'next/navigation';
import {AdminShell} from '../../admin-shell';
import {withAdminSecurity} from '@/lib/control-plane/server';
import {AdminAuthError} from '@/lib/control-plane/security';
import {readBusinessOperations,type BusinessListFilter} from '@/lib/control-plane/business-growth';
export const dynamic='force-dynamic';export const metadata={title:'Business Operations | Ask Trust Hub',robots:{index:false,follow:false}};
const FILTERS=['ALL','CLAIMED','ACTIVATED','NOT_ACTIVATED','ACTIVE_30D','INACTIVE_30D','NO_MANAGER_OPEN','NO_POST_CLAIM_ACTION'] as const;
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){try{const filter=String((await searchParams).filter??'ALL') as BusinessListFilter;const {staff,data}=await withAdminSecurity(async(s,t,_ctx,sql)=>({staff:await s.require(t,'ADMIN_VIEW'),data:await readBusinessOperations(sql,FILTERS.includes(filter as never)?filter:'ALL')}));return <AdminShell staff={staff}><header><p className="text-xs font-semibold uppercase tracking-wider text-indigo">Operations</p><h2 className="text-3xl font-semibold text-navy">Business Operations</h2><p className="mt-2 text-sm text-muted-foreground">Internal lifecycle view. Account activity is separate from regulatory status and ranking.</p></header><nav className="flex flex-wrap gap-2" aria-label="Business filters">{FILTERS.map(f=><Link key={f} href={`?filter=${f}`} className="btn-secondary">{f.replaceAll('_',' ')}</Link>)}</nav><p className="text-xs text-muted-foreground">Exact Manager-open telemetry since {data.epoch?new Date(data.epoch).toLocaleString('en-US',{timeZone:'UTC'})+' UTC':'not activated'}.</p><div className="card-surface overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr>{['Organization','Trust Hub account','Profiles','Hubs','Acquisition','Activation','Last activity','30-day active','Team','Layer B completeness'].map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.orgId}><td className="border-b p-3"><Link className="link-inline" href={`/admin/operations/businesses/${r.orgId}`}>{r.organization}</Link></td><td className="border-b p-3">{r.organizationStatus}</td><td className="border-b p-3">{r.profileCount} ({r.activeGrantCount} active)</td><td className="border-b p-3">{r.hubs.join(', ')||'—'}</td><td className="border-b p-3">{r.acquisitionSource}{r.campaign?` · ${r.campaign}`:''}</td><td className="border-b p-3">{r.activationState.replaceAll('_',' ')}</td><td className="border-b p-3">{r.lastActivityAt?new Date(r.lastActivityAt).toLocaleDateString('en-US',{timeZone:'UTC'}):'No measured activity'}</td><td className="border-b p-3">{r.active30d===null?'NOT INSTRUMENTED':r.active30d?'YES':'NO'}</td><td className="border-b p-3">{r.teamSize}</td><td className="border-b p-3">{r.completeness===null?'N/A':`${r.completeness}% business-supplied`}</td></tr>)}</tbody></table>{!data.rows.length?<p className="p-5 text-sm text-muted-foreground">No organizations match this filter. No zero or activity state was inferred.</p>:null}</div></AdminShell>}catch(e){if(e instanceof AdminAuthError&&e.code==='UNAUTHENTICATED')redirect('/admin/login');throw e}}
