import Link from 'next/link';
import {redirect} from 'next/navigation';
import {AdminAuthError} from '@/lib/control-plane/security';
import {withAdminSecurity} from '@/lib/control-plane/server';
import {readSessionToken,withPlatform} from '@/lib/customer/server';
import {withAskTx} from '@/lib/customer/db';
import {customerLog} from '@/lib/customer/log';
import {normalizeFounderFilters,readFounderDashboard,type FounderDashboard,type FounderMetric} from '@/lib/control-plane/founder-metrics';
import {AdminShell} from './admin-shell';

export const dynamic='force-dynamic';
export const metadata={title:'Founder Control Center | Ask Trust Hub',robots:{index:false,follow:false}};

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  let staff;
  try{staff=await withAdminSecurity((s,t)=>s.require(t,'ADMIN_VIEW'))}
  catch(e){
    if(e instanceof AdminAuthError&&e.code==='DISABLED')return <AccessState title="Admin access disabled" copy="This staff authorization is disabled. Contact a Super Admin if access should be restored."/>;
    if(e instanceof AdminAuthError&&e.code==='FORBIDDEN')return <AccessState title="Admin access denied" copy="This staff role does not permit access to the Control Center."/>;
    if(e instanceof AdminAuthError&&e.code==='UNAUTHENTICATED'){
      try{const token=await readSessionToken(),user=await withPlatform(p=>p.sessionUser(token));if(!user)redirect('/admin/login');return <AccessState title="Admin access denied" copy="This Ask identity has no active staff authorization."/>}
      catch(error){if((error as{digest?:string})?.digest?.startsWith('NEXT_REDIRECT'))throw error;customerLog('admin_authorization_infrastructure_error',{routeFamily:'/admin'},'error');return <AccessState title="Control Plane temporarily unavailable" copy="Staff authorization could not be verified. No access was granted. Please try again later."/>}
    }
    customerLog('admin_authorization_infrastructure_error',{routeFamily:'/admin'},'error');return <AccessState title="Control Plane temporarily unavailable" copy="Staff authorization could not be verified. No access was granted. Please try again later."/>;
  }
  const filters=normalizeFounderFilters(await searchParams);
  let dashboard:FounderDashboard|null=null;
  try{dashboard=await withAskTx(client=>readFounderDashboard(client,filters))}catch(error){customerLog('founder_dashboard_read_failed',{errorClass:error instanceof Error?error.name:'unknown'},'error')}
  return <AdminShell staff={staff}>
    <section aria-labelledby="network-pulse"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 id="network-pulse" className="text-2xl font-semibold text-navy">Network pulse</h2><p className="mt-1 text-sm text-muted-foreground">Operational truth, bounded first-party telemetry, and explicit data gaps.</p></div><DashboardFilters filters={filters}/></div>{dashboard?<p className="mt-3 text-xs text-muted-foreground">As of {new Date(dashboard.generatedAt).toLocaleString('en-US',{timeZone:'UTC'})} UTC · First-party Search telemetry since {dashboard.firstPartyStartedAt?new Date(dashboard.firstPartyStartedAt).toLocaleString('en-US',{timeZone:'UTC'})+' UTC':'not activated'}</p>:null}<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(dashboard?.metrics??degradedMetrics(filters.window)).map(metric=><MetricCard key={metric.key} metric={metric}/>)}</div></section>
    <section id="search-health" aria-labelledby="search-heading"><h2 id="search-heading" className="text-2xl font-semibold text-navy">Search health</h2>{dashboard?<div className="mt-4 grid gap-5 lg:grid-cols-2"><DataTable heading="Terminal outcomes" headers={['Outcome','Count','Rate']} rows={dashboard.searchOutcomes.map(r=>[r.outcome,String(r.count),`${r.rate}%`])}/><DataTable heading="Result-count buckets" headers={['Bucket','Count']} rows={dashboard.resultBuckets.map(r=>[r.bucket,String(r.count)])}/><DataTable heading="By Hub" headers={['Hub','Executions']} rows={dashboard.searchByHub.map(r=>[r.hub,String(r.count)])}/><DataTable heading="By intent" headers={['Intent','Executions']} rows={dashboard.searchByIntent.map(r=>[r.intent,String(r.count)])}/></div>:<UnavailableBlock/>}</section>
    <section aria-labelledby="claim-heading"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="claim-heading" className="text-2xl font-semibold text-navy">Business claim funnel</h2><p className="mt-1 text-sm text-muted-foreground">Durable claim and grant records are authoritative. Behavioral events never override them.</p></div><Link className="link-inline min-h-11 items-center" href="/admin/operations/claims">Open Claim Operations</Link></div>{dashboard?<div className="mt-4"><DataTable heading="Current window" headers={['Stage','Count','Source']} rows={dashboard.claimStages.map(r=>[r.stage,String(r.count),r.source])}/></div>:<UnavailableBlock/>}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div aria-labelledby="attention-heading"><h2 id="attention-heading" className="text-2xl font-semibold text-navy">Needs Attention</h2><p className="mt-1 text-sm text-muted-foreground">Incidents and operational problems only.</p><ItemList empty="No currently measurable attention signal in this window." items={(dashboard?.needsAttention??[]).map(i=>({title:`${i.severity} · ${i.title}`,detail:`${i.count} · ${i.source}`,href:i.href}))}/></div><div aria-labelledby="growth-heading"><h2 id="growth-heading" className="text-2xl font-semibold text-navy">Growth opportunities</h2><p className="mt-1 text-sm text-muted-foreground">Evidence-supported cohorts, kept separate from incidents.</p><ItemList empty="No supported opportunity cohort meets the display threshold." items={(dashboard?.growthOpportunities??[]).map(i=>({title:i.title,detail:`${i.count} · ${i.basis}`}))}/></div></section>
    <section aria-labelledby="business-growth-heading"><h2 id="business-growth-heading" className="text-2xl font-semibold text-navy">Business activation and campaigns</h2><p className="mt-1 text-sm text-muted-foreground">Activation uses the frozen grant + exact Manager open + qualifying action contract. Historical open gaps remain explicit.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><QuickCard title="Business Operations" href="/admin/operations/businesses" copy="Organizations, exact managed profiles, activation, retention, teams and Layer B completeness."/><QuickCard title="Campaigns" href="/admin/growth/campaigns" copy="Exact-profile outreach attribution with honest provider connection states."/></div></section>
    <section className="grid gap-4 md:grid-cols-3"><QuickCard title="Security" href="/admin/security" copy="Named staff, roles, status and session authorization."/><QuickCard title="Audit" href="/admin/audit" copy="Append-only privileged activity history."/><QuickCard title="Controls" href="/admin/controls" copy="Recorded intent; all flags remain not yet connected."/></section>
  </AdminShell>
}

function DashboardFilters({filters}:{filters:{window:string;hub?:string;jurisdiction?:string;intent?:string}}){return <form className="flex flex-wrap items-end gap-2" method="get"><label className="text-xs font-semibold">Window<select name="window" defaultValue={filters.window} className="ml-2 min-h-11 rounded-lg border border-border px-2">{['TODAY','7D','30D'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-xs font-semibold">Hub<select name="hub" defaultValue={filters.hub??''} className="ml-2 min-h-11 rounded-lg border border-border px-2"><option value="">All Network</option>{['ask','contractor','move','lender','senior','insurance','investor'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-xs font-semibold">State<input name="jurisdiction" defaultValue={filters.jurisdiction??''} maxLength={2} size={2} className="ml-2 min-h-11 rounded-lg border border-border px-2 uppercase"/></label><label className="text-xs font-semibold">Intent<input name="intent" defaultValue={filters.intent??''} maxLength={64} className="ml-2 min-h-11 w-36 rounded-lg border border-border px-2"/></label><button className="min-h-11 rounded-lg bg-navy px-4 text-sm font-semibold text-white">Apply</button></form>}
function MetricCard({metric}:{metric:FounderMetric}){return <article className="card-surface p-4"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-semibold text-navy">{metric.label}</h3><span className="rounded-full border border-border px-2 py-1 text-[10px] font-bold">{metric.status.replaceAll('_',' ')}</span></div><p className="mt-3 text-2xl font-semibold text-navy">{metric.displayValue}</p>{metric.numerator!==undefined?<p className="mt-1 text-xs text-muted-foreground">{metric.numerator} / {metric.denominator}</p>:null}<details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold text-indigo">Definition and provenance</summary><p className="mt-2">{metric.definition}</p><p className="mt-1 text-muted-foreground">Source: {metric.source}</p>{metric.limitation?<p className="mt-1 text-amber-900">Limitation: {metric.limitation}</p>:null}</details></article>}
function DataTable({heading,headers,rows}:{heading:string;headers:string[];rows:string[][]}){return <div className="card-surface overflow-x-auto p-4"><h3 className="font-semibold text-navy">{heading}</h3><table className="mt-3 min-w-full text-left text-sm"><thead><tr>{headers.map(h=><th className="border-b p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td className="border-b p-2" key={j}>{c}</td>)}</tr>)}</tbody></table>{rows.length===0?<p className="py-4 text-sm text-muted-foreground">No observations in this instrumented window.</p>:null}</div>}
function ItemList({items,empty}:{items:Array<{title:string;detail:string;href?:string}>;empty:string}){return <ul className="mt-4 space-y-3">{items.length?items.map((i,n)=><li className="card-surface p-4" key={`${i.title}-${n}`}><p className="font-semibold text-navy">{i.title}</p><p className="mt-1 text-sm text-muted-foreground">{i.detail}</p>{i.href?<Link className="link-inline mt-2 inline-flex" href={i.href}>Open</Link>:null}</li>):<li className="card-surface p-4 text-sm text-muted-foreground">{empty}</li>}</ul>}
function UnavailableBlock(){return <p className="card-surface mt-4 p-4 text-sm"><strong>DEGRADED:</strong> Control Plane read data is temporarily unavailable. No missing value is shown as zero.</p>}
function degradedMetrics(window:'TODAY'|'7D'|'30D'):FounderMetric[]{return ['research_sessions','search_results_rate','save_watch','activated_consumers','alert_return','claim_cta_start','claim_completion','pending_claims','business_activation','business_30d_active','search_dead_end_rate','search_error_rate','search_p50','search_p95'].map(key=>({key,label:key.replaceAll('_',' '),value:null,displayValue:'DEGRADED',status:'DEGRADED',window,asOf:new Date().toISOString(),source:'Control Plane read model',definition:'Metric could not be safely read.',limitation:'Database read failed; no zero inferred.'}))}
function AccessState({title,copy}:{title:string;copy:string}){return <main className="container-page py-12"><h1 className="text-3xl font-semibold text-navy">{title}</h1><p className="mt-3">{copy}</p></main>}
function QuickCard({title,href,copy}:{title:string;href:string;copy:string}){return <article className="card-surface p-5"><h2 className="text-xl font-semibold text-navy">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{copy}</p><Link className="link-inline mt-4 inline-flex min-h-11 items-center" href={href}>Open {title}</Link></article>}
