'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

type Member = { id:string; email:string; role:'owner'|'manager'|'staff'|'billing'; created_at:string };
type Invitation = { id:string; invited_email_normalized:string; invited_role:string; expires_at:string; version:number };

export function OrganizationTeamPanel({orgId,canAdmin,members,invitations}:{orgId:string;canAdmin:boolean;members:Member[];invitations:Invitation[]}) {
  const router=useRouter(), [status,setStatus]=useState(''), [pending,setPending]=useState(false);
  async function invite(formData:FormData) { setPending(true); setStatus('Sending invitation...'); const response=await fetch(`/api/customer/organizations/${orgId}/invitations`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:formData.get('email'),role:formData.get('role')})}); const result=await response.json(); setPending(false); setStatus(response.ok?(result.emailSent?'Invitation sent.':'Invitation saved; email delivery can be retried.'):`Could not invite: ${result.error||'unavailable'}`); if(response.ok)router.refresh(); }
  async function invitationAction(id:string,version:number,action:'resend'|'revoke') { setPending(true); const response=await fetch(`/api/customer/organizations/${orgId}/invitations/${id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,version})}); const result=await response.json(); setPending(false); setStatus(response.ok?(action==='resend'?'New invitation link sent.':'Invitation revoked.'):`Could not update invitation: ${result.error||'unavailable'}`); if(response.ok)router.refresh(); }
  async function memberAction(id:string,action:'change_role'|'remove',role?:string) { setPending(true); const response=await fetch(`/api/customer/organizations/${orgId}/members/${id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,role})}); const result=await response.json(); setPending(false); setStatus(response.ok?(action==='remove'?'Member access removed.':'Member role updated.'):`Could not update member: ${result.error||'unavailable'}`); if(response.ok)router.refresh(); }
  return <div className="space-y-6">
    <section className="card-surface p-5"><h2 className="text-xl font-semibold text-navy">Team members</h2><p className="mt-1 text-sm text-muted-foreground">Membership controls organization access. Profile authority still requires an active organization grant.</p><ul className="mt-4 divide-y divide-border">{members.map(member=><li key={member.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="break-all text-sm font-medium">{member.email}</p><p className="text-xs capitalize text-muted-foreground">{member.role} / Joined {new Date(member.created_at).toLocaleDateString('en-US')}</p></div>{canAdmin&&member.role!=='owner'?<div className="flex flex-wrap gap-2"><select aria-label={`Role for ${member.email}`} defaultValue={member.role} disabled={pending} onChange={event=>memberAction(member.id,'change_role',event.target.value)} className="min-h-11 rounded-lg border border-border bg-white px-3 text-sm"><option value="manager">Manager</option><option value="staff">Staff</option><option value="billing">Billing</option></select><button type="button" disabled={pending} onClick={()=>memberAction(member.id,'remove')} className="min-h-11 rounded-lg border border-destructive px-3 text-sm text-destructive">Remove</button></div>:null}</li>)}</ul></section>
    {canAdmin?<section className="card-surface p-5"><h2 className="text-xl font-semibold text-navy">Invite a member</h2><p className="mt-1 text-sm text-muted-foreground">Only owners can invite members in V1. Owner invitations and ownership transfer are not available here.</p><form action={invite} className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><input required type="email" name="email" autoComplete="email" aria-label="Email address" placeholder="person@example.com" className="min-h-11 rounded-lg border border-border px-3 text-sm"/><select name="role" aria-label="Invitation role" defaultValue="staff" className="min-h-11 rounded-lg border border-border bg-white px-3 text-sm"><option value="manager">Manager</option><option value="staff">Staff</option><option value="billing">Billing</option></select><button disabled={pending} className="min-h-11 rounded-lg bg-navy px-4 text-sm font-semibold text-white disabled:opacity-50">Send invitation</button></form></section>:null}
    <section className="card-surface p-5"><h2 className="text-xl font-semibold text-navy">Pending invitations</h2>{invitations.length?<ul className="mt-4 divide-y divide-border">{invitations.map(item=><li key={item.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="break-all text-sm font-medium">{item.invited_email_normalized}</p><p className="text-xs capitalize text-muted-foreground">{item.invited_role} / Expires {new Date(item.expires_at).toLocaleDateString('en-US')}</p></div>{canAdmin?<div className="flex flex-wrap gap-2"><button type="button" disabled={pending} onClick={()=>invitationAction(item.id,item.version,'resend')} className="min-h-11 rounded-lg border border-border px-3 text-sm">Resend</button><button type="button" disabled={pending} onClick={()=>invitationAction(item.id,item.version,'revoke')} className="min-h-11 rounded-lg border border-destructive px-3 text-sm text-destructive">Revoke</button></div>:null}</li>)}</ul>:<p className="mt-3 text-sm text-muted-foreground">No pending invitations.</p>}</section>
    <p aria-live="polite" className="text-sm text-muted-foreground">{status}</p>
  </div>;
}
