'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ANALYTICS_EVENTS } from '@/lib/analytics/events';
import { trackEvent } from '@/lib/analytics/track';

type Issue = {id:string;issue_type:string;target_record_type:string;target_record_id:string|null;explanation:string;status:string;version:number;created_at:string;customer_resolution_note:string|null;events:Array<{event_type:string;message:string|null;created_at:string}>};
const TYPES = ['WRONG_BUSINESS','WRONG_LICENSE','WRONG_LICENSE_STATUS','WRONG_ADDRESS','WRONG_CONTACT_INFORMATION','WRONG_QUALIFIER_RELATIONSHIP','WRONG_DISCIPLINE_LINK','DUPLICATE_PROFILE','BUSINESS_CLOSED_OR_CHANGED','OUTDATED_INFORMATION','OTHER_RECORD_ISSUE'];
const TARGETS = ['PROFILE','BUSINESS_IDENTITY','DBPR_CREDENTIAL','OFFICIAL_ADDRESS','QUALIFIER_RELATIONSHIP','DISCIPLINE_EVENT','TRUSTHUB_INTELLIGENCE'];
const DEFAULT_TARGET:Record<string,string> = {WRONG_BUSINESS:'BUSINESS_IDENTITY',WRONG_LICENSE:'DBPR_CREDENTIAL',WRONG_LICENSE_STATUS:'DBPR_CREDENTIAL',WRONG_ADDRESS:'OFFICIAL_ADDRESS',WRONG_CONTACT_INFORMATION:'BUSINESS_IDENTITY',WRONG_QUALIFIER_RELATIONSHIP:'QUALIFIER_RELATIONSHIP',WRONG_DISCIPLINE_LINK:'DISCIPLINE_EVENT',DUPLICATE_PROFILE:'PROFILE',BUSINESS_CLOSED_OR_CHANGED:'BUSINESS_IDENTITY',OUTDATED_INFORMATION:'PROFILE',OTHER_RECORD_ISSUE:'PROFILE'};

export function RecordIssuesPanel({profileId,credentialKey,issues}:{profileId:string;credentialKey:string;issues:Issue[]}) {
  const router=useRouter();
  const [issueType,setIssueType]=useState('OTHER_RECORD_ISSUE'),[targetType,setTargetType]=useState('PROFILE'),[targetId,setTargetId]=useState(''),[explanation,setExplanation]=useState(''),[message,setMessage]=useState(''),[status,setStatus]=useState('');
  useEffect(()=>{trackEvent(ANALYTICS_EVENTS.RECORD_ISSUE_FORM_VIEW,{hub:'contractor',profile_id:profileId});if(issues.length)trackEvent(ANALYTICS_EVENTS.RECORD_ISSUE_STATUS_VIEW,{hub:'contractor',profile_id:profileId,issue_count:issues.length});},[profileId,issues.length]);
  async function submit(){setStatus('Submitting...');const response=await fetch(`/api/customer/manage/${profileId}/record-issues`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({issueType,targetRecordType:targetType,targetRecordId:targetId,explanation})});const result=await response.json();if(!response.ok){setStatus(`Could not submit: ${result.error||'unavailable'}`);return;}trackEvent(ANALYTICS_EVENTS.RECORD_ISSUE_SUBMITTED,{hub:'contractor',profile_id:profileId,issue_type:issueType});setExplanation('');setStatus(`Submitted for review. Reference ${result.id}`);router.refresh();}
  async function act(issue:Issue,action:'withdraw'|'respond'){const response=await fetch(`/api/customer/manage/${profileId}/record-issues/${issue.id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,version:issue.version,message})});const result=await response.json();setStatus(response.ok?'Issue updated.':`Could not update: ${result.error||'unavailable'}`);if(response.ok){setMessage('');router.refresh();}}
  return <section className="card-surface space-y-5 p-5">
    <div><p className="text-xs font-semibold uppercase tracking-wider text-indigo">Layer D &middot; review request</p><h2 className="mt-1 text-xl font-semibold text-navy">Report a record issue</h2><p className="mt-1 text-sm text-muted-foreground">If you believe a public record is inaccurate, linked to the wrong business, or outdated, you can report it for review. Filing an issue does not remove or change the record automatically.</p></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">What appears wrong?<select className="mt-1 w-full rounded-lg border border-border bg-white px-3 py-2" value={issueType} onChange={event=>{const next=event.target.value,nextTarget=DEFAULT_TARGET[next];setIssueType(next);setTargetType(nextTarget);setTargetId(nextTarget==='DBPR_CREDENTIAL'?credentialKey:'');}}>{TYPES.map(value=><option key={value}>{value.replaceAll('_',' ')}</option>)}</select></label><label className="text-sm font-medium">Affected record<select className="mt-1 w-full rounded-lg border border-border bg-white px-3 py-2" value={targetType} onChange={event=>{setTargetType(event.target.value);setTargetId(event.target.value==='DBPR_CREDENTIAL'?credentialKey:'');}}>{TARGETS.map(value=><option key={value}>{value.replaceAll('_',' ')}</option>)}</select></label></div>
    <label className="block text-sm font-medium">Stable record identifier {['DBPR_CREDENTIAL','QUALIFIER_RELATIONSHIP','DISCIPLINE_EVENT'].includes(targetType)?'(required)':'(optional)'}<input className="mt-1 w-full rounded-lg border border-border px-3 py-2" maxLength={160} value={targetId} onChange={event=>setTargetId(event.target.value)} placeholder={targetType==='DBPR_CREDENTIAL'?credentialKey:'Record or source identifier'} /></label>
    <label className="block text-sm font-medium">What should TrustHub review?<textarea className="mt-1 w-full rounded-lg border border-border px-3 py-2" rows={4} minLength={20} maxLength={2000} value={explanation} onChange={event=>setExplanation(event.target.value)} /></label><button type="button" onClick={submit} className="min-h-11 rounded-lg bg-navy px-5 py-2 text-sm font-semibold text-white">Submit for review</button>
    <div><h3 className="font-semibold text-navy">Issue history</h3>{issues.length===0?<p className="mt-2 text-sm text-muted-foreground">No record issues submitted for this profile.</p>:<ul className="mt-3 space-y-3">{issues.map(issue=><li key={issue.id} className="rounded-lg border border-border p-4 text-sm"><p className="font-medium">{issue.issue_type.replaceAll('_',' ')} &middot; {issue.status.replaceAll('_',' ')}</p><p className="mt-1 break-all text-xs text-muted-foreground">Reference {issue.id} &middot; {new Date(issue.created_at).toLocaleDateString('en-US')}</p><p className="mt-2">Target: {issue.target_record_type.replaceAll('_',' ')}{issue.target_record_id?<> &middot; {issue.target_record_id}</>:null}</p><p className="mt-2 text-muted-foreground">{issue.explanation}</p>{issue.customer_resolution_note?<p className="mt-2">Review note: {issue.customer_resolution_note}</p>:null}<ul className="mt-2 text-xs text-muted-foreground">{issue.events.map((event,index)=><li key={index}>{event.event_type.replaceAll('_',' ')} &middot; {new Date(event.created_at).toLocaleString('en-US')}{event.message?<> &middot; {event.message}</>:null}</li>)}</ul>{issue.status==='OPEN'?<button type="button" onClick={()=>act(issue,'withdraw')} className="mt-3 min-h-11 rounded border border-border px-3">Withdraw issue</button>:null}{issue.status==='NEEDS_INFORMATION'?<div className="mt-3"><textarea aria-label="Additional information" className="w-full rounded border border-border p-2" maxLength={2000} value={message} onChange={event=>setMessage(event.target.value)} /><button type="button" onClick={()=>act(issue,'respond')} className="mt-2 min-h-11 rounded bg-navy px-3 text-white">Send additional information</button></div>:null}</li>)}</ul>}</div><p aria-live="polite" className="text-sm text-muted-foreground">{status}</p>
  </section>;
}
