import { NETWORK_PUBLIC_NAMES } from './registry.ts';
import { NETWORK_MANIFEST_CONTRACT, type TrustHubNetworkManifest } from './manifest.ts';

/** Ask-owned adapters from closed specialist snapshot contracts. No HTML scraping. */
export const NETWORK_MANIFEST_GENERATED_AT = '2026-08-29';

export function moveManifest(): TrustHubNetworkManifest {
  return {
    contract: NETWORK_MANIFEST_CONTRACT,
    hub: {
      id: 'move',
      name: NETWORK_PUBLIC_NAMES.move,
      domain: 'movetrusthub.com',
      description: 'FMCSA-oriented mover identity and Florida state research. Not a ranking of movers.',
      accent: '#FF5A1F',
      exploreHref: 'https://www.movetrusthub.com',
      askHref: 'https://www.movetrusthub.com',
      methodologyHref: 'https://www.movetrusthub.com/about/how-we-score-movers',
    },
    snapshot: {
      snapshotId: 'move-home-intel-v1',
      fingerprint: '3f2d144f65d5ab20bd57a1536eabf44825f18f4c8501130913c0a98a7787726e',
      generatedAt: NETWORK_MANIFEST_GENERATED_AT,
      officialAsOf: '2026-08-23',
      retrievedAt: '2026-08-29',
      adapter: 'checked_in_canonical_snapshot',
    },
    status: 'ok',
    card: {
      primaryMetricId: 'directory_profiles',
      supportingMetricIds: ['carrier_entities', 'florida_state_intel'],
      scopeChip: 'Directory cohort',
      ctaLabel: 'Explore moving intelligence',
    },
    metrics: [
      {
        id: 'directory_profiles',
        label: 'Published research profiles',
        value: 5022,
        grain: 'Consumer-visible published MoveTrustHub research profiles',
        sourceFamily: 'fmcsa-directory-cohort',
        officialAsOf: '2026-08-23',
        retrievedAt: '2026-08-29',
        limitation: 'Not the full FMCSA mover census. Publication gates apply.',
      },
      {
        id: 'carrier_entities',
        label: 'Carrier-classified profiles',
        value: 4227,
        grain: 'Published profiles with entity type Carrier',
        sourceFamily: 'fmcsa-directory-cohort',
        officialAsOf: '2026-08-23',
        retrievedAt: '2026-08-29',
        limitation: 'Carrier is a business-model fact, not a quality ranking. Broker is not worse.',
      },
      {
        id: 'florida_state_intel',
        label: 'Florida state intelligence',
        value: 'Live',
        grain: 'State research landing (not a mover count)',
        sourceFamily: 'fdacs-florida',
        officialAsOf: '2026-08-23',
        limitation: 'Florida registrations are not national mover counts.',
      },
    ],
    capabilities: [
      { id: 'identity', label: 'USDOT / MC identity', status: 'deep' },
      { id: 'credential', label: 'FMCSA authority', status: 'available' },
      { id: 'local_regulatory', label: 'Florida FDACS / county overlays', status: 'partial' },
    ],
    geographyCoverage: [
      { geographyType: 'national', capabilityLevel: 'federal_core' },
      { geographyType: 'state', geographyCode: 'FL', capabilityLevel: 'enhanced_state_intelligence' },
    ],
    sourceFamilies: [
      {
        id: 'fmcsa-directory-cohort',
        sourceOrganization: 'Federal Motor Carrier Safety Administration',
        regulatorOrAgency: 'FMCSA',
        sourceSystem: 'SAFER / FMCSA public systems',
        datasetName: 'Interstate household-goods identity used on published MoveTrustHub profiles',
        grain: 'Published research profile',
        geography: 'United States (interstate-oriented directory)',
        officialAsOf: '2026-08-23',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://safer.fmcsa.dot.gov/',
        limitation: 'Directory cohort ≠ full FMCSA census.',
        organizationKind: 'regulator',
      },
      {
        id: 'fdacs-florida',
        sourceOrganization: 'Florida Department of Agriculture and Consumer Services',
        regulatorOrAgency: 'FDACS',
        sourceSystem: 'Florida IM registration records',
        datasetName: 'Florida intrastate mover registration research',
        grain: 'State registration / research landing',
        geography: 'Florida',
        officialAsOf: '2026-08-23',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.movetrusthub.com/florida',
        limitation: 'Florida IM registration is not federal interstate authority.',
        organizationKind: 'regulator',
      },
    ],
    askCapabilities: [{ mode: 'entity', status: 'live' }],
    limitations: [
      'Headquarters is not service territory.',
      'Authority is a regulatory record, not a MoveTrustHub endorsement.',
    ],
  };
}

export function lenderManifest(): TrustHubNetworkManifest {
  return {
    contract: NETWORK_MANIFEST_CONTRACT,
    hub: {
      id: 'lender',
      name: NETWORK_PUBLIC_NAMES.lender,
      domain: 'lendertrusthub.com',
      description: 'NMLS-oriented lender research and Florida state intelligence. Not loan origination.',
      accent: '#16A34A',
      exploreHref: 'https://www.lendertrusthub.com',
      methodologyHref: 'https://www.lendertrusthub.com/methodology',
    },
    snapshot: {
      snapshotId: 'lender-intel-004-florida-public',
      generatedAt: NETWORK_MANIFEST_GENERATED_AT,
      officialAsOf: '2026-08-22',
      retrievedAt: '2026-08-29',
      adapter: 'checked_in_canonical_snapshot',
    },
    status: 'ok',
    card: {
      primaryMetricId: 'florida_public_profiles',
      supportingMetricIds: ['nmls_orientation', 'hmda_activity'],
      scopeChip: 'Florida-enhanced',
      ctaLabel: 'Explore lending intelligence',
    },
    metrics: [
      {
        id: 'florida_public_profiles',
        label: 'Florida public lender research profiles',
        value: 180,
        grain: 'Indexable Florida lender_state_company_profiles (public research routes)',
        sourceFamily: 'nmls-florida-profiles',
        officialAsOf: '2026-08-22',
        retrievedAt: '2026-08-29',
        limitation: 'Not a national lender census. Not HMDA application counts.',
      },
      {
        id: 'nmls_orientation',
        label: 'NMLS Consumer Access orientation',
        value: 'Live',
        grain: 'Research capability, not a license count',
        sourceFamily: 'nmls-consumer-access',
        officialAsOf: '2026-08-07',
        limitation: 'NMLS status can change after the latest check.',
      },
      {
        id: 'hmda_activity',
        label: 'HMDA market activity',
        value: 'Separate grain',
        grain: 'Mortgage applications/originations — not institutions',
        sourceFamily: 'hmda',
        officialAsOf: '2026-08-07',
        limitation: 'HMDA rows are not lender identities. Never summed into a network entity total.',
      },
    ],
    capabilities: [
      { id: 'identity', label: 'Institution identity', status: 'available' },
      { id: 'market_activity', label: 'HMDA activity (separate grain)', status: 'partial' },
      { id: 'licensing', label: 'NMLS context', status: 'available' },
    ],
    geographyCoverage: [
      { geographyType: 'national', capabilityLevel: 'federal_core' },
      { geographyType: 'state', geographyCode: 'FL', capabilityLevel: 'enhanced_state_intelligence' },
    ],
    sourceFamilies: [
      {
        id: 'nmls-consumer-access',
        sourceOrganization: 'Nationwide Multistate Licensing System',
        regulatorOrAgency: 'State mortgage regulators via NMLS',
        sourceSystem: 'NMLS Consumer Access',
        datasetName: 'Mortgage-related license identity',
        grain: 'License / institution identity context',
        geography: 'United States (varies by license type)',
        officialAsOf: '2026-08-07',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.nmlsconsumeraccess.org/',
        limitation: 'License status is not a rate quote or credit decision.',
        organizationKind: 'standards_body',
      },
      {
        id: 'nmls-florida-profiles',
        sourceOrganization: 'Lender Trust Hub Florida research overlay',
        regulatorOrAgency: 'Florida / NMLS-oriented public records',
        sourceSystem: 'LenderTrustHub Florida public profiles',
        datasetName: 'Florida public lender research profiles',
        grain: 'Published Florida research profile',
        geography: 'Florida',
        officialAsOf: '2026-08-22',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.lendertrusthub.com',
        limitation: 'Not LPI row counts and not national identities.',
        organizationKind: 'publisher',
      },
      {
        id: 'hmda',
        sourceOrganization: 'Federal Financial Institutions Examination Council',
        regulatorOrAgency: 'CFPB / FFIEC',
        sourceSystem: 'HMDA publications',
        datasetName: 'Home Mortgage Disclosure Act loan-application register activity',
        grain: 'Application / origination observation',
        geography: 'United States (property location)',
        officialAsOf: '2026-08-07',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://ffiec.cfpb.gov/',
        limitation: 'Property county is not lender headquarters.',
        organizationKind: 'regulator',
      },
      {
        id: 'cfpb-complaints',
        sourceOrganization: 'Consumer Financial Protection Bureau',
        regulatorOrAgency: 'CFPB',
        sourceSystem: 'Consumer Complaint Database',
        datasetName: 'Mortgage-related complaint patterns',
        grain: 'Complaint observation',
        geography: 'United States',
        officialAsOf: '2026-08-07',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.consumerfinance.gov/data-research/consumer-complaints/',
        limitation: 'Complaints are not verdicts. Absence of complaints is not a clean record.',
        organizationKind: 'regulator',
      },
      {
        id: 'fdic',
        sourceOrganization: 'Federal Deposit Insurance Corporation',
        regulatorOrAgency: 'FDIC',
        sourceSystem: 'FDIC public institution records',
        datasetName: 'Insured depository identity context',
        grain: 'Insured institution identity',
        geography: 'United States',
        officialAsOf: '2026-08-07',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.fdic.gov/',
        limitation: 'FDIC insurance does not apply to every product a company markets.',
        organizationKind: 'regulator',
      },
    ],
    askCapabilities: [{ mode: 'entity', status: 'planned' }],
    limitations: [
      'Institution identity is not a servicer identity.',
      'Ask LenderTrustHub is not marked live in Prompt 1.',
    ],
  };
}

export function insuranceManifest(): TrustHubNetworkManifest {
  return {
    contract: NETWORK_MANIFEST_CONTRACT,
    hub: {
      id: 'insurance',
      name: NETWORK_PUBLIC_NAMES.insurance,
      domain: 'insurancetrusthub.com',
      description: 'State DOI / NAIC insurance research. Agencies, producers, and legal insurers stay separate.',
      accent: '#0D9488',
      exploreHref: 'https://www.insurancetrusthub.com',
      methodologyHref: 'https://www.insurancetrusthub.com/methodology',
    },
    snapshot: {
      snapshotId: 'insurance-doi-naic-orientation',
      generatedAt: NETWORK_MANIFEST_GENERATED_AT,
      officialAsOf: '2026-08-07',
      retrievedAt: '2026-08-29',
      adapter: 'checked_in_canonical_snapshot',
    },
    status: 'ok',
    card: {
      primaryMetricId: 'classes_kept_separate',
      supportingMetricIds: ['doi_orientation', 'publication_gate'],
      scopeChip: 'Publication gate',
      ctaLabel: 'Explore insurance intelligence',
    },
    metrics: [
      {
        id: 'classes_kept_separate',
        label: 'Research classes',
        value: 'Agency · producer · legal insurer',
        grain: 'Separate identity classes — never summed',
        sourceFamily: 'state-doi',
        officialAsOf: '2026-08-07',
        limitation: 'Do not add agencies, people, and legal insurers into one total.',
      },
      {
        id: 'doi_orientation',
        label: 'State DOI / NAIC pathways',
        value: 'Live research',
        grain: 'Capability, not a license count',
        sourceFamily: 'naic',
        officialAsOf: '2026-08-07',
        limitation: 'The state DOI is usually the authority of record.',
      },
      {
        id: 'publication_gate',
        label: 'Public profile publication',
        value: 'Gated',
        grain: 'Publication policy, not a roster count',
        sourceFamily: 'state-doi',
        officialAsOf: '2026-08-07',
        limitation: 'Missing public profiles do not mean unlicensed.',
      },
    ],
    capabilities: [
      { id: 'identity', label: 'Agency / producer / insurer identity', status: 'partial' },
      { id: 'licensing', label: 'State license context', status: 'available' },
    ],
    geographyCoverage: [{ geographyType: 'state', capabilityLevel: 'state_research' }],
    sourceFamilies: [
      {
        id: 'state-doi',
        sourceOrganization: 'State Departments of Insurance',
        regulatorOrAgency: 'State DOI',
        sourceSystem: 'State producer/agency license tools (varies)',
        datasetName: 'Producer and agency licensing context',
        grain: 'License / identity class',
        geography: 'United States (state-based)',
        officialAsOf: '2026-08-07',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://content.naic.org/state-insurance-departments',
        limitation: 'Completeness differs by state.',
        organizationKind: 'regulator',
      },
      {
        id: 'naic',
        sourceOrganization: 'National Association of Insurance Commissioners',
        sourceSystem: 'NAIC consumer resources',
        datasetName: 'Multi-state insurance coordination references',
        grain: 'Reference pathway, not a national license',
        geography: 'United States',
        officialAsOf: '2026-08-07',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://content.naic.org/',
        limitation: 'NAIC is not a substitute for the state DOI.',
        organizationKind: 'standards_body',
      },
      {
        id: 'cms-medicare-edu',
        sourceOrganization: 'Centers for Medicare & Medicaid Services',
        regulatorOrAgency: 'CMS',
        sourceSystem: 'Medicare.gov educational resources',
        datasetName: 'Medicare educational context',
        grain: 'Educational resource, not a producer roster',
        geography: 'United States',
        officialAsOf: '2026-08-07',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.medicare.gov/',
        limitation: 'Educational routing is not a CMS endorsement of an agent.',
        organizationKind: 'regulator',
      },
    ],
    askCapabilities: [{ mode: 'entity', status: 'partial' }],
    limitations: ['Insurer, agency, and producer are different regulated roles.'],
  };
}

export function contractorManifest(): TrustHubNetworkManifest {
  return {
    contract: NETWORK_MANIFEST_CONTRACT,
    hub: {
      id: 'contractor',
      name: NETWORK_PUBLIC_NAMES.contractor,
      domain: 'contractortrusthub.com',
      description: 'State licensing-board contractor research with state-specific evidence depth.',
      accent: '#0A2540',
      exploreHref: 'https://www.contractortrusthub.com',
      askHref: 'https://www.contractortrusthub.com',
    },
    snapshot: {
      snapshotId: 'contractor-intel-003-orientation',
      generatedAt: NETWORK_MANIFEST_GENERATED_AT,
      officialAsOf: '2026-08-22',
      retrievedAt: '2026-08-29',
      adapter: 'checked_in_canonical_snapshot',
    },
    status: 'ok',
    card: {
      primaryMetricId: 'board_evidence',
      supportingMetricIds: ['florida_enhanced', 'credential_not_contractor'],
      scopeChip: 'Florida-enhanced',
      ctaLabel: 'Explore contractor intelligence',
    },
    metrics: [
      {
        id: 'board_evidence',
        label: 'State licensing-board evidence',
        value: 'Multi-state, uneven depth',
        grain: 'Official-board credential / registration research',
        sourceFamily: 'state-contractor-boards',
        officialAsOf: '2026-08-22',
        limitation: 'Do not claim identical coverage in every state.',
      },
      {
        id: 'florida_enhanced',
        label: 'Florida / county overlays',
        value: 'Enhanced where published',
        grain: 'State and county regulatory overlays',
        sourceFamily: 'fl-dbpr',
        officialAsOf: '2026-08-22',
        limitation: 'Address county is not service territory.',
      },
      {
        id: 'credential_not_contractor',
        label: 'Credentials vs contractors',
        value: 'Kept separate',
        grain: 'Credential records are not a contractor headcount',
        sourceFamily: 'state-contractor-boards',
        officialAsOf: '2026-08-22',
        limitation: 'Never sum credentials into “contractors.”',
      },
    ],
    capabilities: [
      { id: 'credential', label: 'License / registration credentials', status: 'available' },
      { id: 'local_regulatory', label: 'County overlays (selected FL)', status: 'partial' },
    ],
    geographyCoverage: [
      { geographyType: 'state', capabilityLevel: 'state_research' },
      { geographyType: 'state', geographyCode: 'FL', capabilityLevel: 'enhanced_state_intelligence' },
      { geographyType: 'county', geographyCode: 'FL-MDC', capabilityLevel: 'enhanced_county_intelligence' },
    ],
    sourceFamilies: [
      {
        id: 'state-contractor-boards',
        sourceOrganization: 'State contractor licensing boards',
        regulatorOrAgency: 'State licensing boards',
        sourceSystem: 'Official board extracts (varies by state)',
        datasetName: 'Contractor license and registration evidence',
        grain: 'Credential / registration record',
        geography: 'United States (state-specific depth)',
        officialAsOf: '2026-08-22',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.contractortrusthub.com',
        limitation: 'Missing board records do not mean a clean history.',
        organizationKind: 'regulator',
      },
      {
        id: 'fl-dbpr',
        sourceOrganization: 'Florida Department of Business and Professional Regulation',
        regulatorOrAgency: 'Florida DBPR',
        sourceSystem: 'Florida license extracts used in ContractorTrustHub Florida research',
        datasetName: 'Florida contractor licensing overlays',
        grain: 'Florida credential observation',
        geography: 'Florida',
        officialAsOf: '2026-08-22',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.myfloridalicense.com/',
        limitation: 'Florida depth is not national depth.',
        organizationKind: 'regulator',
      },
    ],
    askCapabilities: [{ mode: 'entity', status: 'live' }],
    limitations: ['Physical address is not service territory.'],
  };
}

export function seniorManifest(): TrustHubNetworkManifest {
  return {
    contract: NETWORK_MANIFEST_CONTRACT,
    hub: {
      id: 'senior',
      name: NETWORK_PUBLIC_NAMES.senior,
      domain: 'seniortrusthub.com',
      description: 'CMS-oriented senior care research. Nursing homes, home health, and hospice stay separate.',
      accent: '#7C3AED',
      exploreHref: 'https://www.seniortrusthub.com',
      askHref: 'https://www.seniortrusthub.com/ask',
    },
    snapshot: {
      snapshotId: 'senior-cms-class-separation',
      generatedAt: NETWORK_MANIFEST_GENERATED_AT,
      officialAsOf: '2026-08-10',
      retrievedAt: '2026-08-29',
      adapter: 'checked_in_canonical_snapshot',
    },
    status: 'ok',
    card: {
      primaryMetricId: 'three_classes',
      supportingMetricIds: ['cms_orientation', 'ownership_inspection'],
      scopeChip: 'Three provider classes',
      ctaLabel: 'Explore senior-care intelligence',
    },
    metrics: [
      {
        id: 'three_classes',
        label: 'CMS provider classes',
        value: 'Nursing homes · Home health · Hospice',
        grain: 'Separate CMS provider classes — never one “senior providers” total',
        sourceFamily: 'cms-care-compare',
        officialAsOf: '2026-08-10',
        limitation: 'Do not add these classes together.',
      },
      {
        id: 'cms_orientation',
        label: 'CMS government-sourced research',
        value: 'Live orientation',
        grain: 'Research capability, not a placement inventory',
        sourceFamily: 'cms-care-compare',
        officialAsOf: '2026-08-10',
        limitation: 'Not a referral or placement agency.',
      },
      {
        id: 'ownership_inspection',
        label: 'Ownership / inspection evidence',
        value: 'Where CMS publishes it',
        grain: 'Ownership and inspection observations, not a quality score from Ask',
        sourceFamily: 'cms-care-compare',
        officialAsOf: '2026-08-10',
        limitation: 'Facility is not the same as the ownership organization.',
      },
    ],
    capabilities: [
      { id: 'identity', label: 'Facility identity (CCN)', status: 'available' },
      { id: 'ownership', label: 'Ownership context', status: 'partial' },
      { id: 'inspection', label: 'Inspection / deficiency evidence', status: 'partial' },
      { id: 'staffing_quality', label: 'CMS quality measures', status: 'partial' },
    ],
    geographyCoverage: [{ geographyType: 'national', capabilityLevel: 'federal_core' }],
    sourceFamilies: [
      {
        id: 'cms-care-compare',
        sourceOrganization: 'Centers for Medicare & Medicaid Services',
        regulatorOrAgency: 'CMS',
        sourceSystem: 'CMS Care Compare / provider information files',
        datasetName: 'Nursing home, home health, and hospice public research files',
        grain: 'Provider-class record (kept separate by class)',
        geography: 'United States',
        officialAsOf: '2026-08-10',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://www.medicare.gov/care-compare/',
        limitation: 'CMS class files are not one senior-care inventory.',
        organizationKind: 'regulator',
      },
    ],
    askCapabilities: [
      { mode: 'entity', status: 'live' },
      { mode: 'identifier', status: 'live' },
      { mode: 'count', status: 'live' },
      { mode: 'aggregate', status: 'live' },
      { mode: 'comparison', status: 'live' },
      { mode: 'evidence', status: 'live' },
      { mode: 'definition', status: 'live' },
      { mode: 'fail_closed', status: 'live' },
    ],
    limitations: [
      'Never publish a combined senior class total.',
      'Home Health county filtering is not supported. CHOW is Nursing Home only. Hospice has no overall CMS star.',
      'Provider address/office geography is not service area. CMS ratings are not TrustHub recommendations.',
    ],
  };
}

export function investorManifest(): TrustHubNetworkManifest {
  return {
    contract: NETWORK_MANIFEST_CONTRACT,
    hub: {
      id: 'investor',
      name: NETWORK_PUBLIC_NAMES.investor,
      domain: 'investortrusthub.com',
      description: 'SEC/IARD investment-firm research. Not stock advice or performance ranking.',
      accent: '#001F52',
      exploreHref: 'https://www.investortrusthub.com',
      askHref: 'https://www.investortrusthub.com/ask',
    },
    snapshot: {
      snapshotId: 'inv-home-003',
      generatedAt: NETWORK_MANIFEST_GENERATED_AT,
      officialAsOf: '2026-08-29',
      retrievedAt: '2026-08-29',
      adapter: 'checked_in_canonical_snapshot',
    },
    status: 'ok',
    card: {
      primaryMetricId: 'sec_iard_roster',
      supportingMetricIds: ['ria_count', 'era_count'],
      scopeChip: 'SEC/IARD roster',
      ctaLabel: 'Explore adviser intelligence',
    },
    metrics: [
      {
        id: 'sec_iard_roster',
        label: 'SEC/IARD roster firms',
        value: 23622,
        grain: 'Firm registrations on the InvestorTrustHub SEC/IARD roster universe',
        sourceFamily: 'sec-iard-adv',
        officialAsOf: '2026-08-29',
        retrievedAt: '2026-08-29',
        limitation: 'Roster firms are not a performance ranking. Not FINRA people coverage.',
      },
      {
        id: 'ria_count',
        label: 'RIA firms',
        value: 17018,
        grain: 'Registered investment adviser firms in the same roster universe',
        sourceFamily: 'sec-iard-adv',
        officialAsOf: '2026-08-29',
        retrievedAt: '2026-08-29',
        limitation: 'RIA is not ERA. Do not treat extra observations as extra firms.',
      },
      {
        id: 'era_count',
        label: 'ERA firms',
        value: 6604,
        grain: 'Exempt reporting adviser firms in the same roster universe',
        sourceFamily: 'sec-iard-adv',
        officialAsOf: '2026-08-29',
        retrievedAt: '2026-08-29',
        limitation: 'ERA is a classification, not a quality grade. 17018+6604=23622.',
      },
    ],
    capabilities: [
      { id: 'identity', label: 'Firm identity (IARD)', status: 'deep' },
      { id: 'compensation', label: 'Form ADV compensation/structure', status: 'available' },
      { id: 'registration', label: 'RIA / ERA classification', status: 'available' },
    ],
    geographyCoverage: [{ geographyType: 'national', capabilityLevel: 'federal_core' }],
    sourceFamilies: [
      {
        id: 'sec-iard-adv',
        sourceOrganization: 'U.S. Securities and Exchange Commission',
        regulatorOrAgency: 'SEC',
        sourceSystem: 'IARD / Form ADV publications',
        datasetName: 'Investment adviser firm roster and Form ADV observations',
        grain: 'Firm registration (roster) vs ADV observation (separate)',
        geography: 'United States',
        officialAsOf: '2026-08-29',
        retrievedAt: '2026-08-29',
        publicSourceUrl: 'https://adviserinfo.sec.gov/',
        limitation: 'Principal office is not necessarily client geography. ADV observations are not extra firms.',
        organizationKind: 'regulator',
      },
    ],
    askCapabilities: [
      { mode: 'entity', status: 'live' },
      { mode: 'identifier', status: 'live' },
      { mode: 'count', status: 'live' },
      { mode: 'aggregate', status: 'live' },
      { mode: 'comparison', status: 'live' },
      { mode: 'evidence', status: 'live' },
      { mode: 'definition', status: 'live' },
      { mode: 'fail_closed', status: 'live' },
    ],
    limitations: [
      'Not personalized investment advice.',
      'RIA is not ERA. Principal office is not client geography. RAUM is not performance. Item 5.E is not a fee amount.',
      'Ownership is confidence-gated. Disclosures are not an enforcement census.',
    ],
  };
}

export function allHubManifests(): TrustHubNetworkManifest[] {
  return [
    moveManifest(),
    lenderManifest(),
    insuranceManifest(),
    contractorManifest(),
    seniorManifest(),
    investorManifest(),
  ];
}
