import type { AskResearchIntent, AskResearchPlan } from './research-planner.ts';
import type { AskExecutionScope } from './research-scope.ts';
import { CANONICAL_ORIGINS, type SpecialistHubId } from './registry.ts';

export const RESEARCH_DESTINATION_VERSION = 'ask-research-destinations-v1' as const;
export type ResearchDestinationType = 'VERIFY'|'TOOL'|'COUNTY_RESEARCH'|'STATE_RESEARCH'|'CLASS_RESEARCH'|'HUB_HOME'|'OFFICIAL_SOURCE';
export type ResearchDestination = {id:string;hub:SpecialistHubId;label:string;type:ResearchDestinationType;href:string;capability:string;intents:AskResearchIntent[];entityClasses?:string[];geography?:{stateCode:string;county?:string};publication:'PUBLIC'|'RESTRICTED';priority:number;owner:'TRUSTHUB'|'OFFICIAL';description:string;caveat?:string;conciergeAllowed:boolean;guidedAllowed:boolean};

const d=(row:ResearchDestination)=>row;
export const RESEARCH_DESTINATIONS:readonly ResearchDestination[]=[
 d({id:'move.verify_dot',hub:'move',label:'Verify a USDOT or MC',type:'VERIFY',href:'https://www.movetrusthub.com/verify-dot',capability:'moving_authority_verification',intents:['HOW_TO','IDENTIFIER_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY','COHORT_BROWSE'],publication:'PUBLIC',priority:20,owner:'TRUSTHUB',description:'Research FMCSA identity and authority evidence.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'move.companies',hub:'move',label:'Research moving companies',type:'CLASS_RESEARCH',href:'https://www.movetrusthub.com/companies',capability:'recorded_headquarters_directory',intents:['COHORT_BROWSE','EXPLAINER'],entityClasses:['mover'],publication:'PUBLIC',priority:50,owner:'TRUSTHUB',description:'Browse recorded company evidence; recorded location is not service territory.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'move.florida',hub:'move',label:'Explore Florida moving research',type:'STATE_RESEARCH',href:'https://www.movetrusthub.com/florida',capability:'florida_recorded_location',intents:['COHORT_BROWSE'],geography:{stateCode:'FL'},publication:'PUBLIC',priority:40,owner:'TRUSTHUB',description:'Florida recorded-headquarters research.',caveat:'Recorded headquarters does not prove service availability.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'move.home',hub:'move',label:'Open MoveTrustHub',type:'HUB_HOME',href:CANONICAL_ORIGINS.move,capability:'hub_home',intents:['COMPARE','RECOMMENDATION_REQUEST','MULTI_HUB_JOURNEY'],publication:'PUBLIC',priority:90,owner:'TRUSTHUB',description:'Move research homepage.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'lender.loan_estimate_analyzer',hub:'lender',label:'Analyze your Loan Estimate',type:'TOOL',href:'https://www.lendertrusthub.com/tools/loan-estimate-analyzer',capability:'loan_estimate_analysis',intents:['HOW_TO','EXPLAINER'],publication:'PUBLIC',priority:20,owner:'TRUSTHUB',description:'Review Loan Estimate fields beyond the interest rate.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'lender.research',hub:'lender',label:'Research a lender or NMLS ID',type:'VERIFY',href:'https://www.lendertrusthub.com/ask',capability:'lender_identity_research',intents:['HOW_TO','IDENTIFIER_LOOKUP','ENTITY_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY'],publication:'PUBLIC',priority:25,owner:'TRUSTHUB',description:'Research a lender name, NMLS ID, or LEI.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'lender.florida',hub:'lender',label:'Explore Florida mortgage research',type:'STATE_RESEARCH',href:'https://www.lendertrusthub.com/florida',capability:'hmda_property_geography',intents:['COHORT_BROWSE'],geography:{stateCode:'FL'},publication:'PUBLIC',priority:40,owner:'TRUSTHUB',description:'HMDA property-market evidence, not headquarters or licensing.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'insurance.florida',hub:'insurance',label:'Explore Florida insurance research',type:'STATE_RESEARCH',href:'https://www.insurancetrusthub.com/florida',capability:'florida_credential_research',intents:['COHORT_BROWSE','EXPLAINER'],geography:{stateCode:'FL'},publication:'PUBLIC',priority:40,owner:'TRUSTHUB',description:'Florida agency and legal-insurer credential research.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'insurance.research',hub:'insurance',label:'Research an NPN, NAIC code, agency, or insurer',type:'VERIFY',href:'https://www.insurancetrusthub.com/ask',capability:'insurance_identity_research',intents:['IDENTIFIER_LOOKUP','ENTITY_LOOKUP'],publication:'PUBLIC',priority:25,owner:'TRUSTHUB',description:'Research published insurance identities. Mass individual-producer profiles are restricted.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'contractor.broward',hub:'contractor',label:'Explore Broward credential research',type:'COUNTY_RESEARCH',href:'https://www.contractortrusthub.com/florida/broward',capability:'broward_contractor_credentials',intents:['COHORT_BROWSE'],entityClasses:['roofing_contractor','contractor'],geography:{stateCode:'FL',county:'Broward'},publication:'PUBLIC',priority:30,owner:'TRUSTHUB',description:'Broward County credential-source research.',caveat:'Current does not mean good standing or endorsement.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'contractor.verify',hub:'contractor',label:'Verify a contractor credential',type:'VERIFY',href:'https://www.contractortrusthub.com/verify',capability:'contractor_verification',intents:['HOW_TO','ENTITY_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY','IDENTIFIER_LOOKUP','EXPLAINER'],publication:'PUBLIC',priority:20,owner:'TRUSTHUB',description:'Research a contractor name or credential.',caveat:'Current does not mean good standing.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'contractor.florida',hub:'contractor',label:'Explore Florida contractor research',type:'STATE_RESEARCH',href:'https://www.contractortrusthub.com/florida',capability:'florida_contractor_credentials',intents:['COHORT_BROWSE'],geography:{stateCode:'FL'},publication:'PUBLIC',priority:40,owner:'TRUSTHUB',description:'Florida credential research.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'senior.search',hub:'senior',label:'Search senior-care providers',type:'CLASS_RESEARCH',href:'https://www.seniortrusthub.com/search',capability:'provider_search',intents:['HOW_TO','EXPLAINER','COHORT_BROWSE','ENTITY_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY','IDENTIFIER_LOOKUP'],entityClasses:['nursing_home','home_health','hospice'],publication:'PUBLIC',priority:25,owner:'TRUSTHUB',description:'Search source-backed provider records.',caveat:'Office geography does not establish service availability.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'senior.florida',hub:'senior',label:'Explore Florida senior-care research',type:'STATE_RESEARCH',href:'https://www.seniortrusthub.com/florida',capability:'florida_provider_research',intents:['COHORT_BROWSE','EXPLAINER'],geography:{stateCode:'FL'},publication:'PUBLIC',priority:40,owner:'TRUSTHUB',description:'Florida provider research using source-native evidence.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'investor.firms',hub:'investor',label:'Research investment adviser firms',type:'CLASS_RESEARCH',href:'https://www.investortrusthub.com/firms',capability:'firm_research',intents:['HOW_TO','EXPLAINER','COHORT_BROWSE','ENTITY_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY','IDENTIFIER_LOOKUP'],publication:'PUBLIC',priority:25,owner:'TRUSTHUB',description:'Research published firm identities and Form ADV evidence.',caveat:'Registered does not mean recommended.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'official.fmcsa',hub:'move',label:'Official source — FMCSA',type:'OFFICIAL_SOURCE',href:'https://www.fmcsa.dot.gov/protect-your-move/search-mover',capability:'official_mover_lookup',intents:['HOW_TO','IDENTIFIER_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY'],publication:'PUBLIC',priority:60,owner:'OFFICIAL',description:'FMCSA mover search.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'official.nmls',hub:'lender',label:'Official source — NMLS Consumer Access',type:'OFFICIAL_SOURCE',href:'https://www.nmlsconsumeraccess.org/',capability:'official_nmls_lookup',intents:['HOW_TO','IDENTIFIER_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY'],publication:'PUBLIC',priority:60,owner:'OFFICIAL',description:'Official NMLS consumer lookup.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'official.cms',hub:'senior',label:'Official source — CMS Care Compare',type:'OFFICIAL_SOURCE',href:'https://www.medicare.gov/care-compare/',capability:'official_cms_provider_lookup',intents:['HOW_TO','EXPLAINER','ENTITY_LOOKUP_MISSING_IDENTITY'],publication:'PUBLIC',priority:60,owner:'OFFICIAL',description:'CMS provider and rating evidence.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'official.iapd',hub:'investor',label:'Official source — IAPD',type:'OFFICIAL_SOURCE',href:'https://adviserinfo.sec.gov/',capability:'official_adviser_lookup',intents:['HOW_TO','EXPLAINER','IDENTIFIER_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY'],publication:'PUBLIC',priority:60,owner:'OFFICIAL',description:'SEC Investment Adviser Public Disclosure.',conciergeAllowed:true,guidedAllowed:true}),
 d({id:'official.insurance_departments',hub:'insurance',label:'Official source — state insurance department',type:'OFFICIAL_SOURCE',href:'https://content.naic.org/state-insurance-departments',capability:'official_producer_lookup',intents:['HOW_TO','ENTITY_LOOKUP_MISSING_IDENTITY','IDENTIFIER_LOOKUP'],publication:'PUBLIC',priority:60,owner:'OFFICIAL',description:'Choose the applicable official state insurance department and its license lookup.',conciergeAllowed:true,guidedAllowed:true}),
 ...(['lender','insurance','contractor','senior','investor'] as const).map(hub=>d({id:`${hub}.home`,hub,label:`Open ${hub==='senior'?'SeniorTrustHub':hub==='investor'?'InvestorTrustHub':`${hub[0].toUpperCase()}${hub.slice(1)}TrustHub`}`,type:'HUB_HOME',href:CANONICAL_ORIGINS[hub],capability:'hub_home',intents:['IDENTIFIER_LOOKUP','ENTITY_LOOKUP','ENTITY_LOOKUP_MISSING_IDENTITY','COHORT_BROWSE','HOW_TO','EXPLAINER','COMPARE','RECOMMENDATION_REQUEST','MULTI_HUB_JOURNEY'],publication:'PUBLIC',priority:90,owner:'TRUSTHUB',description:'Verified specialist research homepage.',conciergeAllowed:true,guidedAllowed:true})),
];

export function validateResearchDestinationRegistry(rows:readonly ResearchDestination[]=RESEARCH_DESTINATIONS):string[]{const errors:string[]=[];const ids=new Set<string>();for(const row of rows){if(ids.has(row.id))errors.push(`duplicate:${row.id}`);ids.add(row.id);let url:URL;try{url=new URL(row.href)}catch{errors.push(`invalid_url:${row.id}`);continue}if(/localhost|vercel\.app$/i.test(url.hostname))errors.push(`nonproduction:${row.id}`);if(row.owner==='TRUSTHUB'&&url.origin!==new URL(CANONICAL_ORIGINS[row.hub]).origin)errors.push(`wrong_origin:${row.id}`);if(row.owner==='OFFICIAL'&&!row.id.startsWith('official.'))errors.push(`official_not_allowlisted:${row.id}`);if(row.type==='COUNTY_RESEARCH'&&!row.geography?.county)errors.push(`county_missing:${row.id}`);if(row.type==='STATE_RESEARCH'&&!row.geography?.stateCode)errors.push(`state_missing:${row.id}`);if(/\/(firm|companies|contractors|lender|facility)\//.test(url.pathname))errors.push(`entity_pattern:${row.id}`)}return errors}

export function resolveResearchDestinations(input:{researchPlan:AskResearchPlan;executionScope?:AskExecutionScope;limit?:number}):ResearchDestination[]{const {researchPlan:plan,executionScope:scope}=input;if(!plan.primaryHub)return[];const geo=scope?.executionGeography;const county=geo?.county;const state=geo?.stateCode;const rows=RESEARCH_DESTINATIONS.filter(row=>row.hub===plan.primaryHub&&row.intents.includes(plan.intent)&&row.publication==='PUBLIC').filter(row=>{if(row.geography?.county)return row.geography.county===county&&row.geography.stateCode===state;if(row.geography?.stateCode)return row.geography.stateCode===state;return true}).filter(row=>!(plan.primaryHub==='insurance'&&plan.entityClass?.id==='insurance_producer'&&row.owner==='TRUSTHUB')).sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id));return rows.slice(0,input.limit??3)}

export function conciergeDestinationContext(plan:AskResearchPlan,scope:AskExecutionScope):string{const rows=resolveResearchDestinations({researchPlan:plan,executionScope:scope,limit:3});return ['VERIFIED ROUTES — EXHAUSTIVE URL ALLOWLIST (mention no URL not listed here):',...rows.map(row=>`- ${row.label}: ${row.href} (${row.description}${row.caveat?` ${row.caveat}`:''})`),'For an ordinary question, the complete response MUST be 600–1,200 characters. Give a direct answer, the best verified next action, an official source when useful, one caveat, and at most one refinement question. No long checklist. TrustHub evidence does not rank, endorse, or establish good standing.'].join('\n')}
