import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {PGlite} from '@electric-sql/pglite';
import {applyCustomerMigrations,enableAppRole} from '../customer/migrate.ts';
import type {SqlClient} from '../customer/sql.ts';
import {validateProductEventV1} from './contracts/product-event-v1.ts';
import {readFounderDashboard} from './founder-metrics.ts';

function asSql(db:PGlite):SqlClient{return{async query<T extends Record<string,unknown>>(text:string,params?:unknown[]){const r=await db.query(text,params??[]);return{rows:(r.rows??[])as T[]}},async exec(text:string){await db.exec(text)}}}
async function boot(){const db=new PGlite(),sql=asSql(db);await applyCustomerMigrations(sql);await db.query('BEGIN');await enableAppRole(sql);return{db,sql}}
const base={schema_version:'product_event.v1',event_id:'11111111-1111-4111-8111-111111111111',event_name:'search_terminal_outcome',occurred_at:'2026-09-09T15:00:00Z',surface:'ASK_SSR',hub:'ask',route_family:'/ask',terminal_outcome:'RESULTS',result_count_bucket:'2-10'} as const;

test('Migration 012 creates a server-only typed event store and activation epoch',async()=>{const{db,sql}=await boot();const table=(await sql.query<{relrowsecurity:boolean;relforcerowsecurity:boolean}>(`SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname='ath_product_events'`)).rows[0];assert.equal(table.relrowsecurity,true);assert.equal(table.relforcerowsecurity,true);assert.equal((await sql.query(`SELECT 1 FROM ath_product_events WHERE event_name='telemetry_store_activated'`)).rows.length,1);const migration=readFileSync('schema/migrations/012_ath_product_events.sql','utf8');for(const index of ['occurred_idx','name_time_idx','hub_time_idx','terminal_time_idx','campaign_time_idx'])assert.match(migration,new RegExp(index));assert.match(migration,/REVOKE ALL ON TABLE ath_product_events FROM PUBLIC/);assert.doesNotMatch(migration,/\b(metadata|raw_query|email|token|private_note|private_decision)\s+(JSONB?|TEXT|VARCHAR)/i);await db.close()});
test('product_event.v1 validates exact terminal outcomes and rejects prohibited data',()=>{assert.equal(validateProductEventV1(base).ok,true);for(const outcome of ['RESULTS','CLARIFICATION','FAIL_CLOSED_WITH_ACTION','FAIL_CLOSED_DEAD_END','ERROR'])assert.equal(validateProductEventV1({...base,terminal_outcome:outcome}).ok,true);assert.equal(validateProductEventV1({...base,terminal_outcome:'SUCCESS'}).ok,false);assert.equal(validateProductEventV1({...base,schema_version:'product_event.v2'}).ok,false);for(const key of ['raw_query','email','auth_token','private_note','private_decision','service_role_key'])assert.equal(validateProductEventV1({...base,[key]:'forbidden'}).ok,false)});
test('event id is idempotent and does not double count',async()=>{const{db,sql}=await boot();const insert=`INSERT INTO ath_product_events(schema_version,event_id,event_name,occurred_at,surface,hub,route_family,terminal_outcome,result_count_bucket)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(event_id) DO NOTHING`;const p=[base.schema_version,base.event_id,base.event_name,base.occurred_at,base.surface,base.hub,base.route_family,base.terminal_outcome,base.result_count_bucket];await sql.query(insert,p);await sql.query(insert,p);assert.equal((await sql.query(`SELECT 1 FROM ath_product_events WHERE event_id=$1`,[base.event_id])).rows.length,1);await db.close()});
test('frozen V1 bounded string event IDs persist',async()=>{const{db,sql}=await boot();await sql.query(`INSERT INTO ath_product_events(schema_version,event_id,event_name,occurred_at,surface,hub)VALUES('product_event.v1','evt_1','contract_test',now(),'TEST','ask')`);assert.equal((await sql.query(`SELECT 1 FROM ath_product_events WHERE event_id='evt_1'`)).rows.length,1);await db.close()});
test('Search read model preserves all outcomes, windows, filters and LIVE zero semantics',async()=>{const{db,sql}=await boot();for(const [i,outcome] of ['RESULTS','CLARIFICATION','FAIL_CLOSED_WITH_ACTION','FAIL_CLOSED_DEAD_END','ERROR'].entries())await sql.query(`INSERT INTO ath_product_events(schema_version,event_id,event_name,occurred_at,surface,hub,route_family,intent,terminal_outcome,duration_ms,result_count_bucket)VALUES('product_event.v1',$1,'search_terminal_outcome',now(),'ASK_SSR',$2,'/ask',$3,$4,$5,$6)`,[`10000000-0000-4000-8000-00000000001${i}`,'lender','IDENTITY',outcome,100+i*100,outcome==='RESULTS'?'2-10':'0']);const all=await readFounderDashboard(sql,{window:'7D'});assert.deepEqual(all.searchOutcomes.map(x=>x.count),[1,1,1,1,1]);assert.equal(all.metrics.find(x=>x.key==='search_dead_end_rate')?.status,'LIVE');const filtered=await readFounderDashboard(sql,{window:'TODAY',hub:'lender',intent:'IDENTITY'});assert.equal(filtered.searchOutcomes.reduce((n,x)=>n+x.count,0),5);const none=await readFounderDashboard(sql,{window:'30D',hub:'senior'});assert.equal(none.metrics.find(x=>x.key==='search_results_rate')?.displayValue,'0%');assert.equal(none.metrics.find(x=>x.key==='search_results_rate')?.status,'LIVE');await db.close()});
test('unavailable consumer and business activation metrics never render zero',async()=>{const{db,sql}=await boot();const view=await readFounderDashboard(sql,{window:'7D'});for(const key of ['research_sessions','save_watch','activated_consumers','alert_return','business_activation','business_30d_active']){const metric=view.metrics.find(x=>x.key===key)!;assert.equal(metric.value,null);assert.ok(['UNAVAILABLE','NOT_INSTRUMENTED'].includes(metric.status));assert.doesNotMatch(metric.displayValue,/^0/)}await db.close()});
test('browser ingestion is allowlisted and cannot import privileged server modules',()=>{const route=readFileSync('app/api/product-events/route.ts','utf8'),track=readFileSync('lib/analytics/track.ts','utf8'),page=readFileSync('app/admin/page.tsx','utf8');assert.match(route,/acceptClientProductEvent/);assert.match(track,/FIRST_PARTY_EVENTS/);assert.doesNotMatch(track,/customer\/db|control-plane\/product-events|service.role|DATABASE_URL/i);assert.match(page,/require\(t,'ADMIN_VIEW'\)/);assert.doesNotMatch(page,/raw query|private_note|private_decision/i)});
test('Search persistence is fail-open and does not alter routing or Vercel Analytics',()=>{const recorder=readFileSync('lib/control-plane/product-events.ts','utf8'),ask=readFileSync('app/ask/page.tsx','utf8'),track=readFileSync('lib/analytics/track.ts','utf8');assert.match(recorder,/catch \(error\)[\s\S]*product_event_persist_failed/);assert.match(ask,/buildAskResearchRoute\(query\)/);assert.match(track,/track\(name, cleaned\)/);assert.match(track,/\.catch\(\(\) => undefined\)/)});
