import 'server-only';
import type {SqlClient} from '@/lib/customer/sql';
import type {CapabilityHealthV1} from './contracts/capability-health-v1';
import {validateCapabilityHealthV1} from './contracts/capability-health-v1';
import {NETWORK_CAPABILITIES,capabilityByKey} from './capability-registry';
import type {AdminSecurityService,AdminRequestContext} from './security';

export async function recordHealthObservation(sql:SqlClient,event:CapabilityHealthV1){const valid=validateCapabilityHealthV1(event);if(!valid.ok)throw new Error(`invalid_capability_health:${valid.errors.join(',')}`);await sql.query(`INSERT INTO ath_data_health_observations(schema_version,observation_id,capability_key,hub,status,reason_code,checked_at,last_success_at,last_failure_at,source_as_of,retrieved_at,snapshot_as_of,accepted_at,generated_at,published_at,records_observed,previous_records_observed,build_id,contract_version,evidence_ref,observed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) ON CONFLICT(observation_id) DO NOTHING`,[event.schema_version,event.observation_id,event.capability_key,event.hub,event.status,event.reason_code,event.checked_at,event.last_success_at??null,event.last_failure_at??null,event.source_as_of??null,event.retrieved_at??null,event.snapshot_as_of??null,event.accepted_at??null,event.generated_at??null,event.published_at??null,event.records_observed??null,event.previous_records_observed??null,event.build_id??null,event.contract_version??null,event.evidence_ref,event.observed_by]);}

export async function seedCapabilityRegistry(sql:SqlClient){for(const d of NETWORK_CAPABILITIES)await sql.query(`INSERT INTO ath_data_capabilities(capability_key,hub,category,source_system,source_dataset,jurisdiction,profile_class,criticality,owner_name,expected_check_minutes,expected_freshness_minutes,publication_expected,monitoring_expected,health_adapter_type,documentation_ref) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(capability_key) DO UPDATE SET hub=EXCLUDED.hub,category=EXCLUDED.category,source_system=EXCLUDED.source_system,source_dataset=EXCLUDED.source_dataset,jurisdiction=EXCLUDED.jurisdiction,profile_class=EXCLUDED.profile_class,criticality=EXCLUDED.criticality,owner_name=EXCLUDED.owner_name,expected_check_minutes=EXCLUDED.expected_check_minutes,expected_freshness_minutes=EXCLUDED.expected_freshness_minutes,publication_expected=EXCLUDED.publication_expected,monitoring_expected=EXCLUDED.monitoring_expected,health_adapter_type=EXCLUDED.health_adapter_type,documentation_ref=EXCLUDED.documentation_ref,updated_at=now()`,[d.key,d.hub,d.category,d.sourceSystem,d.sourceDataset,d.jurisdiction,d.profileClass,d.criticality,d.owner,d.checkCadenceMinutes,d.freshnessMinutes,d.publicationExpected,d.monitoringExpected,d.adapter,d.reference]);}

export async function readDataOperations(sql:SqlClient,filters:{hub?:string;status?:string;category?:string}={}){await seedCapabilityRegistry(sql);const params:unknown[]=[];const where:string[]=[];for(const [column,value] of [['c.hub',filters.hub],['latest.status',filters.status],['c.category',filters.category]] as const)if(value){params.push(value);where.push(`${column}=$${params.length}`)}const rows=(await sql.query<Record<string,unknown>>(`SELECT c.*,COALESCE(latest.status,'UNKNOWN') status,COALESCE(latest.reason_code,'HEALTH_ADAPTER_NOT_INSTRUMENTED') reason_code,latest.checked_at::text,latest.last_success_at::text,latest.last_failure_at::text,latest.source_as_of::text,latest.retrieved_at::text,latest.snapshot_as_of::text,latest.accepted_at::text,latest.generated_at::text,latest.published_at::text,latest.records_observed,latest.evidence_ref,(SELECT count(*)::int FROM ath_data_incidents i WHERE i.capability_key=c.capability_key AND i.status IN('OPEN','ACKNOWLEDGED')) open_incidents FROM ath_data_capabilities c LEFT JOIN LATERAL(SELECT * FROM ath_data_health_observations o WHERE o.capability_key=c.capability_key ORDER BY checked_at DESC LIMIT 1)latest ON true ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY CASE COALESCE(latest.status,'UNKNOWN') WHEN 'DEGRADED' THEN 0 WHEN 'DELAYED' THEN 1 WHEN 'UNKNOWN' THEN 2 ELSE 3 END,c.hub,c.capability_key`,params)).rows;
 const alerts=(await sql.query<Record<string,unknown>>(`SELECT (SELECT count(*)::int FROM ath_monitoring_subscriptions WHERE enabled) active_subscriptions,(SELECT count(*)::int FROM ath_regulatory_change_events WHERE received_at>=now()-interval '30 days') events_30d,(SELECT count(*)::int FROM ath_notifications WHERE monitoring_event_id IS NOT NULL AND created_at>=now()-interval '30 days') notifications_30d,(SELECT count(*)::int FROM ath_notifications WHERE monitoring_event_id IS NOT NULL AND read_at IS NULL) unread,(SELECT count(*)::int FROM ath_notification_deliveries WHERE status='PENDING') pending,(SELECT count(*)::int FROM ath_notification_deliveries WHERE status='FAILED') failed,(SELECT min(created_at)::text FROM ath_notification_deliveries WHERE status='PENDING') oldest_pending,(SELECT count(DISTINCT s.hub_profile_id)::int FROM ath_monitoring_subscriptions s WHERE s.enabled) profiles_impacted,(SELECT count(DISTINCT s.org_id)::int FROM ath_monitoring_subscriptions s WHERE s.enabled) organizations_impacted`)).rows[0];
 const incidents=(await sql.query<Record<string,unknown>>(`SELECT incident_id::text,capability_key,incident_type,severity,status,reason_code,first_seen::text,last_seen::text,occurrence_count,acknowledged_at::text,resolved_at::text FROM ath_data_incidents WHERE status<>'RESOLVED' ORDER BY CASE severity WHEN 'P0' THEN 0 WHEN 'P1' THEN 1 WHEN 'P2' THEN 2 ELSE 3 END,last_seen DESC`)).rows;
 return{generatedAt:new Date().toISOString(),capabilities:rows,alerts,incidents,consumerBlastRadius:'UNKNOWN' as const};}
export async function readDataPulse(sql:SqlClient){return(await sql.query<Record<string,unknown>>(`WITH latest AS(SELECT DISTINCT ON(capability_key) capability_key,status FROM ath_data_health_observations ORDER BY capability_key,checked_at DESC) SELECT count(*)FILTER(WHERE l.status='CURRENT' AND c.criticality='CRITICAL')::int current_critical,count(*)FILTER(WHERE l.status='DELAYED')::int delayed,count(*)FILTER(WHERE l.status='DEGRADED')::int degraded,count(*)FILTER(WHERE COALESCE(l.status,'UNKNOWN')='UNKNOWN' AND c.criticality='CRITICAL')::int unknown_critical,(SELECT count(*)::int FROM ath_data_incidents WHERE status<>'RESOLVED' AND severity IN('P0','P1')) open_major,(SELECT count(*)::int FROM ath_monitoring_subscriptions WHERE enabled) impacted_subscriptions,(SELECT count(*)::int FROM ath_notification_deliveries WHERE status='PENDING') pending_dispatch,(SELECT count(*)::int FROM ath_notification_deliveries WHERE status='FAILED') failed_dispatch FROM ath_data_capabilities c LEFT JOIN latest l USING(capability_key)`)).rows[0]}

export class DataIncidentService{constructor(private sql:SqlClient,private security:AdminSecurityService,private token:string,private ctx:AdminRequestContext){}async change(id:string,action:'ACKNOWLEDGE'|'REQUEST_RECHECK'|'RESOLVE',reason:string){const actor=await this.security.require(this.token,'DATA_OPS');if(reason.trim().length<3||reason.length>240)throw new Error('invalid_reason');const row=(await this.sql.query<Record<string,unknown>>(`SELECT * FROM ath_data_incidents WHERE incident_id=$1::uuid FOR UPDATE`,[id])).rows[0];if(!row)throw new Error('incident_not_found');if(action==='RESOLVE'){const cap=capabilityByKey(String(row.capability_key));const latest=(await this.sql.query<{status:string}>(`SELECT status FROM ath_data_health_observations WHERE capability_key=$1 ORDER BY checked_at DESC LIMIT 1`,[row.capability_key])).rows[0];if(!cap||latest?.status!=='CURRENT')throw new Error('health_not_recovered')}const status=action==='ACKNOWLEDGE'?'ACKNOWLEDGED':action==='RESOLVE'?'RESOLVED':String(row.status);await this.sql.query(`UPDATE ath_data_incidents SET status=$2,acknowledged_at=CASE WHEN $2='ACKNOWLEDGED' THEN now() ELSE acknowledged_at END,acknowledged_by=CASE WHEN $2='ACKNOWLEDGED' THEN $3 ELSE acknowledged_by END,resolved_at=CASE WHEN $2='RESOLVED' THEN now() ELSE resolved_at END,resolved_by=CASE WHEN $2='RESOLVED' THEN $3 ELSE resolved_by END,resolution_reason=CASE WHEN $2='RESOLVED' THEN $4 ELSE resolution_reason END,updated_at=now() WHERE incident_id=$1`,[id,status,actor.staffId,reason]);await this.sql.query(`INSERT INTO ath_data_incident_events(incident_id,event_type,actor_staff_id,reason_code) VALUES($1,$2,$3,$4)`,[id,action==='REQUEST_RECHECK'?'RECHECK_REQUESTED':action==='ACKNOWLEDGE'?'ACKNOWLEDGED':'RESOLVED',actor.staffId,reason]);await this.security.recordAudit(actor,{eventType:`DATA_INCIDENT_${action}`,targetType:'data_incident',targetRef:id,reasonCode:reason,result:'SUCCEEDED',before:{status:row.status},after:{status}},this.ctx);return{ok:true,status}}}
