import type { SqlClient } from '@/lib/customer/sql';
import type { ControlPlaneHub } from './contracts/common';

export const FOUNDER_WINDOWS=['TODAY','7D','30D'] as const;
export type FounderWindow=(typeof FOUNDER_WINDOWS)[number];
export const METRIC_STATUSES=['LIVE','NOT_INSTRUMENTED','UNAVAILABLE','DEGRADED','STALE'] as const;
export type MetricStatus=(typeof METRIC_STATUSES)[number];
export type FounderMetric={key:string;label:string;value:number|null;displayValue:string;status:MetricStatus;window:FounderWindow;asOf:string;source:string;definition:string;numerator?:number;denominator?:number;limitation?:string};
export type FounderFilters={window:FounderWindow;hub?:Exclude<ControlPlaneHub,'ask'>|ControlPlaneHub;jurisdiction?:string;intent?:string};
export type AttentionItem={severity:'P1'|'P2';type:string;title:string;count:number;firstSeen:string|null;lastSeen:string|null;hub?:string;jurisdiction?:string;source:string;href?:string};
export type GrowthOpportunity={type:string;title:string;count:number;basis:string;hub?:string};
export type SearchBreakdown={outcome:string;count:number;rate:number};
export type FounderDashboard={generatedAt:string;firstPartyStartedAt:string|null;filters:FounderFilters;metrics:FounderMetric[];searchOutcomes:SearchBreakdown[];searchByHub:Array<{hub:string;count:number}>;searchByIntent:Array<{intent:string;count:number}>;resultBuckets:Array<{bucket:string;count:number}>;claimStages:Array<{stage:string;count:number;source:string}>;needsAttention:AttentionItem[];growthOpportunities:GrowthOpportunity[]};

const intervals:Record<FounderWindow,string>={TODAY:"date_trunc('day',now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'",'7D':"now()-interval '7 days'",'30D':"now()-interval '30 days'"};
const pct=(n:number,d:number)=>d?Math.round(n/d*1000)/10:0;
const countDisplay=(n:number)=>n.toLocaleString('en-US');
const unavailable=(key:string,label:string,window:FounderWindow,asOf:string,status:MetricStatus,reason:string,source:string,definition:string):FounderMetric=>({key,label,value:null,displayValue:status.replaceAll('_',' '),status,window,asOf,source,definition,limitation:reason});

export async function readFounderDashboard(sql:SqlClient,filters:FounderFilters):Promise<FounderDashboard>{
  const from=intervals[filters.window], params:unknown[]=[];
  const eventWhere=[`occurred_at>=${from}`];
  if(filters.hub){params.push(filters.hub);eventWhere.push(`hub=$${params.length}`)}
  if(filters.jurisdiction){params.push(filters.jurisdiction);eventWhere.push(`jurisdiction=$${params.length}`)}
  if(filters.intent){params.push(filters.intent);eventWhere.push(`intent=$${params.length}`)}
  const where=eventWhere.join(' AND '), now=new Date().toISOString(), claimParams:unknown[]=[];
  const claimScope:string[]=[];
  if(filters.hub==='ask')claimScope.push('false');
  else if(filters.hub){claimParams.push(filters.hub);claimScope.push(`p.hub_id=$${claimParams.length}`)}
  if(filters.jurisdiction){claimParams.push(filters.jurisdiction);claimScope.push(`p.home_state=$${claimParams.length}`)}
  const claimWhere=[`c.created_at>=${from}`,...claimScope], currentClaimWhere=claimScope.length?` AND ${claimScope.join(' AND ')}`:'';
  const [epoch,search,latency,hubRows,intentRows,buckets,claims,attention,activation] = await Promise.all([
    sql.query<{started_at:string}>(`SELECT occurred_at::text started_at FROM ath_product_events WHERE event_name='telemetry_store_activated' ORDER BY occurred_at LIMIT 1`),
    sql.query<{terminal_outcome:string;n:number;p50:number|null;p95:number|null;first_seen:string;last_seen:string}>(`SELECT terminal_outcome,count(*)::int n,percentile_cont(.5) WITHIN GROUP(ORDER BY duration_ms) FILTER(WHERE duration_ms IS NOT NULL)::float8 p50,percentile_cont(.95) WITHIN GROUP(ORDER BY duration_ms) FILTER(WHERE duration_ms IS NOT NULL)::float8 p95,min(occurred_at)::text first_seen,max(occurred_at)::text last_seen FROM ath_product_events WHERE event_name='search_terminal_outcome' AND ${where} GROUP BY terminal_outcome`,params),
    sql.query<{p50:number|null;p95:number|null;samples:number}>(`SELECT percentile_cont(.5) WITHIN GROUP(ORDER BY duration_ms)::float8 p50,percentile_cont(.95) WITHIN GROUP(ORDER BY duration_ms)::float8 p95,count(duration_ms)::int samples FROM ath_product_events WHERE event_name='search_terminal_outcome' AND duration_ms IS NOT NULL AND ${where}`,params),
    sql.query<{hub:string;n:number}>(`SELECT hub,count(*)::int n FROM ath_product_events WHERE event_name='search_terminal_outcome' AND ${where} GROUP BY hub ORDER BY n DESC`,params),
    sql.query<{intent:string;n:number}>(`SELECT COALESCE(intent,'unknown') intent,count(*)::int n FROM ath_product_events WHERE event_name='search_terminal_outcome' AND ${where} GROUP BY 1 ORDER BY n DESC LIMIT 12`,params),
    sql.query<{bucket:string;n:number}>(`SELECT COALESCE(result_count_bucket,'unknown') bucket,count(*)::int n FROM ath_product_events WHERE event_name='search_terminal_outcome' AND ${where} GROUP BY 1 ORDER BY 1`,params),
    sql.query<{started:number;completed:number;approved:number;pending:number;oldest_hours:number|null}>(`SELECT count(*) FILTER(WHERE ${claimWhere.join(' AND ')})::int started,count(*) FILTER(WHERE ${claimWhere.join(' AND ')} AND c.status IN('approved','rejected','withdrawn','superseded'))::int completed,count(*) FILTER(WHERE ${claimWhere.join(' AND ')} AND c.status='approved')::int approved,count(*) FILTER(WHERE c.status IN('submitted','needs_info','in_review')${currentClaimWhere})::int pending,max(extract(epoch FROM(now()-c.created_at))/3600) FILTER(WHERE c.status IN('submitted','needs_info','in_review')${currentClaimWhere})::float8 oldest_hours FROM ath_claims c JOIN ath_hub_profiles p ON p.id=c.hub_profile_id`,claimParams),
    sql.query<{validation_failures:number;first_failure:string|null;last_failure:string|null;cta:number;manager_opened:number}>(`SELECT count(*) FILTER(WHERE event_name='claim_validation_failed' AND ${where})::int validation_failures,min(occurred_at) FILTER(WHERE event_name='claim_validation_failed' AND ${where})::text first_failure,max(occurred_at) FILTER(WHERE event_name='claim_validation_failed' AND ${where})::text last_failure,count(*) FILTER(WHERE event_name='claim_cta_clicked' AND ${where})::int cta,count(*) FILTER(WHERE event_name='manage_business_opened' AND ${where})::int manager_opened FROM ath_product_events`,params),
    sql.query<{approved_orgs:number;qualifying_orgs:number}>(`SELECT count(DISTINCT g.org_id)::int approved_orgs,count(DISTINCT a.org_id) FILTER(WHERE a.action IN('business_profile_updated','business_profile_reconfirmed','record_issue_created','business_reply_submitted','monitoring_enabled','organization_member_invited'))::int qualifying_orgs FROM ath_management_grants g LEFT JOIN ath_audit_events a ON a.org_id=g.org_id AND a.created_at>=g.granted_at WHERE g.status='active'`),
  ]);
  const byOutcome=new Map(search.rows.map(r=>[r.terminal_outcome,Number(r.n)])), total=[...byOutcome.values()].reduce((a,b)=>a+b,0), results=byOutcome.get('RESULTS')??0,clarification=byOutcome.get('CLARIFICATION')??0,dead=byOutcome.get('FAIL_CLOSED_DEAD_END')??0,errors=byOutcome.get('ERROR')??0, latencyRow=latency.rows[0]??{p50:null,p95:null,samples:0};
  const claim=claims.rows[0]??{started:0,completed:0,approved:0,pending:0,oldest_hours:null}, att=attention.rows[0]??{validation_failures:0,first_failure:null,last_failure:null,cta:0,manager_opened:0}, act=activation.rows[0]??{approved_orgs:0,qualifying_orgs:0};
  const live=(key:string,label:string,value:number,displayValue:string,source:string,definition:string,numerator?:number,denominator?:number):FounderMetric=>({key,label,value,displayValue,status:'LIVE',window:filters.window,asOf:now,source,definition,numerator,denominator});
  const metrics:FounderMetric[]=[
    unavailable('research_sessions','Research sessions',filters.window,now,'NOT_INSTRUMENTED','A session-boundary contract is not yet emitted.','product_event.v1','Distinct research sessions, not page views.'),
    live('search_results_rate','Search RESULTS rate',pct(results,total),total?`${pct(results,total)}%`:'0%','ath_product_events','RESULTS outcomes / Search terminal outcomes.',results,total),
    unavailable('save_watch','Save → Watch',filters.window,now,'UNAVAILABLE','Unified cross-hub Save/Watch persistence is not available.','specialist consumer systems','Consumers creating a Watch after a Save.'),
    unavailable('activated_consumers','Activated consumers',filters.window,now,'UNAVAILABLE','Unified Projects/Saves/Watches plus return-session identity is unavailable.','network consumer systems','Authenticated identity + persisted research object + return session.'),
    unavailable('alert_return','Alert → return',filters.window,now,'UNAVAILABLE','Unified alert-to-return attribution is not available.','specialist monitoring systems','Delivered alerts followed by a research return.'),
    att.cta>0?live('claim_cta_start','Claim CTA → start',pct(Number(claim.started),Number(att.cta)),`${pct(Number(claim.started),Number(att.cta))}%`,'ath_product_events + ath_claims','Unique claim starts / claim CTA observations in window.',Number(claim.started),Number(att.cta)):unavailable('claim_cta_start','Claim CTA → start',filters.window,now,'NOT_INSTRUMENTED','No first-party CTA denominator exists yet for this window.','ath_product_events + ath_claims','Unique claim starts / claim CTA observations.'),
    live('claim_completion','Claim completion',pct(Number(claim.completed),Number(claim.started)),Number(claim.started)?`${pct(Number(claim.completed),Number(claim.started))}%`:'0%','ath_claims','Terminal claim outcomes / claims created in window.',Number(claim.completed),Number(claim.started)),
    live('pending_claims','Pending claims',Number(claim.pending),countDisplay(Number(claim.pending)),'ath_claims','Current submitted, needs-info, or in-review claims.'),
    unavailable('business_activation','Activated organizations',filters.window,now,'NOT_INSTRUMENTED',`${act.approved_orgs} organizations have active grants and ${act.qualifying_orgs} have qualifying durable actions, but Manager-open cannot be safely joined to organization.`,'ath_management_grants + ath_audit_events + product_event.v1','Approved grant + Manager opened + qualifying post-claim action.'),
    unavailable('business_30d_active','30-day active organizations',filters.window,now,'NOT_INSTRUMENTED','Requires completed Activated Business cohort linkage first.','same as Activated Business','Activated organization with a qualifying action during its following 30-day window.'),
    live('search_dead_end_rate','Search dead-end rate',pct(dead,total),total?`${pct(dead,total)}%`:'0%','ath_product_events','FAIL_CLOSED_DEAD_END / Search terminal outcomes.',dead,total),
    live('search_error_rate','Search ERROR rate',pct(errors,total),total?`${pct(errors,total)}%`:'0%','ath_product_events','ERROR / Search terminal outcomes.',errors,total),
    latencyRow.p50==null?unavailable('search_p50','Search p50 latency',filters.window,now,'NOT_INSTRUMENTED','No duration samples exist in this instrumented window.','ath_product_events.duration_ms','Median terminal Search duration.'):live('search_p50','Search p50 latency',Number(latencyRow.p50),`${Math.round(Number(latencyRow.p50))} ms`,'ath_product_events.duration_ms','Median terminal Search duration.'),
    latencyRow.p95==null?unavailable('search_p95','Search p95 latency',filters.window,now,'NOT_INSTRUMENTED','No duration samples exist in this instrumented window.','ath_product_events.duration_ms','95th percentile terminal Search duration.'):live('search_p95','Search p95 latency',Number(latencyRow.p95),`${Math.round(Number(latencyRow.p95))} ms`,'ath_product_events.duration_ms',`95th percentile terminal Search duration across ${latencyRow.samples} samples.`),
  ];
  const needsAttention:AttentionItem[]=[];
  if(errors>0)needsAttention.push({severity:'P1',type:'SEARCH_ERROR_SPIKE',title:'Search errors observed',count:errors,firstSeen:search.rows.find(r=>r.terminal_outcome==='ERROR')?.first_seen??null,lastSeen:search.rows.find(r=>r.terminal_outcome==='ERROR')?.last_seen??null,source:'ath_product_events',href:'/admin#search-health'});
  if(dead>0)needsAttention.push({severity:'P2',type:'SEARCH_DEAD_END_SPIKE',title:'Search dead ends observed',count:dead,firstSeen:search.rows.find(r=>r.terminal_outcome==='FAIL_CLOSED_DEAD_END')?.first_seen??null,lastSeen:search.rows.find(r=>r.terminal_outcome==='FAIL_CLOSED_DEAD_END')?.last_seen??null,source:'ath_product_events',href:'/admin#search-health'});
  if(Number(att.validation_failures)>0)needsAttention.push({severity:'P1',type:'CLAIM_VALIDATION_FAILURE_CLUSTER',title:'Claim validation failures observed',count:Number(att.validation_failures),firstSeen:att.first_failure,lastSeen:att.last_failure,source:'ath_product_events',href:'/internal/review'});
  if(Number(claim.pending)>0 && Number(claim.oldest_hours??0)>72)needsAttention.push({severity:'P2',type:'PENDING_CLAIM_AGE',title:'Pending claims older than 72 hours',count:Number(claim.pending),firstSeen:null,lastSeen:now,source:'ath_claims · internal operating threshold',href:'/internal/review'});
  const growthOpportunities:GrowthOpportunity[]=[];
  if(Number(claim.started)>=3 && Number(claim.completed)<Number(claim.started))growthOpportunities.push({type:'CLAIM_COMPLETION_OPPORTUNITY',title:'Started claims without terminal completion in this window',count:Number(claim.started)-Number(claim.completed),basis:'ath_claims statuses; operational cohort, not an incident.'});
  if(clarification>=3)growthOpportunities.push({type:'HIGH_CLARIFICATION_COHORT',title:'Search clarification cohort',count:clarification,basis:'First-party CLARIFICATION outcomes; review demand patterns without changing routing.'});
  return {generatedAt:now,firstPartyStartedAt:epoch.rows[0]?.started_at??null,filters,metrics,searchOutcomes:['RESULTS','CLARIFICATION','FAIL_CLOSED_WITH_ACTION','FAIL_CLOSED_DEAD_END','ERROR'].map(outcome=>({outcome,count:byOutcome.get(outcome)??0,rate:pct(byOutcome.get(outcome)??0,total)})),searchByHub:hubRows.rows.map(r=>({hub:r.hub,count:Number(r.n)})),searchByIntent:intentRows.rows.map(r=>({intent:r.intent,count:Number(r.n)})),resultBuckets:buckets.rows.map(r=>({bucket:r.bucket,count:Number(r.n)})),claimStages:[{stage:'Claims started',count:Number(claim.started),source:'ath_claims.created_at'},{stage:'Terminal claim outcomes',count:Number(claim.completed),source:'ath_claims.status'},{stage:'Approved',count:Number(claim.approved),source:'ath_claims.status=approved'},{stage:'Business Manager opened',count:Number(att.manager_opened),source:'product_event.v1 · forward only'}],needsAttention,growthOpportunities};
}

export function normalizeFounderFilters(input:Record<string,string|string[]|undefined>):FounderFilters{const w=String(input.window??'7D').toUpperCase();const window=FOUNDER_WINDOWS.includes(w as FounderWindow)?w as FounderWindow:'7D';const candidateHub=String(input.hub??'');const hub=['ask','move','lender','insurance','contractor','senior','investor'].includes(candidateHub)?candidateHub as ControlPlaneHub:undefined;const jurisdiction=/^[A-Za-z]{2}$/.test(String(input.jurisdiction??''))?String(input.jurisdiction).toUpperCase():undefined;const intent=/^[A-Za-z0-9_:-]{1,64}$/.test(String(input.intent??''))?String(input.intent):undefined;return{window,hub,jurisdiction,intent}}
