import 'server-only';
import type{SqlClient}from'@/lib/customer/sql';
import{AdminSecurityService,type AdminRequestContext}from'./security.ts';
import{hasAdminPermission,type AdminIdentity}from'./rbac.ts';

export const IDENTITY_REVIEW_TYPES=['POSSIBLE_DUPLICATE','IDENTIFIER_REUSED','REVIEW_REQUIRED_BINDING','PROFILE_REDIRECT','MERGE_CANDIDATE','SPLIT_CANDIDATE','HUB_PROFILE_ORPHAN','ORGANIZATION_PROFILE_RELATIONSHIP_REVIEW']as const;
export const IDENTITY_RESOLUTIONS=['CONFIRM_DISTINCT','CONFIRM_REPLACEMENT_RELATIONSHIP','REQUEST_SPECIALIST_REVIEW','WAIT_FOR_SOURCE_RECOVERY','MARK_BINDING_REVIEWED','CLOSE_NO_ACTION']as const;
export type IdentityResolution=(typeof IDENTITY_RESOLUTIONS)[number];
export function identityDecisionAllowed(actor:Pick<AdminIdentity,'role'>,reviewType:string){return reviewType==='ORGANIZATION_PROFILE_RELATIONSHIP_REVIEW'?hasAdminPermission(actor.role,'CLAIM_OPS'):hasAdminPermission(actor.role,'DATA_OPS')}

export class IdentityOperationsService{
 private sql:SqlClient;private security:AdminSecurityService;private token:string;private ctx:AdminRequestContext;
 constructor(sql:SqlClient,security:AdminSecurityService,token:string,ctx:AdminRequestContext){this.sql=sql;this.security=security;this.token=token;this.ctx=ctx}
 private async read(){return this.security.require(this.token,'ADMIN_VIEW')}
 async detect(){await this.security.require(this.token,'DATA_OPS');
  await this.sql.query(`INSERT INTO ath_identity_reviews(review_key,review_type,hub,primary_hub_profile_id,secondary_hub_profile_id,severity,reason_codes,match_basis)
   SELECT 'identifier:'||a.hub_id||':'||a.id||':'||b.id,'IDENTIFIER_REUSED',a.hub_id,a.id,b.id,'P1',ARRAY['EXACT_IDENTIFIER_CONFLICT'],ARRAY['EXACT_IDENTIFIER_NAMESPACE_AND_VALUE']
   FROM ath_hub_profiles a JOIN ath_hub_profiles b ON b.hub_id=a.hub_id AND b.id>a.id AND b.identifier_namespace=a.identifier_namespace AND b.native_credential_key=a.native_credential_key
   WHERE a.identifier_namespace IS NOT NULL AND a.entity_class=b.entity_class ON CONFLICT(review_key)DO NOTHING`);
  await this.sql.query(`INSERT INTO ath_identity_reviews(review_key,review_type,hub,primary_hub_profile_id,organization_id,severity,reason_codes,match_basis,dependency_status)
   SELECT 'grant-binding:'||g.id,'ORGANIZATION_PROFILE_RELATIONSHIP_REVIEW',p.hub_id,p.id,g.org_id,'P1',ARRAY['ACTIVE_GRANT_CLAIM_BINDING_MISMATCH'],ARRAY['EXACT_GRANT_AND_CLAIM_PROFILE_BINDING'],'CURRENT'
   FROM ath_management_grants g JOIN ath_hub_profiles p ON p.id=g.hub_profile_id JOIN ath_claims c ON c.id=g.granted_from_claim_id
   WHERE g.status='active' AND(c.hub_profile_id<>g.hub_profile_id OR c.org_id<>g.org_id) ON CONFLICT(review_key)DO NOTHING`);
 }
 async list(filter?:string){await this.read();await this.detectReadOnlySafe();const params:unknown[]=[];let where='true';if(filter&&IDENTITY_REVIEW_TYPES.includes(filter as never)){params.push(filter);where=`r.review_type=$1`}else if(filter&&['OPEN','WAITING','RESOLVED'].includes(filter)){params.push(filter);where=`r.status=$1`}else if(filter&&['contractor','move','lender','senior','insurance','investor'].includes(filter)){params.push(filter);where=`r.hub=$1`}return(await this.sql.query<Record<string,unknown>>(`SELECT r.review_id::text,r.review_type,r.hub,r.status,r.severity,r.reason_codes,r.match_basis,r.dependency_status,r.opened_at::text,p.display_name_snapshot,p.entity_class,p.identifier_namespace,p.native_credential_key FROM ath_identity_reviews r LEFT JOIN ath_hub_profiles p ON p.id=r.primary_hub_profile_id WHERE ${where} ORDER BY CASE r.severity WHEN 'P0' THEN 0 WHEN 'P1' THEN 1 WHEN 'P2' THEN 2 ELSE 3 END,r.opened_at LIMIT 250`,params)).rows}
 private async detectReadOnlySafe(){/* Candidate creation is an explicit DATA_OPS action, never a page-load mutation. */}
 async detail(id:string){await this.read();const rows=await this.sql.query<Record<string,unknown>>(`SELECT r.*,a.display_name_snapshot primary_name,a.hub_id primary_hub,a.entity_class primary_class,a.identifier_namespace primary_namespace,a.native_credential_key primary_identifier,a.native_profile_id::text primary_native_id,a.native_source_system primary_source,a.publication_state primary_publication,b.display_name_snapshot secondary_name,b.entity_class secondary_class,b.identifier_namespace secondary_namespace,b.native_credential_key secondary_identifier,b.native_profile_id::text secondary_native_id,b.native_source_system secondary_source,b.publication_state secondary_publication,o.display_name organization_name FROM ath_identity_reviews r LEFT JOIN ath_hub_profiles a ON a.id=r.primary_hub_profile_id LEFT JOIN ath_hub_profiles b ON b.id=r.secondary_hub_profile_id LEFT JOIN ath_organizations o ON o.id=r.organization_id WHERE r.review_id=$1`,[id]);if(!rows.rows[0])throw new Error('not_found');const events=await this.sql.query<Record<string,unknown>>(`SELECT event_type,reason_code,from_status,to_status,occurred_at::text FROM ath_identity_review_events WHERE review_id=$1 ORDER BY occurred_at`,[id]);return{review:rows.rows[0],events:events.rows}}
 async decide(id:string,resolution:IdentityResolution,reason:string){if(!IDENTITY_RESOLUTIONS.includes(resolution)||!/^[A-Z0-9_:-]{3,120}$/.test(reason))throw new Error('validation_failed');const actor=await this.security.identity(this.token);if(!actor)await this.security.require(this.token,'ADMIN_VIEW');const current=(await this.sql.query<{review_type:string;status:string}>(`SELECT review_type,status FROM ath_identity_reviews WHERE review_id=$1 FOR UPDATE`,[id])).rows[0];if(!current)throw new Error('not_found');if(!actor||!identityDecisionAllowed(actor,current.review_type))throw new Error('forbidden');const next=resolution==='WAIT_FOR_SOURCE_RECOVERY'?'WAITING':'RESOLVED';await this.sql.query(`UPDATE ath_identity_reviews SET status=$2,resolution=$3,resolved_at=CASE WHEN $2='RESOLVED' THEN now() ELSE NULL END,assigned_staff_id=$4 WHERE review_id=$1`,[id,next,resolution,actor.staffId]);await this.sql.query(`INSERT INTO ath_identity_review_events(review_id,event_type,actor_staff_id,reason_code,from_status,to_status)VALUES($1,'DECISION_RECORDED',$2,$3,$4,$5)`,[id,actor.staffId,reason,current.status,next]);await this.security.recordAudit(actor,{eventType:'IDENTITY_REVIEW_DECIDED',targetType:'identity_review',targetRef:id,reasonCode:reason,result:'SUCCEEDED',before:{status:current.status},after:{status:next,resolution}},this.ctx);return{ok:true,status:next}}
}

export function exactIdentityCandidate(input:{sameName?:boolean;sameAddress?:boolean;sameDomain?:boolean;exactIdentifierConflict?:boolean;exactNativeProfileConflict?:boolean}){return Boolean(input.exactIdentifierConflict||input.exactNativeProfileConflict)}
export function grainsCompatible(a:{hub:string;entityClass:string},b:{hub:string;entityClass:string}){return a.hub===b.hub&&a.entityClass===b.entityClass}
export function orphanDisposition(dependency:'CURRENT'|'DELAYED'|'DEGRADED'|'UNKNOWN'){return dependency==='DEGRADED'||dependency==='UNKNOWN'?'WAIT_FOR_SOURCE_RECOVERY':'REVIEW_REQUIRED'}
export async function readIdentityPulse(sql:SqlClient){return(await sql.query<{open:number;critical:number;orphans:number}>(`SELECT count(*) FILTER(WHERE status IN('OPEN','WAITING'))::int open,count(*) FILTER(WHERE status IN('OPEN','WAITING') AND severity IN('P0','P1'))::int critical,count(*) FILTER(WHERE status IN('OPEN','WAITING') AND review_type='HUB_PROFILE_ORPHAN')::int orphans FROM ath_identity_reviews`)).rows[0]??{open:0,critical:0,orphans:0}}
