import {createHash,randomUUID} from 'node:crypto';
import {buildAskResearchRoute} from '../network/ask-research-route.ts';
import {orchestrateGuidedResearch} from '../guided-research/orchestrator.ts';
import type {GuidedResultState} from '../guided-research/contract.ts';

export const SEARCH_CANARY_SUITE_VERSION='search-canary-suite.v1' as const;
export const CANARY_RUN_STATUSES=['PASS','FAIL','ERROR','FLAKY','DEPENDENCY_BLOCKED'] as const;
export type CanaryRunStatus=(typeof CANARY_RUN_STATUSES)[number];
export const RELEASE_GATE_STATES=['READY','WARN','BLOCKED','UNKNOWN'] as const;
export type ReleaseGateState=(typeof RELEASE_GATE_STATES)[number];
export type SearchTerminalOutcome='RESULTS'|'CLARIFICATION'|'FAIL_CLOSED_WITH_ACTION'|'FAIL_CLOSED_DEAD_END'|'ERROR';
export type CanarySuite='QUICK'|'FULL'|'RELEASE';
export type SearchCanaryDefinition={key:string;description:string;question:string;surface:'ASK_SSR'|'GUIDED';hub:'move'|'lender'|'insurance'|'senior'|'contractor'|'investor'|null;classes:readonly string[];severity:'BLOCKER'|'WARNING';suites:readonly CanarySuite[];expectedTerminal:SearchTerminalOutcome;expectedResultStates?:readonly GuidedResultState[];expectedIntent?:string;expectedIdentityFamily?:string;requiresRows?:boolean;requiresNextAction?:boolean;forbidsNextAction?:boolean;maxRows?:number;dependencies:readonly string[];latencyWarningMs:number;repetitions?:number};
export type NormalizedSearchContract={terminalOutcome:SearchTerminalOutcome;hub:string|null;intent:string|null;resultState:string|null;rowCount:number;identityFamilies:string[];hasExplanation:boolean;hasLimitations:boolean;hasNextAction:boolean;hasProvenance:boolean;destinations:string[];shape:string[]};
export type CanaryAssessment={status:CanaryRunStatus;failureCodes:string[];fingerprint:string;contract:NormalizedSearchContract};

const suite=(...s:CanarySuite[])=>s;
export const SEARCH_CANARIES:readonly SearchCanaryDefinition[]=[
 {key:'INVESTOR_UNSPECIFIED_ENTITY',description:'Unspecified adviser asks for identity before research; never broad RIA/ERA browse.',question:'Is this financial advisor registered with the SEC?',surface:'ASK_SSR',hub:'investor',classes:['ROUTING_SAFETY','CLARIFICATION'],severity:'BLOCKER',suites:suite('QUICK','FULL','RELEASE'),expectedTerminal:'CLARIFICATION',expectedIntent:'ENTITY_LOOKUP_MISSING_IDENTITY',maxRows:0,dependencies:[],latencyWarningMs:1500},
 {key:'MOVE_HOW_TO_NOT_ENTITY',description:'Mover licensing how-to routes to verification guidance, not an entity-name lookup.',question:'How do I check if a moving company is licensed?',surface:'ASK_SSR',hub:'move',classes:['ROUTING_SAFETY','FAIL_CLOSED'],severity:'BLOCKER',suites:suite('QUICK','FULL','RELEASE'),expectedTerminal:'FAIL_CLOSED_WITH_ACTION',expectedIntent:'HOW_TO',requiresNextAction:true,maxRows:0,dependencies:[],latencyWarningMs:1500},
 {key:'SENIOR_UNSPECIFIED_HOME_HEALTH',description:'Unspecified home-health identity asks for clarification; never geographic browse.',question:'Is this home health agency Medicare certified?',surface:'ASK_SSR',hub:'senior',classes:['ROUTING_SAFETY','CLARIFICATION'],severity:'BLOCKER',suites:suite('QUICK','FULL','RELEASE'),expectedTerminal:'CLARIFICATION',expectedIntent:'ENTITY_LOOKUP_MISSING_IDENTITY',maxRows:0,dependencies:[],latencyWarningMs:1500},
 {key:'UNSUPPORTED_WITH_ACTION',description:'Unsupported value judgment fails closed with a bounded specialist research action.',question:'Which contractor is the safest?',surface:'ASK_SSR',hub:'contractor',classes:['FAIL_CLOSED'],severity:'BLOCKER',suites:suite('QUICK','FULL','RELEASE'),expectedTerminal:'FAIL_CLOSED_WITH_ACTION',expectedIntent:'RECOMMENDATION_REQUEST',requiresNextAction:true,maxRows:0,dependencies:[],latencyWarningMs:1500},
 {key:'UNSUPPORTED_DEAD_END',description:'Out-of-network request fails closed without a fabricated result or destination.',question:'What is the best pizza near me?',surface:'ASK_SSR',hub:null,classes:['FAIL_CLOSED'],severity:'BLOCKER',suites:suite('QUICK','FULL','RELEASE'),expectedTerminal:'FAIL_CLOSED_DEAD_END',forbidsNextAction:true,maxRows:0,dependencies:[],latencyWarningMs:1500},
 {key:'PRESENTATION_STABILITY',description:'Fresh logical sessions preserve the required clarification presentation contract.',question:'Is this financial advisor registered with the SEC?',surface:'ASK_SSR',hub:'investor',classes:['PRESENTATION_STABILITY'],severity:'BLOCKER',suites:suite('FULL','RELEASE'),expectedTerminal:'CLARIFICATION',maxRows:0,dependencies:[],latencyWarningMs:1500,repetitions:3},
 {key:'MOVE_EXACT_USDOT',description:'Stable USDOT probe preserves Move identity grain and provenance.',question:'USDOT 3244649',surface:'GUIDED',hub:'move',classes:['EXACT_IDENTITY','PROVENANCE'],severity:'WARNING',suites:suite('FULL'),expectedTerminal:'RESULTS',expectedResultStates:['SUPPORTED_RESULTS','EXACT_IDENTITY'],expectedIdentityFamily:'mover',requiresRows:true,dependencies:['MOVE_FMCSA_AUTHORITY'],latencyWarningMs:12000},
 {key:'LENDER_EXACT_NMLS',description:'Stable NMLS institution probe preserves institution grain and provenance.',question:'NMLS 3030',surface:'GUIDED',hub:'lender',classes:['EXACT_IDENTITY','PROVENANCE'],severity:'WARNING',suites:suite('FULL'),expectedTerminal:'RESULTS',expectedResultStates:['EXACT_IDENTITY'],requiresRows:true,dependencies:['LENDER_NMLS_IDENTITY'],latencyWarningMs:12000},
 {key:'INSURANCE_EXACT_NPN',description:'Stable NPN probe preserves insurance entity-class separation and provenance.',question:'NPN 10391484',surface:'GUIDED',hub:'insurance',classes:['EXACT_IDENTITY','PROVENANCE'],severity:'WARNING',suites:suite('FULL'),expectedTerminal:'RESULTS',expectedResultStates:['EXACT_IDENTITY'],requiresRows:true,dependencies:['INSURANCE_NAIC_IDENTITY'],latencyWarningMs:12000},
 {key:'SENIOR_EXACT_CCN',description:'Stable CCN probe preserves provider-class identity and provenance.',question:'CMS CCN 105411',surface:'GUIDED',hub:'senior',classes:['EXACT_IDENTITY','PROVENANCE'],severity:'WARNING',suites:suite('FULL'),expectedTerminal:'RESULTS',expectedResultStates:['SUPPORTED_RESULTS','EXACT_IDENTITY'],requiresRows:true,dependencies:['SENIOR_CMS_NURSING_HOME'],latencyWarningMs:12000},
 {key:'CONTRACTOR_BROWARD_ROOFING',description:'Contractor cohort preserves trade and credential geography.',question:'licensed roofer in Fort Lauderdale Florida',surface:'GUIDED',hub:'contractor',classes:['RESULT_CONTRACT','PROVENANCE'],severity:'WARNING',suites:suite('FULL'),expectedTerminal:'RESULTS',expectedResultStates:['SUPPORTED_RESULTS'],requiresRows:true,dependencies:['CONTRACTOR_FL_DBPR_IDENTITY'],latencyWarningMs:12000},
 {key:'INVESTOR_EXACT_CRD',description:'Stable firm CRD probe preserves firm—not representative—identity.',question:'CRD 166089',surface:'GUIDED',hub:'investor',classes:['EXACT_IDENTITY','PROVENANCE'],severity:'WARNING',suites:suite('FULL'),expectedTerminal:'RESULTS',expectedResultStates:['EXACT_IDENTITY'],requiresRows:true,dependencies:['INVESTOR_SEC_ADV'],latencyWarningMs:12000},
] as const;

const allowedHost=(href:string)=>{try{const h=new URL(href,'https://www.asktrusthub.com').hostname.toLowerCase();return h.endsWith('trusthub.com')||['adviserinfo.sec.gov','www.fmcsa.dot.gov','www.medicare.gov','www.nmlsconsumeraccess.org','content.naic.org'].includes(h)}catch{return false}};
function outcomeForRoute(route:ReturnType<typeof buildAskResearchRoute>):SearchTerminalOutcome{if(route.plan.intent==='ENTITY_LOOKUP_MISSING_IDENTITY')return'CLARIFICATION';if(['HOW_TO','EXPLAINER','RECOMMENDATION_REQUEST'].includes(route.plan.intent))return route.destinations.length?'FAIL_CLOSED_WITH_ACTION':'FAIL_CLOSED_DEAD_END';if(route.plan.executionAllowed&&route.scope.executionAllowed)return'RESULTS';return route.destinations.length?'FAIL_CLOSED_WITH_ACTION':'FAIL_CLOSED_DEAD_END'}
export async function executeCanary(def:SearchCanaryDefinition):Promise<{contract:NormalizedSearchContract;latencyMs:number}>{const started=performance.now();if(def.surface==='ASK_SSR'){const route=buildAskResearchRoute(def.question);return{latencyMs:Math.round(performance.now()-started),contract:{terminalOutcome:outcomeForRoute(route),hub:route.plan.primaryHub??null,intent:route.plan.intent,resultState:null,rowCount:0,identityFamilies:route.plan.entityClass?.id?[route.plan.entityClass.id]:[],hasExplanation:Boolean(route.explanation),hasLimitations:Boolean(route.limitation),hasNextAction:route.destinations.length>0,hasProvenance:route.destinations.length>0,destinations:route.destinations.map(d=>d.href),shape:['consumerHeading','consumerMessage','interpretation','rows','provenance','limitations','destinations','nextActions']}}}const response=await orchestrateGuidedResearch({action:{type:'START',question:def.question}});const result=response.result;const rows=result?.rows??[];return{latencyMs:Math.round(performance.now()-started),contract:{terminalOutcome:result?['BACKEND_UNAVAILABLE','TIMEOUT'].includes(result.resultState)?'ERROR':result.resultState==='SUPPORTED_RESULTS'||result.resultState==='EXACT_IDENTITY'?'RESULTS':result.choices?.length?'CLARIFICATION':result.destinations?.length||result.nextActions?.length?'FAIL_CLOSED_WITH_ACTION':'FAIL_CLOSED_DEAD_END':'CLARIFICATION',hub:response.session.hub??null,intent:response.session.researchPlan.intent,resultState:result?.resultState??null,rowCount:result?.total??0,identityFamilies:[...new Set(rows.map(r=>String((r as Record<string,unknown>).entityClass??(r as Record<string,unknown>).profileClass??'unknown')))],hasExplanation:Boolean(result?.consumerMessage),hasLimitations:Boolean(result?.limitations?.length),hasNextAction:Boolean(result?.destinations?.length||result?.nextActions?.length),hasProvenance:Boolean(result?.provenance&&Object.keys(result.provenance).length),destinations:(result?.destinations??[]).map(d=>d.href),shape:Object.keys(result??{}).filter(k=>!['requestId','latencyMs'].includes(k)).sort()}}}
export function assessCanary(def:SearchCanaryDefinition,contract:NormalizedSearchContract,dependencyStatus:'CURRENT'|'DELAYED'|'DEGRADED'|'UNKNOWN'='CURRENT'):CanaryAssessment{const f:string[]=[];if(contract.terminalOutcome!==def.expectedTerminal)f.push('WRONG_TERMINAL_OUTCOME');if(def.hub!==contract.hub)f.push('WRONG_HUB');if(def.expectedIntent&&contract.intent!==def.expectedIntent)f.push('WRONG_INTENT');if(def.expectedResultStates&&!def.expectedResultStates.includes(contract.resultState as GuidedResultState))f.push('WRONG_RESULT_STATE');if(def.maxRows!==undefined&&contract.rowCount>def.maxRows)f.push('UNEXPECTED_BROAD_RESULT');if(def.requiresRows&&contract.rowCount<1)f.push('RESULT_COUNT_OUT_OF_RANGE');if(def.expectedIdentityFamily&&contract.identityFamilies.some(x=>x!=='unknown'&&!x.includes(def.expectedIdentityFamily!)))f.push('WRONG_IDENTITY_GRAIN');if(def.requiresNextAction&&!contract.hasNextAction)f.push('EXPECTED_NEXT_ACTION_MISSING');if(def.forbidsNextAction&&contract.hasNextAction)f.push('UNEXPECTED_NEXT_ACTION');if(def.requiresRows&&!contract.hasProvenance)f.push('PROVENANCE_MISSING');if(contract.destinations.some(x=>!allowedHost(x)))f.push('UNSAFE_DESTINATION');if(!contract.hasExplanation)f.push('RESPONSE_SHAPE_UNSTABLE');const routingFailure=f.some(x=>['WRONG_HUB','WRONG_INTENT','WRONG_IDENTITY_GRAIN','UNEXPECTED_BROAD_RESULT','UNSAFE_DESTINATION'].includes(x));const dependencyBlocked=f.length>0&&!routingFailure&&def.dependencies.length>0&&['DEGRADED','UNKNOWN'].includes(dependencyStatus);const normalized=JSON.stringify(contract);return{status:f.length===0?'PASS':dependencyBlocked?'DEPENDENCY_BLOCKED':'FAIL',failureCodes:f,fingerprint:createHash('sha256').update(normalized).digest('hex'),contract}}
export function evaluateRelease(buildId:string,expectedBuildId:string,runs:Array<{definition:SearchCanaryDefinition;status:CanaryRunStatus}>,fresh=true):{gate:ReleaseGateState;reasons:string[]}{if(!buildId||buildId!==expectedBuildId)return{gate:'BLOCKED',reasons:['DEPLOYMENT_IDENTITY_MISMATCH']};if(!fresh)return{gate:'UNKNOWN',reasons:['STALE_EVIDENCE']};const blockers=runs.filter(r=>r.definition.severity==='BLOCKER');if(!blockers.length)return{gate:'UNKNOWN',reasons:['NO_CRITICAL_EVIDENCE']};if(blockers.some(r=>['FAIL','ERROR','FLAKY'].includes(r.status)))return{gate:'BLOCKED',reasons:['CRITICAL_CANARY_FAILED']};if(runs.some(r=>r.status!=='PASS'))return{gate:'WARN',reasons:['WARNING_OR_DEPENDENCY_BLOCK']};return{gate:'READY',reasons:[]}}
export function suiteCanaries(kind:CanarySuite){return SEARCH_CANARIES.filter(c=>c.suites.includes(kind))}
export function newRunGroupId(){return randomUUID()}
export type SearchIncidentState={status:'SUSPECT'|'OPEN'|'ACKNOWLEDGED'|'RECOVERABLE'|'RESOLVED';occurrenceCount:number;consecutiveFailures:number;consecutivePasses:number};
export function nextIncidentState(current:SearchIncidentState|undefined,event:'BLOCKER_FAILURE'|'PASS'):SearchIncidentState|undefined{if(event==='BLOCKER_FAILURE'){if(!current)return{status:'SUSPECT',occurrenceCount:1,consecutiveFailures:1,consecutivePasses:0};const failures=current.consecutiveFailures+1;return{...current,status:failures>=2?'OPEN':current.status,occurrenceCount:current.occurrenceCount+1,consecutiveFailures:failures,consecutivePasses:0}}if(!current)return undefined;const passes=current.consecutivePasses+1;return{...current,status:passes>=2?'RECOVERABLE':current.status,consecutiveFailures:0,consecutivePasses:passes}}
