import {createHash,timingSafeEqual} from 'node:crypto';
import {hashToken} from '../customer/crypto.ts';
import {one,type SqlClient} from '../customer/sql.ts';
import {ADMIN_COMMAND_TYPES,validateAdminCommandV1,type AdminCommandV1} from './contracts/admin-command-v1.ts';
import {ADMIN_ROLES,hasAdminPermission,type AdminIdentity,type AdminPermission,type AdminRole} from './rbac.ts';

export class AdminAuthError extends Error{
  readonly code:'UNAUTHENTICATED'|'FORBIDDEN'|'DISABLED'|'BOOTSTRAP_CLOSED'|'INVALID_BOOTSTRAP_PROOF'|'STEP_UP_REQUIRED'|'VALIDATION_FAILED'|'LAST_SUPER_ADMIN';
  constructor(code:AdminAuthError['code']){super(code);this.code=code;this.name='AdminAuthError'}
}
const FORBIDDEN_AUDIT_KEYS=['password','secret','token','service_role','magic_link','handoff','private_note','private_decision'];
function bounded(value:unknown):unknown{if(value===null||typeof value==='boolean'||typeof value==='number')return value;if(typeof value==='string')return value.slice(0,500);if(Array.isArray(value))return value.slice(0,20).map(bounded);if(typeof value==='object'){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(value as Record<string,unknown>)){if(FORBIDDEN_AUDIT_KEYS.some(x=>k.toLowerCase().includes(x)))throw new AdminAuthError('VALIDATION_FAILED');out[k]=bounded(v)}return out}return undefined}
function proofMatches(actual:string,expected:string):boolean{if(!actual||!expected)return false;const a=createHash('sha256').update(actual).digest(),b=createHash('sha256').update(expected).digest();return timingSafeEqual(a,b)}
export type AdminRequestContext={requestId:string;ip?:string|null;userAgent?:string|null};

export class AdminSecurityService{
  private readonly sql:SqlClient;
  private readonly now:()=>Date;
  constructor(sql:SqlClient,now:()=>Date=()=>new Date()){this.sql=sql;this.now=now}
  async identity(sessionToken:string|null|undefined):Promise<AdminIdentity|null>{if(!sessionToken)return null;const row=await one<{staff_id:string;user_id:string;email:string;role:AdminRole;status:'ACTIVE'|'DISABLED';session_id:string;last_authorized_at:string|null;expires_at:string;revoked_at:string|null;user_status:string}>(this.sql,`SELECT a.staff_id::text,u.id::text user_id,u.email,a.role,a.status,s.id::text session_id,a.last_authorized_at::text,s.expires_at::text,s.revoked_at::text,u.status user_status FROM ath_sessions s JOIN ath_users u ON u.id=s.user_id JOIN ath_admin_staff a ON a.user_id=u.id WHERE s.token_hash=$1`,[hashToken(sessionToken)]);if(!row||row.revoked_at||row.user_status!=='active'||new Date(row.expires_at)<=this.now())return null;if(row.status==='DISABLED')throw new AdminAuthError('DISABLED');return{staffId:row.staff_id,userId:row.user_id,email:row.email,role:row.role,status:row.status,sessionId:row.session_id,lastAuthorizedAt:row.last_authorized_at}}
  async require(sessionToken:string|null|undefined,permission:AdminPermission):Promise<AdminIdentity>{const actor=await this.identity(sessionToken);if(!actor)throw new AdminAuthError('UNAUTHENTICATED');if(!hasAdminPermission(actor.role,permission))throw new AdminAuthError('FORBIDDEN');await this.sql.query(`UPDATE ath_admin_staff SET last_authorized_at=$2 WHERE staff_id=$1`,[actor.staffId,this.now().toISOString()]);return actor}
  private async audit(actor:AdminIdentity,event:string,targetType:string,targetRef:string,reason:string,result:string,ctx:AdminRequestContext,before?:unknown,after?:unknown,commandId?:string){await this.sql.query(`INSERT INTO ath_admin_audit_log(actor_staff_id,actor_role,event_type,target_type,target_ref,reason_code,request_id,command_id,result,before_state,after_state,authorization_context,ip,user_agent)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12::jsonb,$13,$14)`,[actor.staffId,actor.role,event,targetType,targetRef,reason,ctx.requestId,commandId??null,result,before===undefined?null:JSON.stringify(bounded(before)),after===undefined?null:JSON.stringify(bounded(after)),JSON.stringify({role:actor.role,contract:'admin-rbac.v1'}),ctx.ip??null,ctx.userAgent??null])}
  async bootstrap(sessionToken:string,proof:string,expectedProof:string,ctx:AdminRequestContext):Promise<AdminIdentity>{const user=await one<{id:string;email:string;session_id:string}>(this.sql,`SELECT u.id::text,u.email,s.id::text session_id FROM ath_sessions s JOIN ath_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND u.status='active' FOR UPDATE`,[hashToken(sessionToken)]);if(!user)throw new AdminAuthError('UNAUTHENTICATED');const count=await one<{n:string}>(this.sql,`SELECT count(*)::text n FROM ath_admin_staff WHERE status='ACTIVE'`);if(Number(count?.n)!==0)throw new AdminAuthError('BOOTSTRAP_CLOSED');if(!proofMatches(proof,expectedProof))throw new AdminAuthError('INVALID_BOOTSTRAP_PROOF');const row=await one<{staff_id:string}>(this.sql,`INSERT INTO ath_admin_staff(user_id,role,status,created_by)VALUES($1,'SUPER_ADMIN','ACTIVE',$1)RETURNING staff_id::text`,[user.id]);const actor:AdminIdentity={staffId:row!.staff_id,userId:user.id,email:user.email,role:'SUPER_ADMIN',status:'ACTIVE',sessionId:user.session_id,lastAuthorizedAt:null};await this.audit(actor,'ADMIN_BOOTSTRAPPED','staff',actor.staffId,'INITIAL_BOOTSTRAP','SUCCEEDED',ctx,undefined,{role:'SUPER_ADMIN',status:'ACTIVE'});return actor}
  async listStaff(token:string){await this.require(token,'ADMIN_VIEW');return(await this.sql.query<{staff_id:string;email:string;role:AdminRole;status:string;created_at:string;last_authorized_at:string|null}>(`SELECT a.staff_id::text,u.email,a.role,a.status,a.created_at::text,a.last_authorized_at::text FROM ath_admin_staff a JOIN ath_users u ON u.id=a.user_id ORDER BY a.created_at`)).rows}
  async changeStaff(token:string,targetStaffId:string,input:{role?:AdminRole;status?:'ACTIVE'|'DISABLED';reason:string},ctx:AdminRequestContext){const actor=await this.require(token,'STAFF_MANAGE');if(!input.reason||input.reason.length>200||input.role&&!ADMIN_ROLES.includes(input.role))throw new AdminAuthError('VALIDATION_FAILED');const current=await one<{staff_id:string;role:AdminRole;status:'ACTIVE'|'DISABLED'}>(this.sql,`SELECT staff_id::text,role,status FROM ath_admin_staff WHERE staff_id=$1 FOR UPDATE`,[targetStaffId]);if(!current)throw new AdminAuthError('VALIDATION_FAILED');if(current.role==='SUPER_ADMIN'&&current.status==='ACTIVE'&&(input.status==='DISABLED'||input.role&&input.role!=='SUPER_ADMIN')){const c=await one<{n:string}>(this.sql,`SELECT count(*)::text n FROM ath_admin_staff WHERE role='SUPER_ADMIN' AND status='ACTIVE'`);if(Number(c?.n)<=1)throw new AdminAuthError('LAST_SUPER_ADMIN')}const next={role:input.role??current.role,status:input.status??current.status};await this.sql.query(`UPDATE ath_admin_staff SET role=$2,status=$3,updated_at=$4::timestamptz,disabled_at=CASE WHEN $3='DISABLED' THEN $4::timestamptz ELSE NULL END,disabled_by=CASE WHEN $3='DISABLED' THEN $5::uuid ELSE NULL END WHERE staff_id=$1`,[targetStaffId,next.role,next.status,this.now().toISOString(),actor.userId]);await this.audit(actor,'STAFF_AUTHORIZATION_CHANGED','staff',targetStaffId,input.reason,'SUCCEEDED',ctx,current,next);return next}
  async listAudit(token:string){await this.require(token,'AUDIT_VIEW');return(await this.sql.query<Record<string,unknown>>(`SELECT audit_id::text,occurred_at::text,actor_role,event_type,target_type,target_ref,reason_code,result,request_id,command_id::text FROM ath_admin_audit_log ORDER BY occurred_at DESC LIMIT 200`)).rows}
  async recordClaimOperation(token:string,input:{eventType:string;targetRef:string;reason:string;result:string;before?:unknown;after?:unknown},ctx:AdminRequestContext){const actor=await this.require(token,'CLAIM_OPS');await this.audit(actor,input.eventType,'claim',input.targetRef,input.reason,input.result,ctx,input.before,input.after);return actor}
  async setControlFlag(token:string,input:{flagKey:string;scopeType:string;scopeRef:string;enabled:boolean;reason:string},ctx:AdminRequestContext){const actor=await this.require(token,'CONTROL_FLAG_MANAGE');if(!/^[A-Z][A-Z0-9_]{2,80}$/.test(input.flagKey)||!['network','hub','profile_class','jurisdiction','capability','campaign','feature'].includes(input.scopeType)||!input.scopeRef||!input.reason)throw new AdminAuthError('VALIDATION_FAILED');const scopeKey=`${input.scopeType}:${input.scopeRef}`;const before=await one<Record<string,unknown>>(this.sql,`SELECT enabled,connection_state,version FROM ath_control_flags WHERE flag_key=$1 AND scope_key=$2 FOR UPDATE`,[input.flagKey,scopeKey]);const row=await one<Record<string,unknown>>(this.sql,`INSERT INTO ath_control_flags(flag_key,scope_type,scope_ref,scope_key,enabled,connection_state,reason_code,changed_by)VALUES($1,$2,$3,$4,$5,'NOT_YET_CONNECTED',$6,$7)ON CONFLICT(flag_key,scope_key)DO UPDATE SET enabled=excluded.enabled,reason_code=excluded.reason_code,changed_by=excluded.changed_by,changed_at=now(),version=ath_control_flags.version+1 RETURNING enabled,connection_state,version`,[input.flagKey,input.scopeType,input.scopeRef,scopeKey,input.enabled,input.reason,actor.staffId]);await this.audit(actor,'CONTROL_FLAG_CHANGED','control_flag',`${input.flagKey}:${scopeKey}`,input.reason,'SUCCEEDED',ctx,before,row);return row}
  async listControlFlags(token:string){await this.require(token,'ADMIN_VIEW');return(await this.sql.query<Record<string,unknown>>(`SELECT flag_id::text,flag_key,scope_type,scope_ref,enabled,connection_state,reason_code,changed_at::text,version FROM ath_control_flags ORDER BY changed_at DESC`)).rows}
  async submitCommand(token:string,command:AdminCommandV1,idempotencyKey:string,ctx:AdminRequestContext):Promise<{command_id?:string;status?:string;result?:unknown;idempotentReplay:boolean}>;
  async submitCommand(token:string,command:AdminCommandV1,idempotencyKey:string,ctx:AdminRequestContext){const actor=await this.require(token,'ADMIN_COMMAND_EXECUTE');if(!idempotencyKey||idempotencyKey.length>120||!validateAdminCommandV1(command).ok||!ADMIN_COMMAND_TYPES.includes(command.command_type))throw new AdminAuthError('VALIDATION_FAILED');const safeScope=bounded(command.target_scope),safeAuthorization=bounded(command.authorization_context);const existing=await one<Record<string,unknown>>(this.sql,`SELECT command_id::text,status,result FROM ath_admin_commands WHERE idempotency_key=$1`,[idempotencyKey]);if(existing)return{...existing,idempotentReplay:true};const row=await one<Record<string,unknown>>(this.sql,`INSERT INTO ath_admin_commands(command_id,command_type,target_scope,actor_staff_id,authorization_context,reason_code,idempotency_key,requested_at,status,before_state_ref,intended_after_state,result,audit_ref)VALUES($1,$2,$3::jsonb,$4,$5::jsonb,$6,$7,$8,'REJECTED',$9,$10,$11::jsonb,$12)RETURNING command_id::text,status,result`,[command.command_id,command.command_type,JSON.stringify(safeScope),actor.staffId,JSON.stringify(safeAuthorization),command.reason_code,idempotencyKey,command.requested_at,command.before_state_ref,command.intended_after_state,JSON.stringify({code:'NOT_YET_CONNECTED'}),command.audit_ref]);await this.audit(actor,'ADMIN_COMMAND_REJECTED','admin_command',command.command_id,command.reason_code,'REJECTED',ctx,undefined,{status:'REJECTED',code:'NOT_YET_CONNECTED'},command.command_id);return{...row,idempotentReplay:false}}
}
