import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createPageMetadata } from '@/lib/seo/metadata';
import { readSessionToken,withPlatform } from '@/lib/customer/server';

export const dynamic='force-dynamic';
export const metadata=createPageMetadata({title:'Regulatory notifications',description:'Private monitoring notifications for managed profiles.',path:'/manage/notifications',noIndex:true});

export default async function NotificationsPage(){const token=await readSessionToken();if(!token)notFound();const rows=await withPlatform(p=>p.monitoringNotifications(token));return <main className="mx-auto max-w-3xl space-y-6 px-4 py-8 sm:py-12"><header><Link href="/manage" className="text-sm underline">Managed profiles</Link><h1 className="mt-4 text-2xl font-semibold text-navy">Regulatory notifications</h1><p className="mt-2 text-sm text-muted-foreground">Private alerts for material changes detected in monitored public records. Alerts do not imply misconduct.</p></header>{rows.length===0?<p className="card-surface p-5 text-sm text-muted-foreground">No notifications.</p>:<ul className="space-y-3">{rows.map(row=><li key={String(row.id)} className="card-surface p-5"><p className="text-xs font-semibold uppercase tracking-wider text-indigo">{String(row.display_name_snapshot)}</p><h2 className="mt-1 font-semibold text-navy">{String(row.title)}</h2><p className="mt-2 text-sm text-muted-foreground">{String(row.summary)}</p><p className="mt-2 text-xs text-muted-foreground">Source: {row.source_system==='fl_dbpr'?'Florida DBPR':String(row.source_system)} &middot; Detected {new Date(String(row.detected_at)).toLocaleDateString('en-US')}</p><div className="mt-3 flex flex-wrap gap-4 text-sm"><Link className="inline-flex min-h-11 items-center underline" href={`/manage/${row.native_profile_id}#monitoring-alerts`}>View alert</Link><Link className="inline-flex min-h-11 items-center underline" href={`/manage/${row.native_profile_id}#record-issues`}>Report a record issue</Link><Link className="inline-flex min-h-11 items-center underline" href={`/manage/${row.native_profile_id}#business-responses`}>Add a business response</Link></div></li>)}</ul>}</main>}
