import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createPageMetadata } from '@/lib/seo/metadata';
import { readSessionToken, withPlatform } from '@/lib/customer/server';
import { CUSTOMER_HUB_REGISTRY } from '@/lib/customer/hub-registry';
import { safeRate } from '@/lib/customer/launch-ops';

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const metadata = createPageMetadata({ title:'Launch operations', description:'Staff-only controlled soft-launch operations.', path:'/internal/launch-ops', noIndex:true });

const number=(value:number|null|undefined)=>value==null?'Unavailable':value.toLocaleString('en-US');
const hours=(value:number|null|undefined)=>value==null?'Unavailable':value<24?`${Math.round(value)}h`:`${Math.round(value/24)}d`;

export default async function LaunchOpsPage(){
  const token=await readSessionToken();
  if(!token)notFound();
  let data;
  try{data=await withPlatform(platform=>platform.launchOpsSnapshot(token));}catch{notFound();}
  const completion=safeRate(Number(data.summary.approvedAll||0),Number(data.summary.claimsAll||0));
  const activation=safeRate(Number(data.summary.activations7d||0),Number(data.summary.approvedOwners||0));
  const cards=[['Claims started · 24h',number(data.summary.claims24h)],['Claims started · 7d',number(data.summary.claims7d)],['Awaiting review',number(data.summary.awaitingReview)],['Needs information',number(data.summary.needsInfo)],['Approved · 7d',number(data.summary.approved7d)],['Median review time',hours(data.summary.medianReviewHours)],['Oldest unresolved',hours(data.summary.oldestUnresolvedHours)],['Owner activations · 7d',number(data.summary.activations7d)]];
  return <main className="mx-auto max-w-7xl space-y-8 px-4 py-10">
    <header><p className="text-xs font-semibold uppercase tracking-wider text-indigo">Staff only · private operations</p><h1 className="mt-1 text-3xl font-semibold text-navy">Controlled soft-launch operations</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Durable customer state is authoritative. Browser analytics supplies behavioral context and never changes claim truth, queue order, or profile standing.</p><p className="mt-2 text-xs text-muted-foreground">Generated {new Date(data.generatedAt).toLocaleString('en-US')}</p></header>
    <section aria-labelledby="summary"><h2 id="summary" className="text-xl font-semibold text-navy">Launch snapshot</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value])=><div className="card-surface p-4" key={label}><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-1 text-2xl font-semibold text-navy">{value}</dd></div>)}</dl></section>
    <section aria-labelledby="health"><h2 id="health" className="text-xl font-semibold text-navy">Daily health</h2><ul className="mt-3 grid gap-3 md:grid-cols-2">{data.health.map(item=><li className="card-surface p-4" key={item.label}><p className="font-semibold">{item.label}: {item.status}</p><p className="mt-1 text-sm text-muted-foreground">{item.reason}</p></li>)}</ul></section>
    <section aria-labelledby="conversion"><h2 id="conversion" className="text-xl font-semibold text-navy">Durable conversion and activation</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="card-surface p-4"><p className="text-sm text-muted-foreground">Approved claims / claims started · all time</p><p className="mt-1 text-xl font-semibold">{completion.numerator} / {completion.denominator} · {completion.percent==null?'Unavailable':`${completion.percent}%`}</p></div><div className="card-surface p-4"><p className="text-sm text-muted-foreground">Owners with a meaningful action in 7d / approved owners</p><p className="mt-1 text-xl font-semibold">{activation.numerator} / {activation.denominator} · {activation.percent==null?'Unavailable':`${activation.percent}%`}</p></div></div><p className="mt-2 text-xs text-muted-foreground">CTA and browser-stage rates remain in Vercel Analytics until a supported server-side analytics query is available.</p></section>
    <section aria-labelledby="queue"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="queue" className="text-xl font-semibold text-navy">Claim queue</h2><p className="text-sm text-muted-foreground">Needs-information claims first, then oldest unresolved work. Maximum 100 rows.</p></div><Link className="link-inline" href="/internal/review">Open claim review</Link></div><div className="mt-3 overflow-x-auto rounded-xl border border-border"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Business profile','Hub / class','Public identifier','State','Claim status','Source','Age','Next action'].map(x=><th className="px-3 py-3" scope="col" key={x}>{x}</th>)}</tr></thead><tbody>{data.claims.map(claim=><tr className="border-t border-border" key={claim.claimId}><td className="max-w-64 break-words px-3 py-3 font-medium"><Link className="underline" href={`/internal/review/${claim.claimId}`}>{claim.displayName}</Link></td><td className="px-3 py-3">{CUSTOMER_HUB_REGISTRY[claim.hub].displayName}<br/><span className="text-muted-foreground">{claim.entityClass.replaceAll('_',' ')}</span></td><td className="max-w-52 break-all px-3 py-3">{claim.identifier}</td><td className="px-3 py-3">{claim.homeState||'—'}</td><td className="px-3 py-3">{claim.status.replaceAll('_',' ')}</td><td className="px-3 py-3">{claim.source.replaceAll('_',' ')}</td><td className="px-3 py-3">{claim.ageBucket}</td><td className="px-3 py-3">{claim.nextAction}</td></tr>)}</tbody></table>{data.claims.length===0?<p className="p-5 text-sm text-muted-foreground">No claims yet. Conversion rates remain unavailable until a denominator exists.</p>:null}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div><h2 className="text-xl font-semibold text-navy">By Trust Hub</h2><ul className="mt-3 space-y-2">{data.byHub.map(row=><li className="card-surface flex flex-wrap justify-between gap-2 p-4" key={row.hub}><span className="font-medium">{CUSTOMER_HUB_REGISTRY[row.hub].displayName}</span><span className="text-sm">{row.started} started · {row.approved} approved · {row.awaiting} awaiting</span></li>)}</ul></div><div><h2 className="text-xl font-semibold text-navy">Acquisition source</h2><p className="text-sm text-muted-foreground">Unknown stays unknown; attribution is measurement only.</p><ul className="mt-3 space-y-2">{data.bySource.map(row=><li className="card-surface flex justify-between p-4" key={row.source}><span>{row.source.replaceAll('_',' ')}</span><span className="font-semibold">{row.count}</span></li>)}</ul></div></section>
    <section className="grid gap-6 lg:grid-cols-3"><div className="card-surface p-5"><h2 className="text-lg font-semibold">Record issues</h2><p className="mt-2 text-2xl font-semibold">{number(data.summary.recordIssuesOpen)}</p><Link className="mt-3 inline-block underline" href="/internal/record-issues">Open issue queue</Link></div><div className="card-surface p-5"><h2 className="text-lg font-semibold">Business responses awaiting action</h2><p className="mt-2 text-2xl font-semibold">{number(data.summary.repliesAwaiting)}</p><Link className="mt-3 inline-block underline" href="/internal/business-replies">Open response queue</Link></div><div className="card-surface p-5"><h2 className="text-lg font-semibold">Monitoring</h2><p className="mt-2 text-sm">{number(data.summary.monitoringEnabled)} on · {number(data.summary.monitoringEligible)} eligible</p><p className="mt-2 text-xs text-muted-foreground">Unsupported Hubs are not counted as failures.</p></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div><h2 className="text-xl font-semibold text-navy">Recovery reasons</h2><ul className="mt-3 card-surface divide-y divide-border">{data.recoveries.map(row=><li className="flex justify-between gap-3 p-3" key={row.reason}><span className="break-all">{row.reason}</span><span>{row.count}</span></li>)}</ul>{!data.recoveries.length?<p className="mt-2 text-sm text-muted-foreground">No durable recovery events recorded.</p>:null}</div><div><h2 className="text-xl font-semibold text-navy">Transactional mail · 30d</h2><ul className="mt-3 card-surface divide-y divide-border">{data.mail.map(row=><li className="flex justify-between p-3" key={row.status}><span>{row.status.toLowerCase()}</span><span>{row.count}</span></li>)}</ul>{!data.mail.length?<p className="mt-2 text-sm text-muted-foreground">No delivery records in this window.</p>:null}</div></section>
  </main>;
}
