import Link from 'next/link';
import { notFound } from 'next/navigation';
import { CUSTOMER_EXPERIENCE_FIXTURES } from '@/lib/customer/experience-fixtures';
import { CLAIM_EXPERIENCE } from '@/lib/customer/experience';
import { ClaimProgress } from '@/components/customer/ClaimProgress';

export const dynamic='force-dynamic';
export default async function CustomerExperienceFixtures({searchParams}:{searchParams:Promise<{scenario?:string}>}) {
  if(process.env.VERCEL_ENV==='production') notFound();
  const {scenario}=await searchParams;
  const selected=CUSTOMER_EXPERIENCE_FIXTURES.find((fixture)=>fixture.id===scenario);
  return <main className="mx-auto max-w-6xl space-y-8 px-4 py-10"><header className="rounded-2xl bg-navy p-6 text-white"><p className="text-xs font-semibold uppercase tracking-wider text-periwinkle">Synthetic customer acceptance environment</p><h1 className="mt-2 text-3xl font-semibold">ATH-CUST-011B acceptance board</h1><p className="mt-2 text-sm text-slate-200">No real customer PII. These fixtures demonstrate consumer states without creating customer or evidence records.</p></header>
  {selected?<section className="space-y-5"><Link href="/internal/customer-experience-fixtures" className="link-inline">Back to all scenarios</Link><div className="card-surface p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo">{selected.area}</p><h2 className="mt-1 text-2xl font-semibold text-navy">{selected.scenario}</h2><p className="mt-2 text-muted-foreground">Expected: {selected.expected}</p></div>{['submitted','under-review','needs-info','approved','rejected'].includes(selected.id)?<><ClaimProgress current={CLAIM_EXPERIENCE[selected.id==='under-review'?'in_review':selected.id==='needs-info'?'needs_info':selected.id as 'submitted'|'approved'|'rejected'].step}/><div className="card-surface p-6"><h2 className="text-xl font-semibold text-navy">{CLAIM_EXPERIENCE[selected.id==='under-review'?'in_review':selected.id==='needs-info'?'needs_info':selected.id as 'submitted'|'approved'|'rejected'].title}</h2><p className="mt-2 text-sm text-muted-foreground">{CLAIM_EXPERIENCE[selected.id==='under-review'?'in_review':selected.id==='needs-info'?'needs_info':selected.id as 'submitted'|'approved'|'rejected'].body}</p></div></>:<div className="card-surface p-6"><h2 className="text-xl font-semibold text-navy">What happens here</h2><p className="mt-2 text-sm text-muted-foreground">{selected.expected}</p><div className="mt-4 flex flex-wrap gap-3"><button className="btn-primary" type="button">Primary next action</button><Link className="btn-secondary" href="/claim/help?category=acceptance_fixture">Contact support</Link></div></div>}</section>:<section><h2 className="text-2xl font-semibold text-navy">Customer journey fixtures</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{CUSTOMER_EXPERIENCE_FIXTURES.map((fixture)=><article key={fixture.id} className="card-surface flex flex-col p-5"><p className="text-xs font-semibold uppercase tracking-wider text-indigo">{fixture.area}</p><h3 className="mt-1 text-lg font-semibold text-navy">{fixture.scenario}</h3><p className="mt-2 flex-1 text-sm text-muted-foreground">{fixture.expected}</p><Link className="btn-primary mt-4" href={`/internal/customer-experience-fixtures?scenario=${fixture.id}`}>Open test</Link></article>)}</div></section>}
  </main>;
}
